// Code generated by sqd-go codegen; DO NOT EDIT.

package codegen

import (
	"github.com/ClickHouse/ch-go/proto"
	"github.com/ethereum/go-ethereum/common"
	"github.com/holiman/uint256"
)

// UInt256ArrayView provides zero-copy access to proto UInt256 arrays.
// It avoids allocating a []uint256.Int slice on every access.
type UInt256ArrayView struct {
	data []proto.UInt256
}

// NewUInt256ArrayView creates a view from a proto column array row.
func NewUInt256ArrayView(data []proto.UInt256) UInt256ArrayView {
	return UInt256ArrayView{data: data}
}

// Len returns the number of elements in the array.
func (v UInt256ArrayView) Len() int {
	return len(v.data)
}

// At returns the element at index i as uint256.Int.
// This is a zero-copy operation - it returns the value directly.
func (v UInt256ArrayView) At(i int) uint256.Int {
	if i < 0 || i >= len(v.data) {
		return uint256.Int{}
	}
	return uint256FromProto(&v.data[i])
}

// ToSlice copies all elements to a []uint256.Int slice.
// This allocates and should only be used when a slice is explicitly needed.
func (v UInt256ArrayView) ToSlice(dst []uint256.Int) []uint256.Int {
	if cap(dst) >= len(v.data) {
		dst = dst[:len(v.data)]
	} else {
		dst = make([]uint256.Int, len(v.data))
	}
	for i := range dst {
		dst[i] = v.At(i)
	}
	return dst
}

// ForEach calls fn for each element in the array.
// This provides iteration without allocating a slice.
func (v UInt256ArrayView) ForEach(fn func(i int, value uint256.Int) bool) {
	for i := 0; i < len(v.data); i++ {
		if !fn(i, v.At(i)) {
			break
		}
	}
}

// HashArrayView provides zero-copy access to proto hash arrays (32-byte fixed strings).
type HashArrayView struct {
	data [][]byte
}

// NewHashArrayView creates a view from a proto column array row.
func NewHashArrayView(data [][]byte) HashArrayView {
	return HashArrayView{data: data}
}

// Len returns the number of elements in the array.
func (v HashArrayView) Len() int {
	return len(v.data)
}

// At returns the element at index i as a 32-byte slice.
// The returned slice is a view into the proto data and must not be modified.
func (v HashArrayView) At(i int) []byte {
	if i < 0 || i >= len(v.data) {
		return nil
	}
	return v.data[i]
}

// ToHashSlice copies all elements to a []common.Hash slice.
// This allocates and should only be used when a slice is explicitly needed.
func (v HashArrayView) ToHashSlice(dst []common.Hash) []common.Hash {
	if cap(dst) >= len(v.data) {
		dst = dst[:len(v.data)]
	} else {
		dst = make([]common.Hash, len(v.data))
	}
	for i := range dst {
		copy(dst[i][:], v.At(i))
	}
	return dst
}

// BoolArrayView provides zero-copy access to proto bool arrays.
type BoolArrayView struct {
	data []byte
}

// NewBoolArrayView creates a view from a packed byte array.
func NewBoolArrayView(data []byte) BoolArrayView {
	return BoolArrayView{data: data}
}

// Len returns the number of elements in the array.
func (v BoolArrayView) Len() int {
	return len(v.data)
}

// At returns the boolean value at index i.
func (v BoolArrayView) At(i int) bool {
	if i < 0 || i >= len(v.data) {
		return false
	}
	return v.data[i] != 0
}

// ToSlice copies all elements to a []bool slice.
// This allocates and should only be used when a slice is explicitly needed.
func (v BoolArrayView) ToSlice(dst []bool) []bool {
	if cap(dst) >= len(v.data) {
		dst = dst[:len(v.data)]
	} else {
		dst = make([]bool, len(v.data))
	}
	for i := range dst {
		dst[i] = v.At(i)
	}
	return dst
}

// Helper function to convert proto.UInt256 to uint256.Int
func uint256FromProto(v *proto.UInt256) uint256.Int {
	if v == nil {
		return uint256.Int{}
	}
	return uint256.Int{
		v.Low.Low,
		v.Low.High,
		v.High.Low,
		v.High.High,
	}
}
