package codegen

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"unicode"

	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/ethereum/go-ethereum/crypto"
	"github.com/franz101/sqd-go/internal/config"
	"github.com/franz101/sqd-go/internal/template"
)

// Manifest is the JSON manifest written to .sqd/generated/ for the runtime.
type Manifest struct {
	Name       string          `json:"name"`
	Ecosystem  string          `json:"ecosystem,omitempty"`
	Fork       string          `json:"fork,omitempty"`
	ConfigPath string          `json:"config_path"`
	Chains     []ManifestChain `json:"chains"`
}

// ManifestChain is one chain entry in the manifest.
type ManifestChain struct {
	ID         uint64             `json:"id"`
	StartBlock uint64             `json:"start_block"`
	EndBlock   *uint64            `json:"end_block,omitempty"`
	Contracts  []ManifestContract `json:"contracts"`
}

// ManifestContract is one contract entry in the manifest.
type ManifestContract struct {
	Name    string   `json:"name"`
	Events  []string `json:"events"`
	Address any      `json:"address,omitempty"`
}

// GenerateProject runs the full codegen pipeline: validates config, generates
// the JSON manifest, Go event types, parsers, inserters, and hot-state code.
func GenerateProject(project *config.Project) (string, error) {
	if err := config.Validate(project.Config); err != nil {
		return "", err
	}
	outDir := filepath.Join(project.Root, ".sqd", "generated")
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return "", err
	}
	goOutDir := filepath.Join(project.Root, "generated")
	if err := os.MkdirAll(goOutDir, 0o755); err != nil {
		return "", err
	}
	outPath := filepath.Join(outDir, "manifest.json")

	manifest := buildManifest(project)
	if err := writeJSON(outPath, manifest); err != nil {
		return "", err
	}

	events, err := buildEventSpecs(project.Config)
	if err != nil {
		return "", err
	}
	customTables, err := loadCustomTableSpecs(project.Root)
	if err != nil {
		return "", err
	}
	customSchemaTables, err := loadCustomSchemaSpecs(project.Root, filepath.Dir(project.ConfigPath))
	if err != nil {
		return "", err
	}

	schemaSQL := generateSchemaSQL(project.Config, events)
	if len(customTables) > 0 {
		schemaSQL += generateCustomSchemaSQL(project.Config, customTables)
	}
	if err := os.WriteFile(filepath.Join(outDir, "schema.sql"), []byte(schemaSQL), 0o644); err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "schema.sql"), []byte(schemaSQL), 0o644); err != nil {
		return "", err
	}

	if len(customSchemaTables) > 0 {
		customSchemaSQL := generateCustomSchemaSQL(project.Config, customSchemaTables)
		if err := os.WriteFile(filepath.Join(outDir, "custom_schema.sql"), []byte(customSchemaSQL), 0o644); err != nil {
			return "", err
		}
		if err := os.WriteFile(filepath.Join(goOutDir, "custom_schema.sql"), []byte(customSchemaSQL), 0o644); err != nil {
			return "", err
		}
	} else {
		_ = os.Remove(filepath.Join(outDir, "custom_schema.sql"))
		_ = os.Remove(filepath.Join(goOutDir, "custom_schema.sql"))
	}

	if err := os.WriteFile(filepath.Join(outDir, "views.sql"), []byte(generateViewsSQL(project.Config, events)), 0o644); err != nil {
		return "", err
	}
	goCode, err := generateGoCode(project.Config, events)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "events.go"), goCode, 0o644); err != nil {
		return "", err
	}

	schemaGoCode, err := generateSchemaGo(events)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "schema.go"), schemaGoCode, 0o644); err != nil {
		return "", err
	}
	inserterCode, err := generateInserterGo(project.Config, events)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "inserter.go"), inserterCode, 0o644); err != nil {
		return "", err
	}

	viewsCode, err := generateProtoViewGo(events)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "views.go"), viewsCode, 0o644); err != nil {
		return "", err
	}

	allCustomTables := append([]customTableSpec{}, customTables...)
	allCustomTables = append(allCustomTables, customSchemaTables...)

	hotStateTables := buildHotStateTables(allCustomTables, project.Config, events)

	// Determine if we should generate/update generated/custom_processor.go.
	// A user custom_processor.go next to config.yaml belongs to the project
	// package and registers CustomProcessFn; it must not suppress framework
	// generation in the generated package.
	customProcessorPath := filepath.Join(goOutDir, "custom_processor.go")

	// Helper to check if file has user code or is codegen-owned
	checkFile := func(path string) (exists bool, codegenOwned bool) {
		data, err := os.ReadFile(path)
		if err != nil {
			return false, false
		}
		if strings.Contains(string(data), "Code generated by sqd-go codegen; DO NOT EDIT.") {
			return true, true
		}
		return true, false
	}

	customProcessorExists, customProcessorCodegenOwned := checkFile(customProcessorPath)
	if !customProcessorExists || customProcessorCodegenOwned {
		// Generate the custom processor
		var customProcessorCode []byte
		var err error
		// For backward compatibility, if the project is Uniswap/ERC20, we use ERC20 generator.
		// Otherwise we can generate the empty/generic skeleton.
		if project.Config.Name == "case_1_lbtc_event_only" && len(hotStateTables) == 0 {
			customProcessorCode, err = generateCustomProcessorGo(events)
		} else {
			customProcessorCode, err = generateEmptyCustomProcessorGo(project.Config, events, hotStateTables)
		}
		if err != nil {
			return "", err
		}
		if err := os.WriteFile(customProcessorPath, customProcessorCode, 0o644); err != nil {
			return "", err
		}
	}

	hotstatePath := filepath.Join(goOutDir, "hotstate.go")
	statePath := filepath.Join(goOutDir, "state.go")
	if len(hotStateTables) > 0 {
		hotStateCode, err := generateHotStateGo(hotStateTables, events)
		if err != nil {
			return "", err
		}
		if err := os.WriteFile(hotstatePath, hotStateCode, 0o644); err != nil {
			return "", err
		}
		stateExists, stateCodegenOwned := checkFile(statePath)
		if !stateExists || stateCodegenOwned {
			stateCode, err := generateStateGo(hotStateTables, project.Config, events)
			if err != nil {
				return "", err
			}
			if err := os.WriteFile(statePath, stateCode, 0o644); err != nil {
				return "", err
			}
		}
	} else {
		_ = os.Remove(hotstatePath)
		if stateExists, stateCodegenOwned := checkFile(statePath); stateExists && stateCodegenOwned {
			_ = os.Remove(statePath)
		}
	}

	_ = os.Remove(filepath.Join(goOutDir, "prefetch.go"))

	compactionCode, err := generateCompactionGo(project.Config, allCustomTables)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "compaction.go"), compactionCode, 0o644); err != nil {
		return "", err
	}

	ringBufferCode, err := generateRingBufferGo(events)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "ringbuffer.go"), ringBufferCode, 0o644); err != nil {
		return "", err
	}

	parserCode, err := generateParserGo(events)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(goOutDir, "parser.go"), parserCode, 0o644); err != nil {
		return "", err
	}

	// Generate events_easyjson.go (after the other files, so the package compiles).
	if err := runEasyjson(goOutDir); err != nil {
		if _, statErr := os.Stat(filepath.Join(project.Root, "go.mod")); os.IsNotExist(statErr) {
			// Some unit tests generate into a bare temp dir and never build the
			// output; easyjson cannot resolve the package without a module, so warn
			// and continue rather than failing those tests.
			fmt.Printf("WARNING: easyjson skipped (no module context for %s): %v\n", goOutDir, err)
		} else {
			return "", fmt.Errorf("easyjson failed: %w", err)
		}
	}

	return outPath, nil
}

// easyjsonModuleVersion pins the easyjson CLI used by the `go run` fallback to the
// version declared in go.mod, so generated marshalers match the runtime package.
const easyjsonModuleVersion = "v0.7.7"

// runEasyjson regenerates events_easyjson.go in dir. It prefers an installed
// `easyjson` binary (fast path for dev machines) and otherwise runs the pinned
// CLI via `go run`, which needs no separate install — important for CI and for
// `--state` standalone builds in a clean environment (a notebook).
func runEasyjson(dir string) error {
	if path, err := exec.LookPath("easyjson"); err == nil {
		if runErr := runCmdIn(dir, path, "-all", "events.go"); runErr == nil {
			return nil
		}
		// An installed binary that failed (e.g. version skew) falls through to
		// the module-pinned `go run` below.
	}
	return runCmdIn(dir, "go", "run", "github.com/mailru/easyjson/easyjson@"+easyjsonModuleVersion, "-all", "events.go")
}

// runCmdIn runs name with args in dir, surfacing stderr on failure.
func runCmdIn(dir, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("%s: %w (stderr: %s)", name, err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

func buildHotStateTables(customTables []customTableSpec, cfg *config.Config, events []eventSpec) []customTableSpec {
	hotStateTables := append([]customTableSpec{}, customTables...)
	if cfg == nil {
		return hotStateTables
	}
	for _, state := range cfg.State {
		if _, ok := findStateCustomTableSpec(customTables, state); ok {
			continue
		}
		targetEv, err := findStateEventSpec(events, state)
		if err == nil {
			hotStateTables = append(hotStateTables, stateEventToCustomTableSpec(targetEv, state))
		}
	}
	return hotStateTables
}

func buildManifest(project *config.Project) Manifest {
	cfg := project.Config
	manifest := Manifest{
		Name:       cfg.Name,
		ConfigPath: project.ConfigPath,
	}
	if cfg.Ecosystem != nil {
		manifest.Ecosystem = *cfg.Ecosystem
	}
	manifest.Fork = string(cfg.ForkMode())
	for _, chain := range cfg.Chains {
		mc := ManifestChain{
			ID:         chain.ID,
			StartBlock: chain.StartBlock,
			EndBlock:   chain.EndBlock,
		}
		for _, contract := range chain.Contracts {
			out := ManifestContract{
				Name:    contract.Name,
				Address: contract.Address,
			}
			for _, event := range contract.Events {
				out.Events = append(out.Events, event.Event)
			}
			mc.Contracts = append(mc.Contracts, out)
		}
		manifest.Chains = append(manifest.Chains, mc)
	}
	return manifest
}

// Generate is a convenience wrapper: loads a project from path and runs GenerateProject.
func Generate(path string) (string, error) {
	project, err := config.LoadProject(path)
	if err != nil {
		return "", fmt.Errorf("load project: %w", err)
	}
	return GenerateProject(project)
}

func writeJSON(path string, v any) error {
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()

	enc := json.NewEncoder(file)
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

type eventSpec struct {
	ChainID         uint64
	ContractName    string
	ContractIdent   string
	EventName       string
	EventIdent      string
	EventSignature  string
	CanonicalSig    string
	Topic0          string
	ViewName        string
	TableName       string
	GoTypeName      string
	GoConstPrefix   string
	ContractAddress []string
	Args            []eventArg
	DecodeArgs      []eventArg
}

type eventArg struct {
	Name           string
	ColumnName     string
	SolidityType   string
	ClickHouseType string
	Indexed        bool
	Omitted        bool
	GoFieldName    string
	GoType         string
}

type parsedEvent struct {
	Name         string
	CanonicalSig string
	Args         []eventArg
}

func buildEventSpecs(cfg *config.Config) ([]eventSpec, error) {
	var specs []eventSpec
	usedViews := make(map[string]int)
	usedTypes := make(map[string]int)
	usedConsts := make(map[string]int)

	isArgOmitted := func(omitList []string, name string) bool {
		for _, o := range omitList {
			if strings.EqualFold(o, name) || strings.EqualFold(strings.ReplaceAll(o, "_", ""), strings.ReplaceAll(name, "_", "")) {
				return true
			}
		}
		return false
	}

	for _, chain := range cfg.Chains {
		for _, contract := range chain.Contracts {
			for _, ev := range contract.Events {
				parsed, err := parseEvent(ev.Event)
				if err != nil {
					return nil, fmt.Errorf("%s.%s: %w", contract.Name, ev.Event, err)
				}
				eventName := parsed.Name
				if ev.Name != nil && strings.TrimSpace(*ev.Name) != "" {
					eventName = strings.TrimSpace(*ev.Name)
				}
				contractIdent := exportIdent(contract.Name)
				eventIdent := exportIdent(eventName)
				viewName := uniqueLower(usedViews, toSnake(contract.Name+"_"+eventName))
				typeName := uniqueExported(usedTypes, contractIdent+eventIdent)
				constPrefix := uniqueExported(usedConsts, contractIdent+eventIdent)

				var filteredArgs []eventArg
				var decodeArgs []eventArg
				for _, arg := range parsed.Args {
					if isArgOmitted(ev.Omit, arg.Name) {
						arg.Omitted = true
						decodeArgs = append(decodeArgs, arg)
						continue
					}
					filteredArgs = append(filteredArgs, arg)
					decodeArgs = append(decodeArgs, arg)
				}

				specs = append(specs, eventSpec{
					ChainID:         chain.ID,
					ContractName:    contract.Name,
					ContractIdent:   contractIdent,
					EventName:       parsed.Name,
					EventIdent:      eventIdent,
					EventSignature:  strings.TrimSpace(ev.Event),
					CanonicalSig:    parsed.CanonicalSig,
					Topic0:          crypto.Keccak256Hash([]byte(parsed.CanonicalSig)).Hex(),
					ViewName:        viewName,
					TableName:       viewName + "_events",
					GoTypeName:      typeName,
					GoConstPrefix:   constPrefix,
					ContractAddress: addresses(contract.Address),
					Args:            filteredArgs,
					DecodeArgs:      decodeArgs,
				})
			}
		}
	}
	return specs, nil
}

func parseEvent(sig string) (*parsedEvent, error) {
	sig = strings.TrimSpace(sig)
	sig = strings.TrimPrefix(sig, "event ")
	open := strings.IndexByte(sig, '(')
	close := strings.LastIndexByte(sig, ')')
	if open <= 0 || close <= open {
		return nil, fmt.Errorf("invalid event signature")
	}
	name := strings.TrimSpace(sig[:open])
	if name == "" {
		return nil, fmt.Errorf("event name is required")
	}
	args := splitArgs(sig[open+1 : close])
	abiJSON := eventABIJSON(name, args)
	parsed, err := abi.JSON(strings.NewReader(abiJSON))
	if err != nil {
		return nil, err
	}
	abiEvent, ok := parsed.Events[name]
	if !ok {
		return nil, fmt.Errorf("event not found after parsing")
	}
	usedFields := make(map[string]int)
	out := &parsedEvent{Name: name, CanonicalSig: abiEvent.Sig}
	for i, input := range abiEvent.Inputs {
		argName := input.Name
		if strings.TrimSpace(argName) == "" {
			argName = fmt.Sprintf("p%d", i)
		}
		fieldName := uniqueExported(usedFields, exportIdent(argName))
		out.Args = append(out.Args, eventArg{
			Name:           argName,
			ColumnName:     argName,
			SolidityType:   input.Type.String(),
			ClickHouseType: clickHouseType(input.Type.String()),
			Indexed:        input.Indexed,
			GoFieldName:    fieldName,
			GoType:         goType(input.Type.String()),
		})
	}
	return out, nil
}

func eventABIJSON(name string, args []string) string {
	inputs := make([]string, 0, len(args))
	for i, arg := range args {
		arg = strings.TrimSpace(arg)
		if arg == "" {
			continue
		}
		parts := strings.Fields(arg)
		if len(parts) == 0 {
			continue
		}
		typ := normalizeSolidityType(parts[0])
		indexed := false
		paramName := fmt.Sprintf("p%d", i)
		for _, part := range parts[1:] {
			if part == "indexed" {
				indexed = true
				continue
			}
			paramName = part
		}
		inputs = append(inputs, fmt.Sprintf(
			`{"indexed":%t,"name":%s,"type":%s}`,
			indexed, strconv.Quote(paramName), strconv.Quote(typ),
		))
	}
	return fmt.Sprintf(`[{"anonymous":false,"inputs":[%s],"name":%s,"type":"event"}]`,
		strings.Join(inputs, ","), strconv.Quote(name))
}

func splitArgs(args string) []string {
	args = strings.TrimSpace(args)
	if args == "" {
		return nil
	}
	var out []string
	start := 0
	depth := 0
	for i, r := range args {
		switch r {
		case '(', '[':
			depth++
		case ')', ']':
			if depth > 0 {
				depth--
			}
		case ',':
			if depth == 0 {
				out = append(out, strings.TrimSpace(args[start:i]))
				start = i + 1
			}
		}
	}
	out = append(out, strings.TrimSpace(args[start:]))
	return out
}

func generateSchemaSQL(cfg *config.Config, events []eventSpec) string {
	type colData struct {
		ColumnIdent    string
		ClickHouseType string
	}
	type eventData struct {
		DatabaseIdent          string
		TableIdent             string
		Engine                 string
		Collapsing             bool
		IncludeChainID         bool
		IncludeBlockHash       bool
		IncludeContractAddress bool
		IncludeTransactionHash bool
		Columns                []colData
		Key                    string
	}

	tmplData := struct {
		DatabaseIdent          string
		StoreBlocks            bool
		StoreRawLogs           bool
		Engine                 string
		Collapsing             bool
		IncludeChainID         bool
		IncludeBlockHash       bool
		IncludeContractAddress bool
		IncludeTransactionHash bool
	}{
		DatabaseIdent:          quoteSQLIdent(cfg.Name),
		StoreBlocks:            cfg.ShouldStoreBlocks(),
		StoreRawLogs:           cfg.ShouldStoreRawLogs(),
		Engine:                 mergeTreeEngine(cfg.ForkMode().UsesCollapsingMergeTree()),
		Collapsing:             cfg.ForkMode().UsesCollapsingMergeTree(),
		IncludeChainID:         cfg.MetadataIncluded("chain_id"),
		IncludeBlockHash:       cfg.MetadataIncluded("block_hash"),
		IncludeContractAddress: cfg.MetadataIncluded("contract_address"),
		IncludeTransactionHash: cfg.MetadataIncluded("transaction_hash"),
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("-- Code generated by sqd-go codegen; DO NOT EDIT.\n\nCREATE DATABASE IF NOT EXISTS %s;\n", tmplData.DatabaseIdent))

	if tmplData.StoreBlocks {
		b.WriteString("\n")
		b.WriteString(template.MustExecute("sql/createBlocksTable", tmplData))
		b.WriteString(";\n")
	}

	if tmplData.StoreRawLogs {
		b.WriteString("\n")
		b.WriteString(template.MustExecute("sql/createLogsTable", tmplData))
		b.WriteString(";\n")
	}

	b.WriteString("\n")
	b.WriteString(template.MustExecute("sql/createSyncStateTable", tmplData))
	b.WriteString(";\n")

	for _, ev := range events {
		b.WriteString("\n")
		var cols []colData
		for _, arg := range ev.Args {
			cols = append(cols, colData{
				ColumnIdent:    quoteSQLIdent(arg.ColumnName),
				ClickHouseType: arg.ClickHouseType,
			})
		}

		evData := eventData{
			DatabaseIdent:          tmplData.DatabaseIdent,
			TableIdent:             quoteSQLIdent(ev.TableName),
			Engine:                 tmplData.Engine,
			Collapsing:             tmplData.Collapsing,
			IncludeChainID:         tmplData.IncludeChainID,
			IncludeBlockHash:       tmplData.IncludeBlockHash,
			IncludeContractAddress: tmplData.IncludeContractAddress,
			IncludeTransactionHash: tmplData.IncludeTransactionHash,
			Columns:                cols,
			Key:                    eventPrimaryKey(ev),
		}

		b.WriteString(template.MustExecute("sql/createEventTable", evData))
		b.WriteString(";\n")
	}

	// Add positions table for hot state backwards compatibility if present
	if hasERC20Transfer(events) {
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf(`CREATE TABLE IF NOT EXISTS %[1]s.erc20_address_positions (
  address FixedString(20),
  balance_raw String,
  total_in_raw String,
  total_out_raw String,
  net_flow_raw String,
  realized_pnl_raw String,
  transfer_count UInt64,
  updated_at_block UInt64,
  updated_at DateTime64(3, 'UTC') DEFAULT now64(3)
) ENGINE = ReplacingMergeTree(updated_at_block)
ORDER BY address;
`, tmplData.DatabaseIdent))
	}

	return b.String()
}

func mergeTreeEngine(collapsing bool) string {
	if collapsing {
		return "CollapsingMergeTree(sign)"
	}
	return "MergeTree()"
}

func eventPrimaryKey(ev eventSpec) string {
	parts := make([]string, 0, 5)
	for i := 0; i < len(ev.Args) && i < 2; i++ {
		parts = append(parts, quoteSQLIdent(ev.Args[i].ColumnName))
	}
	parts = append(parts, "block_number", "transaction_index", "log_index")
	return strings.Join(parts, ", ")
}

func generateViewsSQL(cfg *config.Config, events []eventSpec) string {
	if !cfg.ShouldStoreRawLogs() {
		return "-- Raw logs omitted by config\n"
	}
	db := quoteSQLIdent(cfg.Name)
	collapsing := cfg.ForkMode().UsesCollapsingMergeTree()

	includeChainID := cfg.MetadataIncluded("chain_id")
	includeBlockHash := cfg.MetadataIncluded("block_hash")
	includeContractAddress := cfg.MetadataIncluded("contract_address")
	includeTransactionHash := cfg.MetadataIncluded("transaction_hash")

	type viewEventData struct {
		ViewIdent    string
		ChainID      uint64
		EventName    string
		Topic0Hex    string
		HasAddresses bool
		AddressList  string
		SelectFields []string
	}

	var viewEvents []viewEventData
	for _, ev := range events {
		var fields []string
		if includeChainID {
			fields = append(fields, "chain_id")
		}
		fields = append(fields, "block_number", "block_timestamp")
		if includeBlockHash {
			fields = append(fields, "block_hash")
		}
		if includeContractAddress {
			fields = append(fields, "concat('0x', lower(hex(address))) AS contract_address")
		}
		if includeTransactionHash {
			fields = append(fields, "concat('0x', lower(hex(transaction_hash))) AS transaction_hash")
		}
		fields = append(fields, "transaction_index", "log_index")

		for _, arg := range ev.Args {
			fields = append(fields, jsonExtractExpr(arg)+" AS "+quoteSQLIdent(arg.ColumnName))
		}

		var addrList string
		if len(ev.ContractAddress) > 0 {
			var addrs []string
			for _, addr := range ev.ContractAddress {
				addrs = append(addrs, "unhex("+quoteSQLString(strip0x(addr))+")")
			}
			addrList = strings.Join(addrs, ", ")
		}

		viewEvents = append(viewEvents, viewEventData{
			ViewIdent:    quoteSQLIdent(ev.ViewName),
			ChainID:      ev.ChainID,
			EventName:    ev.EventName,
			Topic0Hex:    strip0x(ev.Topic0),
			HasAddresses: len(ev.ContractAddress) > 0,
			AddressList:  addrList,
			SelectFields: fields,
		})
	}

	tmplData := struct {
		DatabaseIdent string
		Collapsing    bool
		Events        []viewEventData
	}{
		DatabaseIdent: db,
		Collapsing:    collapsing,
		Events:        viewEvents,
	}

	return template.MustExecute("sql/viewsSQL", tmplData)
}

func generateGoCode(cfg *config.Config, events []eventSpec) ([]byte, error) {
	var b bytes.Buffer

	// Build import block
	var imports []string
	if len(events) > 0 {
		imports = append(imports, `"encoding/json"`)
		imports = append(imports, `"fmt"`)
		imports = append(imports, `"github.com/ethereum/go-ethereum/common"`)
		imports = append(imports, `"github.com/franz101/sqd-go/abiunpack"`)
	}
	if hasUint256Type(events) {
		imports = append(imports, `"github.com/holiman/uint256"`)
	}
	imports = append(imports, `"time"`)

	var singleImport string
	var multiImports []string
	if len(imports) == 1 {
		singleImport = imports[0]
	} else if len(imports) > 1 {
		multiImports = imports
	}

	tmplData := struct {
		Imports        []string
		SingleImport   string
		ProjectName    string
		IncludeChainID bool
		Events         []eventSpec
	}{
		Imports:        multiImports,
		SingleImport:   singleImport,
		ProjectName:    cfg.Name,
		IncludeChainID: cfg.MetadataIncluded("chain_id"),
		Events:         events,
	}

	src := template.MustExecute("code/eventsGo", tmplData)

	b.WriteString(src)
	b.WriteString("\n")

	renderUnpackDispatcher(&b, events)
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

// unpackEventTmpl is the per-event data the dispatcher template interpolates.
type unpackEventTmpl struct {
	Index           int      // event ordinal, names _topic<i> / _addr<i>_<j>
	Topic0Quoted    string   // strconv.Quote'd topic0 hash
	Addrs           []string // strconv.Quote'd contract addresses
	AddrMatchExpr   string   // address-match guard ("true" when no addresses)
	GoTypeName      string   // event struct/unpacker name
	EventNameQuoted string   // strconv.Quote'd human event name
}

// renderUnpackDispatcher renders the log decode entry points (topic/addr
// constants + UnpackLog dispatch). The per-event Unpack<T>LogWithMeta functions
// still use their own imperative renderer (renderEventUnpackFunction), so they
// are appended after the template output.
func renderUnpackDispatcher(b *bytes.Buffer, events []eventSpec) {
	if len(events) == 0 {
		return
	}

	data := struct {
		UsesAddress bool
		Events      []unpackEventTmpl
	}{UsesAddress: dispatcherUsesAddress(events)}
	for i, ev := range events {
		et := unpackEventTmpl{
			Index:           i,
			Topic0Quoted:    strconv.Quote(ev.Topic0),
			AddrMatchExpr:   addressMatchExpr(i, len(ev.ContractAddress)),
			GoTypeName:      ev.GoTypeName,
			EventNameQuoted: strconv.Quote(ev.EventName),
		}
		for _, addr := range ev.ContractAddress {
			et.Addrs = append(et.Addrs, strconv.Quote(addr))
		}
		data.Events = append(data.Events, et)
	}

	b.WriteString(template.MustExecute("code/unpackDispatcher", data))

	for _, ev := range events {
		renderEventUnpackFunction(b, ev)
	}
}

func dispatcherUsesAddress(events []eventSpec) bool {
	for _, ev := range events {
		if len(ev.ContractAddress) > 0 {
			return true
		}
	}
	return false
}

func addressMatchExpr(eventIdx, addrCount int) string {
	if addrCount == 0 {
		return "true"
	}
	var parts []string
	for i := 0; i < addrCount; i++ {
		parts = append(parts, fmt.Sprintf("logAddress == _addr%d_%d", eventIdx, i))
	}
	return "(" + strings.Join(parts, " || ") + ")"
}

// renderEventUnpackFunction renders one event's Unpack<T>Log / Unpack<T>LogWithMeta
// pair. The decode statements are highly ABI-type dependent, so they are rendered
// by the leaf decoders into a sub-buffer and handed to the template as DecodeBody.
func renderEventUnpackFunction(b *bytes.Buffer, ev eventSpec) {
	decodeArgs := ev.DecodeArgs
	if len(decodeArgs) == 0 {
		decodeArgs = ev.Args
	}
	requiredTopics := 1
	for _, arg := range decodeArgs {
		if arg.Indexed {
			requiredTopics++
		}
	}

	// Render the per-argument decode statements (indexed args from topics, the
	// rest walked word-by-word through the data payload) into their own buffer.
	var body bytes.Buffer
	topicIdx := 1
	dataWord := 0
	for _, arg := range decodeArgs {
		if arg.Indexed {
			if !arg.Omitted {
				renderIndexedDecode(&body, arg, topicIdx)
			}
			topicIdx++
			continue
		}
		if !arg.Omitted {
			renderDataDecode(&body, ev.GoTypeName, arg, dataWord)
		}
		dataWord += abiHeadWords(arg.SolidityType)
	}

	b.WriteString(template.MustExecute("code/unpackEventFunc", struct {
		GoTypeName     string
		RequiredTopics int
		DecodeBody     string
	}{
		GoTypeName:     ev.GoTypeName,
		RequiredTopics: requiredTopics,
		DecodeBody:     body.String(),
	}))
}

func renderIndexedDecode(b *bytes.Buffer, arg eventArg, topicIdx int) {
	topic := fmt.Sprintf("topics[%d]", topicIdx)
	switch {
	case arg.SolidityType == "address":
		b.WriteString(fmt.Sprintf("\tev.%s = common.HexToAddress(%s)\n", arg.GoFieldName, topic))
	case arg.SolidityType == "bool":
		b.WriteString(fmt.Sprintf("\tev.%s = abiunpack.TopicBool(%s)\n", arg.GoFieldName, topic))
	case arg.SolidityType == "bytes32":
		b.WriteString(fmt.Sprintf("\tev.%s = common.HexToHash(%s)\n", arg.GoFieldName, topic))
	case isBytesN(arg.SolidityType):
		b.WriteString(fmt.Sprintf("\tabiunpack.DecodeTopicFixedBytes(%s, ev.%s[:], %d)\n", topic, arg.GoFieldName, bytesNSize(arg.SolidityType)))
	case strings.HasPrefix(arg.SolidityType, "uint"), strings.HasPrefix(arg.SolidityType, "int"):
		b.WriteString(fmt.Sprintf("\tabiunpack.DecodeTopicUint256(%s, &ev.%s)\n", topic, arg.GoFieldName))
	default:
		b.WriteString(fmt.Sprintf("\t// %s has unsupported indexed ABI type %q.\n", arg.GoFieldName, arg.SolidityType))
	}
}

func renderDataDecode(b *bytes.Buffer, eventType string, arg eventArg, wordIdx int) {
	label := eventType + "." + arg.GoFieldName
	solType := arg.SolidityType
	if elem, ok := dynamicArrayElement(solType); ok {
		renderDynamicArrayDecode(b, label, arg, elem, wordIdx)
		return
	}
	if elem, length, ok := fixedArrayElement(solType); ok {
		renderFixedArrayDecode(b, label, arg, elem, length, wordIdx)
		return
	}
	switch {
	case solType == "bytes":
		b.WriteString(fmt.Sprintf("\tif ev.%s, ok = abiunpack.Bytes(data, %d); !ok {\n", arg.GoFieldName, wordIdx))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid bytes\", %q)\n\t}\n", label))
	case solType == "string":
		b.WriteString("\tvar raw" + arg.GoFieldName + " []byte\n")
		b.WriteString(fmt.Sprintf("\tif raw%s, ok = abiunpack.Bytes(data, %d); !ok {\n", arg.GoFieldName, wordIdx))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid string\", %q)\n\t}\n", label))
		b.WriteString(fmt.Sprintf("\tev.%s = string(raw%s)\n", arg.GoFieldName, arg.GoFieldName))
	case solType == "address":
		renderWordGuard(b, label, wordIdx)
		b.WriteString(fmt.Sprintf("\tev.%s = common.BytesToAddress(word[12:32])\n", arg.GoFieldName))
	case solType == "bool":
		renderWordGuard(b, label, wordIdx)
		b.WriteString(fmt.Sprintf("\tif ev.%s, ok = abiunpack.Bool(word); !ok {\n", arg.GoFieldName))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid bool word\", %q)\n\t}\n", label))
	case solType == "bytes32":
		renderWordGuard(b, label, wordIdx)
		b.WriteString(fmt.Sprintf("\tev.%s = common.BytesToHash(word)\n", arg.GoFieldName))
	case isBytesN(solType):
		renderWordGuard(b, label, wordIdx)
		b.WriteString(fmt.Sprintf("\tcopy(ev.%s[:], word[:%d])\n", arg.GoFieldName, bytesNSize(solType)))
	case strings.HasPrefix(solType, "uint"), strings.HasPrefix(solType, "int"):
		renderWordGuard(b, label, wordIdx)
		b.WriteString(fmt.Sprintf("\tev.%s.SetBytes32(word)\n", arg.GoFieldName))
	default:
		b.WriteString(fmt.Sprintf("\t// %s has unsupported ABI type %q.\n", arg.GoFieldName, solType))
	}
}

func renderDynamicArrayDecode(b *bytes.Buffer, label string, arg eventArg, elem string, wordIdx int) {
	switch {
	case strings.HasPrefix(elem, "uint"), strings.HasPrefix(elem, "int"):
		b.WriteString(fmt.Sprintf("\tif ev.%s, ok = abiunpack.Uint256Array(data, %d); !ok {\n", arg.GoFieldName, wordIdx))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid uint256 array\", %q)\n\t}\n", label))
	case elem == "address":
		b.WriteString(fmt.Sprintf("\tif ev.%s, ok = abiunpack.AddressArray(data, %d); !ok {\n", arg.GoFieldName, wordIdx))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid address array\", %q)\n\t}\n", label))
	case elem == "bytes32":
		b.WriteString(fmt.Sprintf("\tif ev.%s, ok = abiunpack.HashArray(data, %d); !ok {\n", arg.GoFieldName, wordIdx))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid hash array\", %q)\n\t}\n", label))
	case elem == "bool":
		b.WriteString(fmt.Sprintf("\tif ev.%s, ok = abiunpack.BoolArray(data, %d); !ok {\n", arg.GoFieldName, wordIdx))
		b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid bool array\", %q)\n\t}\n", label))
	default:
		b.WriteString(fmt.Sprintf("\t// %s has unsupported dynamic array ABI type %q.\n", arg.GoFieldName, arg.SolidityType))
	}
}

func renderFixedArrayDecode(b *bytes.Buffer, label string, arg eventArg, elem string, length int, wordIdx int) {
	for i := 0; i < length; i++ {
		target := fmt.Sprintf("ev.%s[%d]", arg.GoFieldName, i)
		currentLabel := fmt.Sprintf("%s[%d]", label, i)
		switch {
		case strings.HasPrefix(elem, "uint"), strings.HasPrefix(elem, "int"):
			renderWordGuard(b, currentLabel, wordIdx+i)
			b.WriteString(fmt.Sprintf("\t%s.SetBytes32(word)\n", target))
		case elem == "address":
			renderWordGuard(b, currentLabel, wordIdx+i)
			b.WriteString(fmt.Sprintf("\t%s = common.BytesToAddress(word[12:32])\n", target))
		case elem == "bytes32":
			renderWordGuard(b, currentLabel, wordIdx+i)
			b.WriteString(fmt.Sprintf("\t%s = common.BytesToHash(word)\n", target))
		case elem == "bool":
			renderWordGuard(b, currentLabel, wordIdx+i)
			b.WriteString(fmt.Sprintf("\tif %s, ok = abiunpack.Bool(word); !ok {\n", target))
			b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: invalid bool word\", %q)\n\t}\n", currentLabel))
		case isBytesN(elem):
			renderWordGuard(b, currentLabel, wordIdx+i)
			b.WriteString(fmt.Sprintf("\tcopy(%s[:], word[:%d])\n", target, bytesNSize(elem)))
		default:
			b.WriteString(fmt.Sprintf("\t// %s has unsupported fixed array ABI type %q.\n", arg.GoFieldName, arg.SolidityType))
			return
		}
	}
}

func renderWordGuard(b *bytes.Buffer, label string, wordIdx int) {
	b.WriteString(fmt.Sprintf("\tif word, ok = abiunpack.Word(data, %d); !ok {\n", wordIdx))
	b.WriteString(fmt.Sprintf("\t\treturn nil, fmt.Errorf(\"decode %%s: missing ABI word %d (data len %%d)\", %q, len(data))\n", wordIdx, label))
	b.WriteString("\t}\n")
}

func abiHeadWords(solType string) int {
	if _, ok := dynamicArrayElement(solType); ok {
		return 1
	}
	if _, _, ok := fixedArrayElement(solType); ok {
		_, length, _ := fixedArrayElement(solType)
		return length
	}
	return 1
}

func jsonExtractExpr(arg eventArg) string {
	if strings.Contains(arg.SolidityType, "[") || strings.HasPrefix(arg.SolidityType, "(") || strings.HasPrefix(arg.SolidityType, "tuple") {
		return fmt.Sprintf("JSONExtractRaw(params, %s)", quoteSQLString(arg.Name))
	}
	if arg.SolidityType == "bool" {
		return fmt.Sprintf("JSONExtractBool(params, %s)", quoteSQLString(arg.Name))
	}
	return fmt.Sprintf("JSONExtractString(params, %s)", quoteSQLString(arg.Name))
}

func goType(solType string) string {
	if elem, ok := dynamicArrayElement(solType); ok {
		return "[]" + goType(elem)
	}
	if elem, length, ok := fixedArrayElement(solType); ok {
		return fmt.Sprintf("[%d]%s", length, goType(elem))
	}
	switch {
	case solType == "bool":
		return "bool"
	case solType == "address":
		return "common.Address"
	case solType == "bytes32":
		return "common.Hash"
	case isBytesN(solType):
		return fmt.Sprintf("[%d]byte", bytesNSize(solType))
	case solType == "bytes":
		return "[]byte"
	case solType == "string":
		return "string"
	case strings.HasPrefix(solType, "uint"), strings.HasPrefix(solType, "int"):
		return "uint256.Int"
	default:
		return "string"
	}
}

func clickHouseType(solType string) string {
	if _, ok := dynamicArrayElement(solType); ok {
		return "String"
	}
	if _, _, ok := fixedArrayElement(solType); ok {
		return "String"
	}
	switch {
	case solType == "bool":
		return "UInt8"
	case solType == "address":
		return "FixedString(20)"
	case solType == "bytes32":
		return "FixedString(32)"
	case isBytesN(solType):
		return fmt.Sprintf("FixedString(%d)", bytesNSize(solType))
	case solType == "bytes", solType == "string":
		return "String"
	case strings.HasPrefix(solType, "uint"):
		return "UInt256"
	case strings.HasPrefix(solType, "int"):
		return "Int256"
	default:
		return "String"
	}
}

func normalizeSolidityType(typ string) string {
	switch typ {
	case "uint":
		return "uint256"
	case "int":
		return "int256"
	default:
		return typ
	}
}

func hasUint256Type(events []eventSpec) bool {
	for _, ev := range events {
		for _, arg := range ev.Args {
			if strings.Contains(arg.GoType, "uint256.Int") {
				return true
			}
		}
	}
	return false
}

func hasCommonType(events []eventSpec) bool {
	for _, ev := range events {
		for _, arg := range ev.Args {
			if strings.Contains(arg.GoType, "common.") {
				return true
			}
		}
	}
	return len(events) > 0
}

func hasERC20Transfer(events []eventSpec) bool {
	for _, ev := range events {
		if isERC20Transfer(ev) {
			return true
		}
	}
	return false
}

func isERC20Transfer(ev eventSpec) bool {
	return ev.CanonicalSig == "Transfer(address,address,uint256)" &&
		len(ev.Args) == 3 &&
		ev.Args[0].SolidityType == "address" &&
		ev.Args[1].SolidityType == "address" &&
		ev.Args[2].SolidityType == "uint256"
}

func dynamicArrayElement(solType string) (string, bool) {
	if strings.HasSuffix(solType, "[]") {
		return solType[:len(solType)-2], true
	}
	return "", false
}

func fixedArrayElement(solType string) (string, int, bool) {
	close := strings.LastIndex(solType, "]")
	open := strings.LastIndex(solType, "[")
	if open < 0 || close != len(solType)-1 || close <= open+1 {
		return "", 0, false
	}
	n, err := strconv.Atoi(solType[open+1 : close])
	if err != nil || n <= 0 {
		return "", 0, false
	}
	return solType[:open], n, true
}

func isBytesN(solType string) bool {
	if !strings.HasPrefix(solType, "bytes") || solType == "bytes" {
		return false
	}
	n := bytesNSize(solType)
	return n > 0 && n <= 32
}

func bytesNSize(solType string) int {
	n, _ := strconv.Atoi(strings.TrimPrefix(solType, "bytes"))
	return n
}

func addresses(addr any) []string {
	switch v := addr.(type) {
	case config.Address:
		out := make([]string, 0, len(v))
		for _, item := range v {
			if s := strings.TrimSpace(item); s != "" {
				out = append(out, s)
			}
		}
		return out
	case string:
		if strings.TrimSpace(v) == "" {
			return nil
		}
		return []string{v}
	case []any:
		out := make([]string, 0, len(v))
		for _, item := range v {
			if s, ok := item.(string); ok && strings.TrimSpace(s) != "" {
				out = append(out, s)
			}
		}
		return out
	case []string:
		return v
	default:
		return nil
	}
}

func uniqueLower(used map[string]int, base string) string {
	if base == "" {
		base = "event"
	}
	count := used[base]
	used[base] = count + 1
	if count == 0 {
		return base
	}
	return fmt.Sprintf("%s_%d", base, count+1)
}

func uniqueExported(used map[string]int, base string) string {
	if base == "" {
		base = "Generated"
	}
	count := used[base]
	used[base] = count + 1
	if count == 0 {
		return base
	}
	return fmt.Sprintf("%s%d", base, count+1)
}

func exportIdent(s string) string {
	parts := identifierParts(s)
	if len(parts) == 0 {
		return "Generated"
	}
	var b strings.Builder
	for _, part := range parts {
		if initialism, ok := commonInitialism(part); ok {
			b.WriteString(initialism)
			continue
		}
		runes := []rune(part)
		if len(runes) == 0 {
			continue
		}
		b.WriteRune(unicode.ToUpper(runes[0]))
		for _, r := range runes[1:] {
			b.WriteRune(r)
		}
	}
	out := b.String()
	if out == "" {
		return "Generated"
	}
	if r := []rune(out)[0]; unicode.IsDigit(r) {
		return "N" + out
	}
	return out
}

func commonInitialism(s string) (string, bool) {
	switch strings.ToUpper(s) {
	case "ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "UID", "URI", "URL", "UTF8", "UUID", "VM", "XML", "XMPP", "XSRF", "XSS":
		return strings.ToUpper(s), true
	default:
		return "", false
	}
}

func toSnake(s string) string {
	parts := identifierParts(s)
	if len(parts) == 0 {
		return "event"
	}
	for i := range parts {
		parts[i] = strings.ToLower(parts[i])
	}
	return strings.Join(parts, "_")
}

func identifierParts(s string) []string {
	var parts []string
	var b strings.Builder
	flush := func() {
		if b.Len() > 0 {
			parts = append(parts, b.String())
			b.Reset()
		}
	}
	var prevLower bool
	for _, r := range s {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if unicode.IsUpper(r) && prevLower {
				flush()
			}
			b.WriteRune(r)
			prevLower = unicode.IsLower(r) || unicode.IsDigit(r)
			continue
		}
		flush()
		prevLower = false
	}
	flush()
	return parts
}

func quoteSQLIdent(name string) string {
	return "`" + strings.ReplaceAll(name, "`", "``") + "`"
}

func quoteSQLString(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func strip0x(v string) string {
	return strings.TrimPrefix(strings.TrimPrefix(v, "0x"), "0X")
}

func generateSchemaGo(events []eventSpec) ([]byte, error) {
	src := template.MustExecute("code/schemaGo", struct {
		Events []eventSpec
	}{Events: events})
	return format.Source([]byte(src))
}

func stateEventToCustomTableSpec(ev *eventSpec, state config.StateConfig) customTableSpec {
	spec := customTableSpec{
		Name:       ev.TableName,
		GoTypeName: ev.GoTypeName,
		BaseName:   pluralizeGoName(exportIdent(state.Name)),
		IsEvent:    true,
	}

	var pkeys []string
	for _, k := range state.Key {
		for _, arg := range ev.Args {
			if strings.EqualFold(arg.ColumnName, k) || strings.EqualFold(arg.Name, k) || strings.EqualFold(arg.GoFieldName, k) {
				pkeys = append(pkeys, arg.ColumnName)
				break
			}
		}
	}
	spec.PrimaryKey = pkeys

	spec.Fields = append(spec.Fields, customFieldSpec{
		Name:       "BlockNumber",
		ColumnName: "block_number",
		Type:       "uint64",
		ColumnType: "UInt64",
	})
	spec.Fields = append(spec.Fields, customFieldSpec{
		Name:       "BlockTimestamp",
		ColumnName: "block_timestamp",
		Type:       "time.Time",
		ColumnType: "DateTime64(3, 'UTC')",
	})
	spec.Fields = append(spec.Fields, customFieldSpec{
		Name:       "TransactionIndex",
		ColumnName: "transaction_index",
		Type:       "uint64",
		ColumnType: "UInt64",
	})
	spec.Fields = append(spec.Fields, customFieldSpec{
		Name:       "LogIndex",
		ColumnName: "log_index",
		Type:       "uint64",
		ColumnType: "UInt64",
	})

	for _, arg := range ev.Args {
		spec.Fields = append(spec.Fields, customFieldSpec{
			Name:       arg.GoFieldName,
			ColumnName: arg.ColumnName,
			Type:       arg.GoType,
			ColumnType: arg.ClickHouseType,
		})
	}

	for _, f := range spec.Fields {
		spec.Columns = append(spec.Columns, customColumnSpec{
			Name: f.ColumnName,
			Type: f.ColumnType,
		})
	}
	return spec
}
