package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/franz101/sqd-go/internal/config"
)

// pruneIsBucketable reports whether a table's prune DELETE can be sharded into
// byte-prefix ranges over its leading primary-key column. Only string-typed
// columns support lexicographic byte ranges; the hot-state keys (addresses,
// bytes32 ids) are hash-derived FixedStrings, so the first byte distributes
// uniformly across buckets.
func pruneIsBucketable(tbl customTableSpec) bool {
	if len(tbl.PrimaryKey) == 0 {
		return false
	}
	field, ok := tbl.fieldByColumn(tbl.PrimaryKey[0])
	if !ok {
		return false
	}
	t := field.ColumnType
	return t == "String" || strings.HasPrefix(t, "FixedString(")
}

func generateCompactionGo(cfg *config.Config, tables []customTableSpec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)

	if len(tables) > 0 {
		b.WriteString(`import (
	"context"
	"fmt"
	"log"
	"sync/atomic"
	"time"

	"github.com/ClickHouse/ch-go"
)

// compactionPruneInFlight guards the background prune: at most one runs at a
// time. The processor is a single goroutine, so a plain CAS is enough.
var compactionPruneInFlight atomic.Bool

// compactionMaintenanceDialer is implemented by *database.Store. Stores that
// can hand out a dedicated connection get the prune in the background; plain
// Conn()/DB() stubs (tests) keep the synchronous path, because a shared
// ch.Client must never see concurrent Do calls.
type compactionMaintenanceDialer interface {
	DialMaintenanceConn(ctx context.Context) (*ch.Client, error)
}

// CompactionPruneStateAsync runs CompactionPruneState in the background on its
// own connection so the multi-second DELETE/OPTIMIZE pass never stalls block
// processing. If a previous prune is still running the call is a no-op (the
// next interval retries). Prune is an optimization, never a correctness
// requirement, so failures are logged and dropped.
func CompactionPruneStateAsync(ctx context.Context, store Store, blockNumber uint64) {
	dialer, ok := store.(compactionMaintenanceDialer)
	if !ok {
		if err := CompactionPruneState(ctx, store, blockNumber); err != nil {
			log.Printf("WARN: prune ClickHouse state at block %d failed: %v", blockNumber, err)
		}
		return
	}
	if !compactionPruneInFlight.CompareAndSwap(false, true) {
		return
	}
	db := store.DB()
	go func() {
		defer compactionPruneInFlight.Store(false)
		conn, err := dialer.DialMaintenanceConn(ctx)
		if err != nil {
			log.Printf("WARN: prune ClickHouse state at block %d failed (dial): %v", blockNumber, err)
			return
		}
		defer conn.Close()
		if err := compactionPruneStateOn(ctx, conn, db, blockNumber); err != nil {
			log.Printf("WARN: prune ClickHouse state at block %d failed: %v", blockNumber, err)
		}
	}()
}

// compactionBucketRanges splits a string-typed key column into 16 disjoint
// byte-prefix ranges (first byte 0x00-0x0f, 0x10-0x1f, ...). Each prune DELETE
// then aggregates only its slice of the table: the range predicate is a prefix
// of the primary key, so ClickHouse prunes granules on both the outer scan and
// the NOT IN subquery instead of hash-aggregating the whole table. On 1.26M
// rows this drops peak mutation memory from 1.3 GiB (unbatched 3-way argMax)
// to ~43 MiB per bucket. Keys that are not uniformly distributed over the
// first byte (e.g. ASCII hex with a constant prefix) degenerate to one
// non-empty bucket — still correct, just unbatched.
func compactionBucketRanges(col string) []string {
	out := make([]string, 0, 16)
	for i := 0; i < 16; i++ {
		switch i {
		case 0:
			out = append(out, fmt.Sprintf("%s < unhex('10')", col))
		case 15:
			out = append(out, fmt.Sprintf("%s >= unhex('f0')", col))
		default:
			out = append(out, fmt.Sprintf("%s >= unhex('%02x') AND %s < unhex('%02x')", col, i*16, col, (i+1)*16))
		}
	}
	return out
}

// CompactionPruneState removes superseded rows from hot-state tables. For each
// table with a primary key, it deletes rows whose block_number is below a
// rolling threshold (blockNumber - 1000) and that are not the latest version of
// their primary-key group. This keeps ClickHouse tables bounded during long
// backfill runs while preserving the most recent state for each entity.
//
// The "latest version" subquery compares one max((block_number,
// transaction_index, log_index)) tuple per group instead of three argMax
// states, and string-keyed tables are pruned in 16 byte-prefix buckets so no
// single mutation aggregates the whole table (see compactionBucketRanges).
func CompactionPruneState(ctx context.Context, store Store, blockNumber uint64) error {
	if store == nil || store.Conn() == nil {
		return nil
	}
	return compactionPruneStateOn(ctx, store.Conn(), store.DB(), blockNumber)
}

func compactionPruneStateOn(ctx context.Context, conn *ch.Client, db string, blockNumber uint64) error {
	if conn == nil {
		return nil
	}

	if blockNumber <= 1000 {
		return nil
	}
	pruneThreshold := blockNumber - 1000

	var queries []string
`)

		for _, tbl := range tables {
			if len(tbl.PrimaryKey) == 0 {
				continue
			}
			pkCols := strings.Join(tbl.PrimaryKey, ", ")
			if pruneIsBucketable(tbl) {
				b.WriteString(fmt.Sprintf(`	// %[1]s (pk: %[2]s; bucketed on %[3]s)
	for _, rng := range compactionBucketRanges("%[3]s") {
		queries = append(queries, fmt.Sprintf("DELETE FROM \x60%%[1]s\x60.\x60%[1]s\x60 WHERE %%[3]s AND block_number < %%[2]d AND (%[2]s, (block_number, transaction_index, log_index)) NOT IN (SELECT %[2]s, max((block_number, transaction_index, log_index)) FROM \x60%%[1]s\x60.\x60%[1]s\x60 WHERE %%[3]s GROUP BY %[2]s) SETTINGS lightweight_deletes_sync = 1", db, pruneThreshold, rng))
	}
	queries = append(queries, fmt.Sprintf("OPTIMIZE TABLE \x60%%s\x60.\x60%[1]s\x60 FINAL", db))

`, tbl.Name, pkCols, tbl.PrimaryKey[0]))
			} else {
				b.WriteString(fmt.Sprintf(`	// %[1]s (pk: %[2]s)
	queries = append(queries,
		fmt.Sprintf("DELETE FROM \x60%%[1]s\x60.\x60%[1]s\x60 WHERE block_number < %%[2]d AND (%[2]s, (block_number, transaction_index, log_index)) NOT IN (SELECT %[2]s, max((block_number, transaction_index, log_index)) FROM \x60%%[1]s\x60.\x60%[1]s\x60 GROUP BY %[2]s) SETTINGS lightweight_deletes_sync = 1", db, pruneThreshold),
		fmt.Sprintf("OPTIMIZE TABLE \x60%%s\x60.\x60%[1]s\x60 FINAL", db),
	)

`, tbl.Name, pkCols))
			}
		}

		b.WriteString(`	start := time.Now()
	for _, q := range queries {
		if err := conn.Do(ctx, ch.Query{Body: q}); err != nil {
			return fmt.Errorf("compaction prune error executing query: %w", err)
		}
	}
	log.Printf("[AUTOMATED COMPACTION] ClickHouse tables pruned and optimized in %s", time.Since(start).Round(time.Millisecond))
	return nil
}
`)
	} else {
		b.WriteString(`import "context"

func CompactionPruneState(ctx context.Context, store Store, blockNumber uint64) error {
	return nil
}

func CompactionPruneStateAsync(ctx context.Context, store Store, blockNumber uint64) {}
`)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format compaction source: %w", err)
	}
	return formatted, nil
}
