package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"

	"github.com/franz101/sqd-go/internal/config"
)

func generateCompactionGo(cfg *config.Config, tables []customTableSpec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)

	if len(tables) > 0 {
		b.WriteString(`import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/ClickHouse/ch-go"
)

// CompactionPruneState removes superseded rows from hot-state tables. For each
// table with a primary key, it deletes rows whose block_number is below a
// rolling threshold (blockNumber - 1000) and that are not the latest version of
// their primary-key group. This keeps ClickHouse tables bounded during long
// backfill runs while preserving the most recent state for each entity.
func CompactionPruneState(ctx context.Context, store Store, blockNumber uint64) error {
	if store == nil || store.Conn() == nil {
		return nil
	}
	db := store.DB()

	if blockNumber <= 1000 {
		return nil
	}
	pruneThreshold := blockNumber - 1000

	queries := []string{
`)

		for _, tbl := range tables {
			if len(tbl.PrimaryKey) == 0 {
				continue
			}
			pkCols := strings.Join(tbl.PrimaryKey, ", ")
			b.WriteString(fmt.Sprintf(`		// %[1]s (pk: %[2]s)
		fmt.Sprintf("DELETE FROM \x60%%[1]s\x60.\x60%[1]s\x60 WHERE block_number < %%[2]d AND (%[2]s, block_number, transaction_index, log_index) NOT IN (SELECT %[2]s, argMax(block_number, (block_number, transaction_index, log_index)), argMax(transaction_index, (block_number, transaction_index, log_index)), argMax(log_index, (block_number, transaction_index, log_index)) FROM \x60%%[1]s\x60.\x60%[1]s\x60 GROUP BY %[2]s) SETTINGS lightweight_deletes_sync = 1", db, pruneThreshold),
		fmt.Sprintf("OPTIMIZE TABLE \x60%%s\x60.\x60%[1]s\x60 FINAL", db),

`, tbl.Name, pkCols))
		}

		b.WriteString(`	}

	start := time.Now()
	for _, q := range queries {
		if err := store.Conn().Do(ctx, ch.Query{Body: q}); err != nil {
			return fmt.Errorf("compaction prune error executing query: %w", err)
		}
	}
	log.Printf("[AUTOMATED COMPACTION] ClickHouse tables pruned and optimized in %s", time.Since(start).Round(time.Millisecond))
	return nil
}
`)
	} else {
		b.WriteString(`import "context"

func CompactionPruneState(ctx context.Context, store Store, blockNumber uint64) error {
	return nil
}
`)
	}

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format compaction source: %w", err)
	}
	return formatted, nil
}
