package codegen

import (
	"bytes"
	"go/format"
	"strconv"
)

func generateCustomProcessorGo(events []eventSpec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

import (
	"context"
	"fmt"
	"math/big"
	"sync"

	"github.com/ClickHouse/ch-go"
	"github.com/ClickHouse/ch-go/proto"
	"github.com/ethereum/go-ethereum/common"
	"github.com/holiman/uint256"
)

type Entities struct {
`)
	for _, ev := range events {
		b.WriteString("\t")
		b.WriteString(ev.GoTypeName)
		b.WriteString(" []")
		b.WriteString(ev.GoTypeName)
		b.WriteString("\n")
	}
	b.WriteString(`	BlockNumber uint64
}

func AppendDecodedLog(entities *Entities, decoded *DecodedLog, meta EventMeta) bool {
	if entities == nil || decoded == nil || decoded.Value == nil {
		return false
	}
	switch ev := decoded.Value.(type) {
`)
	for _, ev := range events {
		b.WriteString("\tcase *")
		b.WriteString(ev.GoTypeName)
		b.WriteString(":\n")
		b.WriteString("\t\tev.EventMeta = meta\n")
		b.WriteString("\t\tentities.")
		b.WriteString(ev.GoTypeName)
		b.WriteString(" = append(entities.")
		b.WriteString(ev.GoTypeName)
		b.WriteString(", *ev)\n")
	}
	b.WriteString(`	default:
		return false
	}
	if meta.BlockNumber > entities.BlockNumber {
		entities.BlockNumber = meta.BlockNumber
	}
	return true
}

type Store interface {
	Conn() *ch.Client
	DB() string
}

type AddressPosition struct {
	Address        common.Address
	Balance        big.Int
	TotalIn        uint256.Int
	TotalOut       uint256.Int
	NetFlow        big.Int
	RealizedPnL    big.Int
	TransferCount  uint64
	UpdatedAtBlock uint64
}

type MemoryState struct {
	AddressPositions map[common.Address]*AddressPosition
	mu               sync.RWMutex
	LastSyncBlock    uint64
}

func NewMemoryState() *MemoryState {
	return &MemoryState{AddressPositions: make(map[common.Address]*AddressPosition)}
}

var GlobalState = NewMemoryState()

func CustomProcessing(ctx context.Context, store Store, entities *Entities) error {
	if entities == nil {
		return nil
	}
	s := GlobalState
`)
	for _, ev := range events {
		if !isERC20Transfer(ev) {
			continue
		}
		fromField := ev.Args[0].GoFieldName
		toField := ev.Args[1].GoFieldName
		valueField := ev.Args[2].GoFieldName
		b.WriteString("\tfor _, ev := range entities.")
		b.WriteString(ev.GoTypeName)
		b.WriteString(" {\n")
		b.WriteString("\t\ts.ApplyTransfer(ev.")
		b.WriteString(fromField)
		b.WriteString(", ev.")
		b.WriteString(toField)
		b.WriteString(", &ev.")
		b.WriteString(valueField)
		b.WriteString(", ev.BlockNumber)\n\t}\n")
	}
	b.WriteString(`	if entities.BlockNumber > 0 {
		if err := s.SyncToClickHouse(ctx, store, entities.BlockNumber); err != nil {
			return err
		}
		s.LastSyncBlock = entities.BlockNumber
	}
	return nil
}

func (s *MemoryState) ApplyTransfer(from, to common.Address, value *uint256.Int, blockNumber uint64) {
	if value == nil {
		return
	}
	zero := common.Address{}
	amount := value.ToBig()
	s.mu.Lock()
	defer s.mu.Unlock()
	if from != zero {
		pos := s.positionLocked(from)
		pos.Balance.Sub(&pos.Balance, amount)
		pos.NetFlow.Set(&pos.Balance)
		pos.TotalOut.Add(&pos.TotalOut, value)
		pos.TransferCount++
		pos.UpdatedAtBlock = blockNumber
	}
	if to != zero {
		pos := s.positionLocked(to)
		pos.Balance.Add(&pos.Balance, amount)
		pos.NetFlow.Set(&pos.Balance)
		pos.TotalIn.Add(&pos.TotalIn, value)
		pos.TransferCount++
		pos.UpdatedAtBlock = blockNumber
	}
}

func (s *MemoryState) Position(address common.Address) (AddressPosition, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	pos, ok := s.AddressPositions[address]
	if !ok {
		return AddressPosition{Address: address}, false
	}
	return copyPosition(pos), true
}

func (s *MemoryState) positionLocked(address common.Address) *AddressPosition {
	pos := s.AddressPositions[address]
	if pos == nil {
		pos = &AddressPosition{Address: address}
		s.AddressPositions[address] = pos
	}
	return pos
}

func copyPosition(pos *AddressPosition) AddressPosition {
	out := AddressPosition{
		Address:        pos.Address,
		TransferCount:  pos.TransferCount,
		UpdatedAtBlock: pos.UpdatedAtBlock,
	}
	out.Balance.Set(&pos.Balance)
	out.TotalIn.Set(&pos.TotalIn)
	out.TotalOut.Set(&pos.TotalOut)
	out.NetFlow.Set(&pos.NetFlow)
	out.RealizedPnL.Set(&pos.RealizedPnL)
	return out
}

func (s *MemoryState) SyncToClickHouse(ctx context.Context, store Store, blockNumber uint64) error {
	if store == nil || store.Conn() == nil || len(s.AddressPositions) == 0 {
		return nil
	}
	s.mu.RLock()
	positions := make([]AddressPosition, 0, len(s.AddressPositions))
	for _, pos := range s.AddressPositions {
		positions = append(positions, copyPosition(pos))
	}
	s.mu.RUnlock()

	var (
		colAddress        proto.ColFixedStr
		colBalance        proto.ColStr
		colTotalIn        proto.ColStr
		colTotalOut       proto.ColStr
		colNetFlow        proto.ColStr
		colRealizedPnL    proto.ColStr
		colTransferCount  proto.ColUInt64
		colUpdatedAtBlock proto.ColUInt64
	)
	colAddress.SetSize(20)
	for _, pos := range positions {
		colAddress.Append(pos.Address.Bytes())
		colBalance.Append(pos.Balance.String())
		colTotalIn.Append(pos.TotalIn.Dec())
		colTotalOut.Append(pos.TotalOut.Dec())
		colNetFlow.Append(pos.NetFlow.String())
		colRealizedPnL.Append(pos.RealizedPnL.String())
		colTransferCount.Append(pos.TransferCount)
		colUpdatedAtBlock.Append(blockNumber)
	}
	return store.Conn().Do(ctx, ch.Query{
		Body: fmt.Sprintf("INSERT INTO %s.erc20_address_positions (address, balance_raw, total_in_raw, total_out_raw, net_flow_raw, realized_pnl_raw, transfer_count, updated_at_block) VALUES", quoteIdent(store.DB())),
		Input: []proto.InputColumn{
			{Name: "address", Data: &colAddress},
			{Name: "balance_raw", Data: &colBalance},
			{Name: "total_in_raw", Data: &colTotalIn},
			{Name: "total_out_raw", Data: &colTotalOut},
			{Name: "net_flow_raw", Data: &colNetFlow},
			{Name: "realized_pnl_raw", Data: &colRealizedPnL},
			{Name: "transfer_count", Data: &colTransferCount},
			{Name: "updated_at_block", Data: &colUpdatedAtBlock},
		},
	})
}

func PositionSummary(address common.Address) string {
	pos, ok := GlobalState.Position(address)
	if !ok {
		return fmt.Sprintf("%s position not found", address.Hex())
	}
	return fmt.Sprintf("%s balance=%s total_in=%s total_out=%s net_flow=%s realized_pnl=%s transfers=%d updated_at_block=%d",
		address.Hex(),
		pos.Balance.String(),
		pos.TotalIn.Dec(),
		pos.TotalOut.Dec(),
		pos.NetFlow.String(),
		pos.RealizedPnL.String(),
		pos.TransferCount,
		pos.UpdatedAtBlock,
	)
}

func _customProcessorEventCount() int {
	return `)
	b.WriteString(strconv.Itoa(len(events)))
	b.WriteString(`
}
`)
	return format.Source(b.Bytes())
}
