package codegen

import (
	"bytes"
	"go/format"
	"strconv"

	"github.com/franz101/sqd-go/internal/config"
)

func generateCustomProcessorGo(events []eventSpec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

import (
	"context"
	"fmt"
	"math/big"
	"sync"

	"github.com/ClickHouse/ch-go"
	"github.com/ClickHouse/ch-go/proto"
	"github.com/ethereum/go-ethereum/common"
	"github.com/holiman/uint256"
)

type AddressPosition struct {
	Address        common.Address
	Balance        big.Int
	TotalIn        uint256.Int
	TotalOut       uint256.Int
	NetFlow        big.Int
	RealizedPnL    big.Int
	TransferCount  uint64
	UpdatedAtBlock uint64
}

type MemoryState struct {
	AddressPositions map[common.Address]*AddressPosition
	mu               sync.RWMutex
	LastSyncBlock    uint64
}

func NewMemoryState() *MemoryState {
	return &MemoryState{AddressPositions: make(map[common.Address]*AddressPosition)}
}

var GlobalState = NewMemoryState()

func CustomProcessing(ctx context.Context, store Store, entities *Entities) error {
	if entities == nil {
		return nil
	}
	s := GlobalState
`)
	for _, ev := range events {
		if !isERC20Transfer(ev) {
			continue
		}
		fromField := ev.Args[0].GoFieldName
		toField := ev.Args[1].GoFieldName
		valueField := ev.Args[2].GoFieldName
		b.WriteString("\tfor _, ev := range entities.")
		b.WriteString(ev.GoTypeName)
		b.WriteString(" {\n")
		b.WriteString("\t\ts.ApplyTransfer(ev.")
		b.WriteString(fromField)
		b.WriteString(", ev.")
		b.WriteString(toField)
		b.WriteString(", &ev.")
		b.WriteString(valueField)
		b.WriteString(", ev.BlockNumber)\n\t}\n")
	}
	b.WriteString(`	if entities.BlockNumber > 0 {
		if err := s.SyncToClickHouse(ctx, store, entities.BlockNumber); err != nil {
			return err
		}
		s.LastSyncBlock = entities.BlockNumber
	}
	return nil
}

func (s *MemoryState) ApplyTransfer(from, to common.Address, value *uint256.Int, blockNumber uint64) {
	if value == nil {
		return
	}
	zero := common.Address{}
	amount := value.ToBig()
	s.mu.Lock()
	defer s.mu.Unlock()
	if from != zero {
		pos := s.positionLocked(from)
		pos.Balance.Sub(&pos.Balance, amount)
		pos.NetFlow.Set(&pos.Balance)
		pos.TotalOut.Add(&pos.TotalOut, value)
		pos.TransferCount++
		pos.UpdatedAtBlock = blockNumber
	}
	if to != zero {
		pos := s.positionLocked(to)
		pos.Balance.Add(&pos.Balance, amount)
		pos.NetFlow.Set(&pos.Balance)
		pos.TotalIn.Add(&pos.TotalIn, value)
		pos.TransferCount++
		pos.UpdatedAtBlock = blockNumber
	}
}

func (s *MemoryState) Position(address common.Address) (AddressPosition, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	pos, ok := s.AddressPositions[address]
	if !ok {
		return AddressPosition{Address: address}, false
	}
	return copyPosition(pos), true
}

func (s *MemoryState) positionLocked(address common.Address) *AddressPosition {
	pos := s.AddressPositions[address]
	if pos == nil {
		pos = &AddressPosition{Address: address}
		s.AddressPositions[address] = pos
	}
	return pos
}

func copyPosition(pos *AddressPosition) AddressPosition {
	out := AddressPosition{
		Address:        pos.Address,
		TransferCount:  pos.TransferCount,
		UpdatedAtBlock: pos.UpdatedAtBlock,
	}
	out.Balance.Set(&pos.Balance)
	out.TotalIn.Set(&pos.TotalIn)
	out.TotalOut.Set(&pos.TotalOut)
	out.NetFlow.Set(&pos.NetFlow)
	out.RealizedPnL.Set(&pos.RealizedPnL)
	return out
}

func (s *MemoryState) SyncToClickHouse(ctx context.Context, store Store, blockNumber uint64) error {
	if store == nil || store.Conn() == nil || len(s.AddressPositions) == 0 {
		return nil
	}
	s.mu.RLock()
	positions := make([]AddressPosition, 0, len(s.AddressPositions))
	for _, pos := range s.AddressPositions {
		positions = append(positions, copyPosition(pos))
	}
	s.mu.RUnlock()

	var (
		colAddress        proto.ColFixedStr
		colBalance        proto.ColStr
		colTotalIn        proto.ColStr
		colTotalOut       proto.ColStr
		colNetFlow        proto.ColStr
		colRealizedPnL    proto.ColStr
		colTransferCount  proto.ColUInt64
		colUpdatedAtBlock proto.ColUInt64
	)
	colAddress.SetSize(20)
	for _, pos := range positions {
		colAddress.Append(pos.Address.Bytes())
		colBalance.Append(pos.Balance.String())
		colTotalIn.Append(pos.TotalIn.Dec())
		colTotalOut.Append(pos.TotalOut.Dec())
		colNetFlow.Append(pos.NetFlow.String())
		colRealizedPnL.Append(pos.RealizedPnL.String())
		colTransferCount.Append(pos.TransferCount)
		colUpdatedAtBlock.Append(blockNumber)
	}
	return store.Conn().Do(ctx, ch.Query{
		Body: fmt.Sprintf("INSERT INTO %s.erc20_address_positions (address, balance_raw, total_in_raw, total_out_raw, net_flow_raw, realized_pnl_raw, transfer_count, updated_at_block) VALUES", quoteIdent(store.DB())),
		Input: []proto.InputColumn{
			{Name: "address", Data: &colAddress},
			{Name: "balance_raw", Data: &colBalance},
			{Name: "total_in_raw", Data: &colTotalIn},
			{Name: "total_out_raw", Data: &colTotalOut},
			{Name: "net_flow_raw", Data: &colNetFlow},
			{Name: "realized_pnl_raw", Data: &colRealizedPnL},
			{Name: "transfer_count", Data: &colTransferCount},
			{Name: "updated_at_block", Data: &colUpdatedAtBlock},
		},
	})
}

func PositionSummary(address common.Address) string {
	pos, ok := GlobalState.Position(address)
	if !ok {
		return fmt.Sprintf("%s position not found", address.Hex())
	}
	return fmt.Sprintf("%s balance=%s total_in=%s total_out=%s net_flow=%s realized_pnl=%s transfers=%d updated_at_block=%d",
		address.Hex(),
		pos.Balance.String(),
		pos.TotalIn.Dec(),
		pos.TotalOut.Dec(),
		pos.NetFlow.String(),
		pos.RealizedPnL.String(),
		pos.TransferCount,
		pos.UpdatedAtBlock,
	)
}

func _customProcessorEventCount() int {
	return `)
	b.WriteString(strconv.Itoa(len(events)))
	b.WriteString(`
}
`)
	return format.Source(b.Bytes())
}

func generateEmptyCustomProcessorGo(cfg *config.Config, events []eventSpec, hotStateTables []customTableSpec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)

	if len(hotStateTables) == 0 {
		b.WriteString(`import (
	"context"
)

// CustomProcessing is called during block processing to run custom business logic.
// You have access to the db store, and the entities containing decoded event logs.
func CustomProcessing(ctx context.Context, store Store, entities *Entities) error {
	if entities == nil {
		return nil
	}
	return nil
}
`)
		return format.Source(b.Bytes())
	}

	b.WriteString(`import (
	"context"
	"fmt"
	"os"
	"strconv"
	"sync"
	"time"

	"github.com/ethereum/go-ethereum/common"
	"github.com/franz101/sqd-go/internal/database"
	"github.com/franz101/sqd-go/internal/ingestion"
)

// CustomProcessFn is the callback registered by the custom processor.
var CustomProcessFn func(state *State, block *ParsedBlock) error

// CustomProcessProtoFn is the proto callback registered by the custom processor.
var CustomProcessProtoFn func(state *State, block *ProtoEventBlock) error

// CustomProcessing wraps the block-based processing
func CustomProcessing(ctx context.Context, store Store, state *State, block *ParsedBlock) error {
	if state == nil || block == nil {
		return nil
	}
	state.Store = store
	// Prefetch intentionally disabled: hot-state misses are resolved lazily
	// (GetUserPosition/GetCondition/...) from durable ClickHouse state.

	// Process block
	if CustomProcessFn != nil {
		if err := CustomProcessFn(state, block); err != nil {
			return err
		}
	}

	return commitCustomProcessing(ctx, store, state, block.BlockNumber)
}

// CustomProcessingProto wraps proto block-based processing.
func CustomProcessingProto(ctx context.Context, store Store, state *State, block *ProtoEventBlock) error {
	if state == nil || block == nil {
		return nil
	}
	state.Store = store
	// Prefetch intentionally disabled: hot-state misses are resolved lazily.

	if CustomProcessProtoFn != nil {
		if err := CustomProcessProtoFn(state, block); err != nil {
			return err
		}
	}

	return commitCustomProcessing(ctx, store, state, protoBlockNumber(block))
}

func commitCustomProcessing(ctx context.Context, store Store, state *State, blockNumber uint64) error {
	// Hybrid commit cadence. Commit when EITHER bound is hit, whichever first:
	//   - maxBlocks (SQD_COMMIT_INTERVAL, default 5000): the crash re-fetch budget.
	//     Bounds how many blocks a crash must re-fetch+re-process from the durable
	//     checkpoint. Dominates during fast backfill.
	//   - maxInterval (SQD_COMMIT_MAX_INTERVAL, default 3s): the durability-latency
	//     bound. Ensures the live tail (few blocks/sec) still becomes durable
	//     promptly instead of waiting maxBlocks (which could be ~30 min of wall
	//     clock). Dominates at the head.
	// This replaces the single magic block interval: the checkpoint never leads the
	// durable horizon, and the gap is bounded in both blocks and wall-clock time.
	maxBlocks := uint64(5000)
	if envVal := os.Getenv("SQD_COMMIT_INTERVAL"); envVal != "" {
		if parsed, err := strconv.ParseUint(envVal, 10, 64); err == nil && parsed > 0 {
			maxBlocks = parsed
		}
	}
	maxInterval := 3 * time.Second
	if envVal := os.Getenv("SQD_COMMIT_MAX_INTERVAL"); envVal != "" {
		if parsed, err := time.ParseDuration(envVal); err == nil && parsed > 0 {
			maxInterval = parsed
		}
	}

	nowNanos := time.Now().UnixNano()
	if state.lastCommitWallNanos == 0 {
		state.lastCommitWallNanos = nowNanos
	}
	blocksElapsed := blockNumber >= state.LastSyncBlock+maxBlocks
	timeElapsed := time.Duration(nowNanos-state.lastCommitWallNanos) >= maxInterval
	if blocksElapsed || timeElapsed {
		state.lastCommitWallNanos = nowNanos
		state.SaveSnapshot(blockNumber)
		if err := state.Commit(ctx, store); err != nil {
			return err
		}

		pruneInterval := uint64(100000)
		if envVal := os.Getenv("CLICKHOUSE_PRUNE_INTERVAL"); envVal != "" {
			parsed, err := strconv.ParseUint(envVal, 10, 64)
			if err != nil {
				return fmt.Errorf("invalid CLICKHOUSE_PRUNE_INTERVAL %q: %w", envVal, err)
			}
			pruneInterval = parsed
		}
		if blockNumber >= state.LastPruneBlock+pruneInterval {
			if err := CompactionPruneState(ctx, store, blockNumber); err != nil {
				return fmt.Errorf("prune ClickHouse state at block %d: %w", blockNumber, err)
			}
			state.LastPruneBlock = blockNumber
		}

		state.LastSyncBlock = blockNumber
	}
	return nil
}

func protoBlockNumber(block *ProtoEventBlock) uint64 {
	if block == nil {
		return 0
	}
	if block.HeaderBlockNumber != 0 {
		return block.HeaderBlockNumber
	}
	if block.BlockNumber.Rows() > 0 {
		return block.BlockNumber[0]
	}
	return 0
}

const defaultRingBufferSize uint32 = 8192

type Processor struct {
	ring      *OrderedHistoricRingBuffer
	protoRing *ProtoRingBuffer
	State     *State
	ProtoMode bool
}

func NewProcessor(protoMode bool) (*Processor, error) {
	var ring *OrderedHistoricRingBuffer
	var protoRing *ProtoRingBuffer
	var err error
	if protoMode {
		protoRing, err = NewProtoRingBuffer(defaultRingBufferSize)
		if err != nil {
			return nil, err
		}
	} else {
		ring, err = NewOrderedHistoricRingBuffer(defaultRingBufferSize)
		if err != nil {
			return nil, err
		}
	}
	return &Processor{
		ring:      ring,
		protoRing: protoRing,
		State:     NewState(),
		ProtoMode: protoMode,
	}, nil
}

func (p *Processor) Process(ctx context.Context, store *database.Store, logs []ingestion.CustomLog) error {
	if p == nil || len(logs) == 0 {
		return nil
	}
	// DEBUG: Log processor state
	logProcessorStateOnce.Do(func() {
		fmt.Printf("[PROCESSOR DEBUG] p.ProtoMode=%v, p.protoRing=%v, p.ring=%v\n", p.ProtoMode, p.protoRing != nil, p.ring != nil)
	})
	if p.ProtoMode {
		if p.protoRing == nil {
			ring, err := NewProtoRingBuffer(defaultRingBufferSize)
			if err != nil {
				return err
			}
			p.protoRing = ring
		}
	} else if p.ring == nil {
		ring, err := NewOrderedHistoricRingBuffer(defaultRingBufferSize)
		if err != nil {
			return err
		}
		p.ring = ring
	}
	if p.State == nil {
		p.State = NewState()
	}
	var stateStore Store
	if store != nil {
		stateStore = store
	}
	p.State.Store = stateStore

	type blockGroup struct {
		blockNum  uint64
		blockHash string
		logs      []DecodedLog
	}

	if p.ProtoMode {
		var curProtoBlock *ProtoEventBlock
		var curBlockNum uint64

		for _, lg := range logs {
			if curProtoBlock == nil || curBlockNum != lg.BlockNumber {
				if curProtoBlock != nil {
					if err := p.processProtoBlocks(ctx, stateStore, []*ProtoEventBlock{curProtoBlock}); err != nil {
						return err
					}
				}
				curBlockNum = lg.BlockNumber
				curProtoBlock = p.protoRing.NextProtoSlot(curBlockNum, lg.BlockHash)
			}
			meta := EventMeta{
				BlockNumber:      lg.BlockNumber,
				BlockTimestamp:   lg.BlockTimestamp,
				BlockHash:        common.HexToHash(lg.BlockHash),
				ContractAddress:  common.HexToAddress(lg.ContractAddress),
				TransactionHash:  common.HexToHash(lg.TransactionHash),
				TransactionIndex: lg.TransactionIndex,
				LogIndex:         lg.LogIndex,
			}
			topics := make([]common.Hash, len(lg.Topics))
			for i, t := range lg.Topics {
				topics[i] = common.HexToHash(t)
			}
			curProtoBlock.AppendFromLog(meta.ContractAddress, topics, common.FromHex(lg.Data), meta)
		}
		if curProtoBlock != nil {
			return p.processProtoBlocks(ctx, stateStore, []*ProtoEventBlock{curProtoBlock})
		}
		return nil
	}

	processGroup := func(group blockGroup) error {
		if len(group.logs) == 0 {
			return nil
		}
		p.ring.Push(group.blockNum, group.blockHash, group.logs)
		block, ok := p.ring.GetParsedBlock(group.blockNum)
		if !ok {
			return fmt.Errorf("block for block %d not found after push", group.blockNum)
		}
		if err := CustomProcessing(ctx, stateStore, p.State, block); err != nil {
			return fmt.Errorf("custom processing block %d failed: %w", block.BlockNumber, err)
		}
		return nil
	}

	var curGroup blockGroup
	var hasGroup bool
	for _, lg := range logs {
		if hasGroup && curGroup.blockNum != lg.BlockNumber {
			if err := processGroup(curGroup); err != nil {
				return err
			}
			curGroup = blockGroup{}
			hasGroup = false
		}

		meta := EventMeta{
			BlockNumber:      lg.BlockNumber,
			BlockTimestamp:   lg.BlockTimestamp,
			BlockHash:        common.HexToHash(lg.BlockHash),
			ContractAddress:  common.HexToAddress(lg.ContractAddress),
			TransactionHash:  common.HexToHash(lg.TransactionHash),
			TransactionIndex: lg.TransactionIndex,
			LogIndex:         lg.LogIndex,
		}
		decoded, err := UnpackLogWithMeta(lg.ContractAddress, lg.Topics, common.FromHex(lg.Data), meta)
		if err != nil {
			return fmt.Errorf("unpack log block=%d tx=%s log=%d: %w", lg.BlockNumber, lg.TransactionHash, lg.LogIndex, err)
		}
		if decoded == nil || decoded.Value == nil {
			continue
		}

		if !hasGroup {
			curGroup = blockGroup{blockNum: lg.BlockNumber, blockHash: lg.BlockHash}
			hasGroup = true
		}
		curGroup.logs = append(curGroup.logs, *decoded)
	}
	if hasGroup {
		if err := processGroup(curGroup); err != nil {
			return err
		}
	}

	return nil
}

var (
	logProtoModeOnce      sync.Once
	logCustomFnOnce       sync.Once
	logProcessorStateOnce sync.Once
)

// processProtoBlocks handles proto mode processing.
func (p *Processor) processProtoBlocks(ctx context.Context, store Store, blocks []*ProtoEventBlock) error {
	// DEBUG: Log that we're in proto mode
	logProtoModeOnce.Do(func() {
		fmt.Println("[PROTO MODE] processProtoBlocks called with", len(blocks), "blocks")
	})
	if len(blocks) == 0 {
		return nil
	}
	if CustomProcessProtoFn == nil {
		logCustomFnOnce.Do(func() {
			fmt.Println("[PROTO MODE] CustomProcessProtoFn is nil, skipping custom proto processing")
		})
		return nil
	}
	for _, protoBlock := range blocks {
		if err := CustomProcessingProto(ctx, store, p.State, protoBlock); err != nil {
			return fmt.Errorf("custom proto processing block %d failed: %w", protoBlockNumber(protoBlock), err)
		}
	}
	return nil
}

func (p *Processor) RestoreToBlock(blockNumber uint64) (uint64, error) {
	if p == nil {
		return 0, nil
	}
	if p.ring != nil {
		p.ring.Reset()
	}
	if p.protoRing != nil {
		p.protoRing.Reset()
	}
	if p.State == nil {
		return blockNumber, nil
	}
	return p.State.RestoreToBlock(blockNumber)
}


func (p *Processor) LoadFromDatabase(blockNumber uint64) error {
	if p == nil {
		return nil
	}
	if p.ring != nil {
		p.ring.Reset()
	}
	if p.protoRing != nil {
		p.protoRing.Reset()
	}
	if p.State == nil {
		p.State = NewState()
	}

	if err := p.State.LoadFromClickHouse(context.Background(), blockNumber); err != nil {
		return fmt.Errorf("failed to load state from ClickHouse: %w", err)
	}

	p.State.LastSyncBlock = blockNumber
	p.State.SaveSnapshot(blockNumber)
	return nil
}

// CommittedBlock returns the highest block whose hot state has been durably
// committed to ClickHouse (wait_for_async_insert=1). The ingestion checkpoint
// must never lead this horizon, so a crash resumes from durable state and
// re-fetches the (cheap) gap rather than losing un-committed updates.
func (p *Processor) CommittedBlock() uint64 {
	if p == nil || p.State == nil {
		return 0
	}
	return p.State.LastSyncBlock
}

// Flush forces a durable commit of all hot state processed up to blockNumber and
// advances the committed horizon. Called on clean completion / shutdown so the
// tail (the < commit-cadence blocks since the last periodic commit) is persisted
// and the checkpoint can advance to it. Returns the new committed horizon.
func (p *Processor) Flush(ctx context.Context, store *database.Store, blockNumber uint64) (uint64, error) {
	if p == nil || p.State == nil {
		return 0, nil
	}
	if store != nil {
		if err := p.State.Commit(ctx, store); err != nil {
			return p.State.LastSyncBlock, err
		}
	}
	if blockNumber > p.State.LastSyncBlock {
		p.State.LastSyncBlock = blockNumber
	}
	p.State.lastCommitWallNanos = time.Now().UnixNano()
	return p.State.LastSyncBlock, nil
}

// SetSnapshotsEnabled toggles in-memory fork-recovery snapshots. Disabled during
// finalized backfill (no reorgs) to remove the dominant GC/memory cost.
func (p *Processor) SetSnapshotsEnabled(enabled bool) {
	if p == nil || p.State == nil {
		return
	}
	p.State.SetSnapshotsEnabled(enabled)
}

// EnableColdCache attaches the Pebble cold tier to the hot caches (pointer-free
// entities). authoritative=true (from-genesis, empty ClickHouse) lets a hot+cold
// miss skip the ClickHouse point-SELECT. No-op if state is nil.
func (p *Processor) EnableColdCache(dir string, authoritative bool) error {
	if p == nil || p.State == nil || p.State.HotState == nil {
		return nil
	}
	return p.State.HotState.EnableColdCache(dir, authoritative, 0, 0)
}

// CloseColdCache releases the cold tier (and its off-heap Pebble buffers). Called
// by the ingestion layer on exit.
func (p *Processor) CloseColdCache() error {
	if p == nil || p.State == nil || p.State.HotState == nil {
		return nil
	}
	return p.State.HotState.CloseColdCache()
}

func prefetchBlockState(ctx context.Context, store Store, state *State, block *ParsedBlock) error {
	return prefetchBlocksState(ctx, store, state, []*ParsedBlock{block})
}

func prefetchProtoBlockState(ctx context.Context, store Store, state *State, block *ProtoEventBlock) error {
	return prefetchProtoBlocksState(ctx, store, state, []*ProtoEventBlock{block})
}

`)

	renderGenericPrefetchBlocksState(&b, cfg, events, hotStateTables)
	renderGenericPrefetchProtoBlocksState(&b, cfg, events, hotStateTables)
	b.WriteString(`func PrintPnLSummary(state *State, blockNumber uint64) {}
`)

	return format.Source(b.Bytes())
}

type statePrefetchPlan struct {
	stateName string
	baseName  string
	keyType   string
	keyFields []customFieldSpec
	sources   []statePrefetchSource
}

type statePrefetchSource struct {
	slotField string
	eventType string
	fields    []statePrefetchField
}

type statePrefetchField struct {
	keyField   string
	eventField string
}

func renderGenericPrefetchBlocksState(b *bytes.Buffer, cfg *config.Config, events []eventSpec, hotStateTables []customTableSpec) {
	plans := buildStatePrefetchPlans(cfg, events, hotStateSpecs(hotStateTables))
	if len(plans) == 0 {
		b.WriteString(`func prefetchBlocksState(ctx context.Context, store Store, state *State, blocks []*ParsedBlock) error {
	return nil
}
`)
		return
	}

	b.WriteString(`func prefetchBlocksState(ctx context.Context, store Store, state *State, blocks []*ParsedBlock) error {
	if state == nil || state.HotState == nil || len(blocks) == 0 {
		return nil
	}
	// Safe nil check: store may be a non-nil interface wrapping a nil *database.Store.
	// store.Conn() panics on nil receiver, so check the concrete value first.
	if store == nil {
		return nil
	}
	if store.Conn() == nil {
		return nil
	}
	hot := state.HotState

	for _, block := range blocks {
		if block == nil {
			continue
		}
		// Custom prefetch for Position on OrderFilled events
		for _, ev := range block.ExchangeOrderFilleds {
			var tokenID common.Hash
			if ev.MakerAssetID.IsZero() {
				ev.TakerAssetID.WriteToSlice(tokenID[:])
			} else {
				ev.MakerAssetID.WriteToSlice(tokenID[:])
			}
			hot.UserPositionsResolver.Queue(UserPositionsClockKey{User: ev.Maker, TokenID: tokenID})
		}
		for _, ev := range block.NegRiskExchangeOrderFilleds {
			var tokenID common.Hash
			if ev.MakerAssetID.IsZero() {
				ev.TakerAssetID.WriteToSlice(tokenID[:])
			} else {
				ev.MakerAssetID.WriteToSlice(tokenID[:])
			}
			hot.UserPositionsResolver.Queue(UserPositionsClockKey{User: ev.Maker, TokenID: tokenID})
		}
`)
	for _, plan := range plans {
		for _, source := range plan.sources {
			b.WriteString("\t\tfor _, ev := range block.")
			b.WriteString(source.slotField)
			b.WriteString(" {\n")
			b.WriteString("\t\t\thot.")
			b.WriteString(plan.baseName)
			b.WriteString("Resolver.Queue(")
			b.WriteString(plan.keyType)
			b.WriteString("{")
			for i, field := range source.fields {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(field.keyField)
				b.WriteString(": ev.")
				b.WriteString(field.eventField)
			}
			b.WriteString("})\n\t\t}\n")
		}
	}
	b.WriteString("\t}\n\n")

	// Resolve custom prefetch for Position
	b.WriteString("\tif err := hot.UserPositionsResolver.Resolve(ctx, store.Conn(), store.DB()); err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"prefetch Position: %w\", err)\n\t}\n")

	for _, plan := range plans {
		b.WriteString("\tif err := hot.")
		b.WriteString(plan.baseName)
		b.WriteString("Resolver.Resolve(ctx, store.Conn(), store.DB()); err != nil {\n")
		b.WriteString("\t\treturn fmt.Errorf(")
		b.WriteString(strconv.Quote("prefetch " + plan.stateName + ": %w"))
		b.WriteString(", err)\n\t}\n")
	}
	b.WriteString("\treturn nil\n}\n")
}

func renderGenericPrefetchProtoBlocksState(b *bytes.Buffer, cfg *config.Config, events []eventSpec, hotStateTables []customTableSpec) {
	plans := buildStatePrefetchPlans(cfg, events, hotStateSpecs(hotStateTables))
	if len(plans) == 0 {
		b.WriteString(`func prefetchProtoBlocksState(ctx context.Context, store Store, state *State, blocks []*ProtoEventBlock) error {
	return nil
}
`)
		return
	}

	b.WriteString(`func prefetchProtoBlocksState(ctx context.Context, store Store, state *State, blocks []*ProtoEventBlock) error {
	if state == nil || state.HotState == nil || len(blocks) == 0 {
		return nil
	}
	if store == nil {
		return nil
	}
	if store.Conn() == nil {
		return nil
	}
	hot := state.HotState

	for _, block := range blocks {
		if block == nil {
			continue
		}
		block.QueryExchangeOrderFilled().Map(func(ev ExchangeOrderFilledProtoView) {
			var tokenID common.Hash
			makerAssetID := ev.MakerAssetID()
			takerAssetID := ev.TakerAssetID()
			if makerAssetID.IsZero() {
				takerAssetID.WriteToSlice(tokenID[:])
			} else {
				makerAssetID.WriteToSlice(tokenID[:])
			}
			hot.UserPositionsResolver.Queue(UserPositionsClockKey{User: ev.Maker(), TokenID: tokenID})
		})
		block.QueryNegRiskExchangeOrderFilled().Map(func(ev NegRiskExchangeOrderFilledProtoView) {
			var tokenID common.Hash
			makerAssetID := ev.MakerAssetID()
			takerAssetID := ev.TakerAssetID()
			if makerAssetID.IsZero() {
				takerAssetID.WriteToSlice(tokenID[:])
			} else {
				makerAssetID.WriteToSlice(tokenID[:])
			}
			hot.UserPositionsResolver.Queue(UserPositionsClockKey{User: ev.Maker(), TokenID: tokenID})
		})
`)
	for _, plan := range plans {
		for _, source := range plan.sources {
			b.WriteString("\t\tblock.Query")
			b.WriteString(source.eventType)
			b.WriteString("().Map(func(ev ")
			b.WriteString(source.eventType)
			b.WriteString("ProtoView) {\n")
			b.WriteString("\t\t\thot.")
			b.WriteString(plan.baseName)
			b.WriteString("Resolver.Queue(")
			b.WriteString(plan.keyType)
			b.WriteString("{")
			for i, field := range source.fields {
				if i > 0 {
					b.WriteString(", ")
				}
				b.WriteString(field.keyField)
				b.WriteString(": ev.")
				b.WriteString(field.eventField)
				b.WriteString("()")
			}
			b.WriteString("})\n\t\t})\n")
		}
	}
	b.WriteString("\t}\n\n")

	b.WriteString("\tif err := hot.UserPositionsResolver.Resolve(ctx, store.Conn(), store.DB()); err != nil {\n")
	b.WriteString("\t\treturn fmt.Errorf(\"prefetch Position: %w\", err)\n\t}\n")

	for _, plan := range plans {
		b.WriteString("\tif err := hot.")
		b.WriteString(plan.baseName)
		b.WriteString("Resolver.Resolve(ctx, store.Conn(), store.DB()); err != nil {\n")
		b.WriteString("\t\treturn fmt.Errorf(")
		b.WriteString(strconv.Quote("prefetch " + plan.stateName + ": %w"))
		b.WriteString(", err)\n\t}\n")
	}
	b.WriteString("\treturn nil\n}\n")
}

func buildStatePrefetchPlans(cfg *config.Config, events []eventSpec, specs []hotStateSpec) []statePrefetchPlan {
	if cfg == nil || len(cfg.State) == 0 {
		return nil
	}
	var plans []statePrefetchPlan
	for _, state := range cfg.State {
		spec, ok := statePrefetchSpec(state, events, specs)
		if !ok {
			continue
		}
		keyFields := spec.table.keyFields()
		if len(keyFields) == 0 {
			continue
		}
		plan := statePrefetchPlan{
			stateName: state.Name,
			baseName:  spec.baseName,
			keyType:   spec.keyType,
			keyFields: keyFields,
		}
		for _, source := range events {
			fields, ok := statePrefetchFields(source, keyFields)
			if !ok {
				continue
			}
			plan.sources = append(plan.sources, statePrefetchSource{
				slotField: source.GoTypeName + "s",
				eventType: source.GoTypeName,
				fields:    fields,
			})
		}
		if len(plan.sources) > 0 {
			plans = append(plans, plan)
		}
	}
	return plans
}

func statePrefetchSpec(state config.StateConfig, events []eventSpec, specs []hotStateSpec) (hotStateSpec, bool) {
	if table, ok := findStateCustomTableSpec(hotStateTables(specs), state); ok {
		return findHotStateSpec(specs, table)
	}
	target, err := findStateEventSpec(events, state)
	if err != nil {
		return hotStateSpec{}, false
	}
	table := stateEventToCustomTableSpec(target, state)
	return findHotStateSpec(specs, table)
}

func statePrefetchFields(source eventSpec, keyFields []customFieldSpec) ([]statePrefetchField, bool) {
	fields := make([]statePrefetchField, 0, len(keyFields))
	for _, keyField := range keyFields {
		arg, ok := matchingStatePrefetchArg(source, keyField)
		if !ok {
			return nil, false
		}
		fields = append(fields, statePrefetchField{keyField: keyField.Name, eventField: arg.GoFieldName})
	}
	return fields, true
}

func matchingStatePrefetchArg(source eventSpec, keyField customFieldSpec) (eventArg, bool) {
	for _, arg := range source.Args {
		if arg.ColumnName == keyField.ColumnName || arg.Name == keyField.ColumnName || arg.GoFieldName == keyField.Name {
			return arg, true
		}
	}
	return eventArg{}, false
}
