package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/franz101/sqd-go/internal/config"
)

type hotStateSpec struct {
	table     customTableSpec
	baseName  string
	keyType   string
	entryType string
	cacheType string
	batchType string
}

func generateHotStateGo(tables []customTableSpec) ([]byte, error) {
	var b bytes.Buffer
	specs := hotStateSpecs(tables)

	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)
	renderHotStateImports(&b, tables)

	b.WriteString("const DefaultClockCacheCapacity uint64 = 100000\n\n")
	for _, spec := range specs {
		if !spec.table.IsEvent {
			renderHotStateEntity(&b, spec.table)
		}
		renderClockKey(&b, spec)
		renderClockCache(&b, spec)
		if !spec.table.IsEvent {
			renderCustomBatch(&b, spec)
			renderClockRecover(&b, spec)
		}
		renderBatchResolver(&b, spec)
	}
	renderHotStateType(&b, specs)
	renderHotStateHelpers(&b, tables)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format source: %w", err)
	}
	return formatted, nil
}

func renderHotStateImports(b *bytes.Buffer, tables []customTableSpec) {
	imports := map[string]string{
		`"context"`:                           "",
		`"fmt"`:                               "",
		`"strings"`:                           "",
		`"sync"`:                              "",
		`"sync/atomic"`:                       "",
		`"github.com/ClickHouse/ch-go"`:       "",
		`"github.com/ClickHouse/ch-go/proto"`: "",
	}
	if customTablesUseDecimal(tables) {
		imports[`"encoding/binary"`] = ""
		imports[`"math/big"`] = ""
	}
	for _, table := range tables {
		for _, field := range table.Fields {
			switch {
			case strings.Contains(field.Type, "time."):
				imports[`"time"`] = ""
			case strings.Contains(field.Type, "common."):
				imports[`"github.com/ethereum/go-ethereum/common"`] = ""
			case strings.Contains(field.Type, "uint256."):
				imports[`"github.com/holiman/uint256"`] = ""
			case strings.Contains(field.Type, "decimal."):
				imports[`"github.com/shopspring/decimal"`] = ""
			case strings.Contains(field.Type, "protomath."):
				imports[`"github.com/franz101/sqd-go/drafts/protomath"`] = ""
			}
		}
	}
	b.WriteString("import (\n")
	for _, imp := range sortedImportKeys(imports) {
		b.WriteString("\t")
		b.WriteString(imp)
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func renderHotStateEntity(b *bytes.Buffer, table customTableSpec) {
	b.WriteString("type ")
	b.WriteString(table.GoTypeName)
	b.WriteString(" struct {\n")
	for _, field := range table.Fields {
		b.WriteString("\t")
		b.WriteString(field.Name)
		b.WriteString(" ")
		b.WriteString(field.Type)
		b.WriteString(" `ch:")
		b.WriteString(strconv.Quote("name=" + field.ColumnName + ";type=" + field.ColumnType))
		b.WriteString("`\n")
	}
	b.WriteString("\tTombstone bool `ch:\"-\"`\n")
	b.WriteString("}\n\n")
}

func renderClockKey(b *bytes.Buffer, spec hotStateSpec) {
	keyFields := spec.table.keyFields()
	b.WriteString("type ")
	b.WriteString(spec.keyType)
	b.WriteString(" struct {\n")
	for _, field := range keyFields {
		b.WriteString("\t")
		b.WriteString(field.Name)
		b.WriteString(" ")
		b.WriteString(field.Type)
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func New")
	b.WriteString(spec.keyType)
	b.WriteString("(value ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(") ")
	b.WriteString(spec.keyType)
	b.WriteString(" {\n\treturn ")
	b.WriteString(spec.keyType)
	b.WriteString("{")
	for i, field := range keyFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(field.Name)
		b.WriteString(": value.")
		b.WriteString(field.Name)
	}
	b.WriteString("}\n}\n\n")
}

func renderClockCache(b *bytes.Buffer, spec hotStateSpec) {
	valueType := spec.table.GoTypeName
	keyFields := spec.table.keyFields()

	b.WriteString("type ")
	b.WriteString(spec.entryType)
	b.WriteString(" struct {\n\tkey ")
	b.WriteString(spec.keyType)
	b.WriteString("\n\tvalue ")
	b.WriteString(valueType)
	b.WriteString("\n\treferenced uint32\n\tinUse uint32\n}\n\n")

	b.WriteString("type ")
	b.WriteString(spec.cacheType)
	b.WriteString(" struct {\n\titems sync.Map\n\tring []")
	b.WriteString(spec.entryType)
	b.WriteString("\n\tcapacity uint64\n\thand uint64\n\tsize uint64\n}\n\n")

	b.WriteString("func New")
	b.WriteString(spec.cacheType)
	b.WriteString("(capacity uint64) *")
	b.WriteString(spec.cacheType)
	b.WriteString(" {\n\tif capacity == 0 {\n\t\tcapacity = DefaultClockCacheCapacity\n\t}\n\treturn &")
	b.WriteString(spec.cacheType)
	b.WriteString("{ring: make([]")
	b.WriteString(spec.entryType)
	b.WriteString(", capacity), capacity: capacity}\n}\n\n")

	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Set(value ")
	b.WriteString(valueType)
	b.WriteString(") {\n\tc.SetByKey(New")
	b.WriteString(spec.keyType)
	b.WriteString("(value), value)\n}\n\n")

	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") SetByKey(key ")
	b.WriteString(spec.keyType)
	b.WriteString(", value ")
	b.WriteString(valueType)
	b.WriteString(") {\n\tif idxVal, ok := c.items.Load(key); ok {\n\t\tidx := idxVal.(uint64)\n\t\te := &c.ring[idx]\n\t\tif atomic.LoadUint32(&e.inUse) == 1 && e.key == key {\n\t\t\te.value = value\n\t\t\tatomic.StoreUint32(&e.referenced, 1)\n\t\t\treturn\n\t\t}\n\t}\n\tfor {\n\t\thand := atomic.AddUint64(&c.hand, 1)\n\t\tidx := (hand - 1) % c.capacity\n\t\te := &c.ring[idx]\n\t\tif atomic.CompareAndSwapUint32(&e.inUse, 1, 0) {\n\t\t\tif atomic.LoadUint32(&e.referenced) == 1 {\n\t\t\t\tatomic.StoreUint32(&e.referenced, 0)\n\t\t\t\tatomic.StoreUint32(&e.inUse, 1)\n\t\t\t\tcontinue\n\t\t\t}\n\t\t\tc.items.Delete(e.key)\n\t\t\te.key = key\n\t\t\te.value = value\n\t\t\tatomic.StoreUint32(&e.referenced, 0)\n\t\t\tc.items.Store(key, idx)\n\t\t\tatomic.StoreUint32(&e.inUse, 1)\n\t\t\treturn\n\t\t}\n\t\tif atomic.LoadUint32(&e.inUse) == 0 {\n\t\t\tif atomic.CompareAndSwapUint32(&e.inUse, 0, 2) {\n\t\t\t\te.key = key\n\t\t\t\te.value = value\n\t\t\t\tatomic.StoreUint32(&e.referenced, 0)\n\t\t\t\tc.items.Store(key, idx)\n\t\t\t\tatomic.AddUint64(&c.size, 1)\n\t\t\t\tatomic.StoreUint32(&e.inUse, 1)\n\t\t\t\treturn\n\t\t\t}\n\t\t}\n\t}\n}\n\n")

	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Get(key ")
	b.WriteString(spec.keyType)
	b.WriteString(") (")
	b.WriteString(valueType)
	b.WriteString(", bool) {\n\tidxVal, ok := c.items.Load(key)\n\tif !ok {\n\t\treturn ")
	b.WriteString(valueType)
	b.WriteString("{}, false\n\t}\n\tidx := idxVal.(uint64)\n\te := &c.ring[idx]\n\tif atomic.LoadUint32(&e.inUse) == 1 && e.key == key {\n\t\tatomic.StoreUint32(&e.referenced, 1)\n\t\treturn e.value, true\n\t}\n\treturn ")
	b.WriteString(valueType)
	b.WriteString("{}, false\n}\n\n")

	if len(keyFields) > 0 {
		b.WriteString("func (c *")
		b.WriteString(spec.cacheType)
		b.WriteString(") GetByFields(")
		renderClockKeyParams(b, keyFields)
		b.WriteString(") (")
		b.WriteString(valueType)
		b.WriteString(", bool) {\n\treturn c.Get(")
		b.WriteString(spec.keyType)
		b.WriteString("{")
		for i, field := range keyFields {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(field.Name)
			b.WriteString(": ")
			b.WriteString(lowerFirst(field.Name))
		}
		b.WriteString("})\n}\n\n")
	}

	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Delete(key ")
	b.WriteString(spec.keyType)
	b.WriteString(") bool {\n\tidxVal, ok := c.items.Load(key)\n\tif !ok {\n\t\treturn false\n\t}\n\tidx := idxVal.(uint64)\n\te := &c.ring[idx]\n\tif atomic.CompareAndSwapUint32(&e.inUse, 1, 0) {\n\t\tif e.key == key {\n\t\t\tc.items.Delete(key)\n\t\t\te.key = ")
	b.WriteString(spec.keyType)
	b.WriteString("{}\n\t\t\te.value = ")
	b.WriteString(valueType)
	b.WriteString("{}\n\t\t\tatomic.StoreUint32(&e.referenced, 0)\n\t\t\tatomic.AddUint64(&c.size, ^uint64(0))\n\t\t\treturn true\n\t\t}\n\t\tatomic.StoreUint32(&e.inUse, 1)\n\t}\n\treturn false\n}\n\n")

	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Range(fn func(")
	b.WriteString(spec.keyType)
	b.WriteString(", ")
	b.WriteString(valueType)
	b.WriteString(") bool) {\n\tif fn == nil {\n\t\treturn\n\t}\n\tc.items.Range(func(keyAny, idxAny any) bool {\n\t\tkey, ok := keyAny.(")
	b.WriteString(spec.keyType)
	b.WriteString(")\n\t\tif !ok {\n\t\t\treturn true\n\t\t}\n\t\tidx, ok := idxAny.(uint64)\n\t\tif !ok || idx >= c.capacity {\n\t\t\treturn true\n\t\t}\n\t\te := &c.ring[idx]\n\t\tif atomic.LoadUint32(&e.inUse) == 1 && e.key == key {\n\t\t\treturn fn(key, e.value)\n\t\t}\n\t\treturn true\n\t})\n}\n\n")

	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") AppendValues(dst []")
	b.WriteString(valueType)
	b.WriteString(") []")
	b.WriteString(valueType)
	b.WriteString(" {\n\tif c == nil {\n\t\treturn dst\n\t}\n\tif atomic.LoadUint64(&c.size) == 0 {\n\t\treturn dst\n\t}\n\tlimit := atomic.LoadUint64(&c.hand)\n\tif limit > c.capacity {\n\t\tlimit = c.capacity\n\t}\n\tfor i := 0; i < int(limit); i++ {\n\t\te := &c.ring[i]\n\t\tif atomic.LoadUint32(&e.inUse) == 1 {\n\t\t\tdst = append(dst, e.value)\n\t\t}\n\t}\n\treturn dst\n}\n\n")

	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Len() uint64 {\n\treturn atomic.LoadUint64(&c.size)\n}\n\n")
}

func renderCustomBatch(b *bytes.Buffer, spec hotStateSpec) {
	b.WriteString("type ")
	b.WriteString(spec.batchType)
	b.WriteString(" struct {\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(batchColumnType(field))
		b.WriteString("\n")
		if scratch := batchScratchField(field); scratch != "" {
			b.WriteString("\t")
			b.WriteString(scratch)
			b.WriteString(" ")
			b.WriteString(batchScratchType(field))
			b.WriteString("\n")
		}
	}
	b.WriteString("\tinput proto.Input\n}\n\n")

	b.WriteString("func New")
	b.WriteString(spec.batchType)
	b.WriteString("() *")
	b.WriteString(spec.batchType)
	b.WriteString(" {\n\tb := &")
	b.WriteString(spec.batchType)
	b.WriteString("{}\n")
	for _, field := range spec.table.Fields {
		for _, line := range batchInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tb.input = proto.Input{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(batchInputData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n\treturn b\n}\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") TableName() string { return ")
	b.WriteString(strconv.Quote(spec.table.Name))
	b.WriteString(" }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Rows() int { return ")
	b.WriteString(batchColumnRowsExpr(spec.table.Fields[0]))
	b.WriteString(" }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Reset() { b.input.Reset() }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Append(item ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(") {\n")
	for _, field := range spec.table.Fields {
		for _, line := range batchAppendLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Inputs() proto.Input { return b.input }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Insert(ctx context.Context, conn *ch.Client, db string) error {\n\tif b.Rows() == 0 {\n\t\treturn nil\n\t}\n\treturn conn.Do(ctx, ch.Query{Body: fmt.Sprintf(")
	b.WriteString(strconv.Quote("INSERT INTO %s.%s " + customInsertColumnList(spec.table) + " VALUES"))
	// wait_for_async_insert MUST be 1: hot-state commits are read back on
	// prefetch/recovery/rollback. With wait=0 (fire-and-forget) a SELECT after
	// Commit can miss un-flushed rows, returning stale/partial state under load.
	b.WriteString(", quoteIdent(db), quoteIdent(b.TableName())), Input: b.input, Settings: []ch.Setting{{Key: \"async_insert\", Value: \"1\", Important: true}, {Key: \"wait_for_async_insert\", Value: \"1\", Important: true}}})\n}\n\n")
}

func renderClockRecover(b *bytes.Buffer, spec hotStateSpec) {
	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Recover(ctx context.Context, conn *ch.Client, db string) error {\n\tvar (\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(resultColumnType(field))
		b.WriteString("\n")
	}
	b.WriteString("\t)\n")
	for _, field := range spec.table.Fields {
		for _, line := range resultInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tresults := proto.Results{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(resultData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn conn.Do(ctx, ch.Query{Body: fmt.Sprintf(")
	b.WriteString(strconv.Quote(recoverQuery(spec.table)))
	b.WriteString(", quoteIdent(db), quoteIdent(")
	b.WriteString(strconv.Quote(spec.table.Name))
	b.WriteString(")), Result: results, OnResult: func(ctx context.Context, block proto.Block) error {\n\t\tfor i := 0; i < block.Rows; i++ {\n\t\t\titem := ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString("{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t\t\t")
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(resultValueExpr(field))
		b.WriteString(",\n")
	}
	b.WriteString("\t\t\t}\n\t\t\tc.Set(item)\n\t\t}\n\t\treturn nil\n\t}})\n}\n\n")
}

func renderHotStateType(b *bytes.Buffer, specs []hotStateSpec) {
	b.WriteString("type HotState struct {\n")
	for _, spec := range specs {
		resolverType := spec.table.GoTypeName + "BatchResolver"
		b.WriteString("\t")
		b.WriteString(spec.baseName)
		b.WriteString(" *")
		b.WriteString(spec.cacheType)
		b.WriteString("\n")

		b.WriteString("\t")
		b.WriteString(spec.baseName)
		b.WriteString("Resolver *")
		b.WriteString(resolverType)
		b.WriteString("\n")

		if !spec.table.IsEvent {
			b.WriteString("\tdirty")
			b.WriteString(spec.baseName)
			b.WriteString(" map[")
			b.WriteString(spec.keyType)
			b.WriteString("]struct{}\n")
		}
	}
	b.WriteString("\tmu sync.Mutex\n")
	b.WriteString("}\n\n")

	b.WriteString("func NewHotState(capacity uint64) *HotState {\n\tif capacity == 0 {\n\t\tcapacity = DefaultClockCacheCapacity\n\t}\n")
	b.WriteString("\tstate := &HotState{\n")
	for _, spec := range specs {
		b.WriteString("\t\t")
		b.WriteString(spec.baseName)
		b.WriteString(": New")
		b.WriteString(spec.cacheType)
		b.WriteString("(capacity),\n")
		if !spec.table.IsEvent {
			b.WriteString("\t\tdirty")
			b.WriteString(spec.baseName)
			b.WriteString(": make(map[")
			b.WriteString(spec.keyType)
			b.WriteString("]struct{}),\n")
		}
	}
	b.WriteString("\t}\n")
	for _, spec := range specs {
		resolverType := spec.table.GoTypeName + "BatchResolver"
		b.WriteString("\tstate.")
		b.WriteString(spec.baseName)
		b.WriteString("Resolver = New")
		b.WriteString(resolverType)
		b.WriteString("(state.")
		b.WriteString(spec.baseName)
		b.WriteString(")\n")
	}
	b.WriteString("\treturn state\n}\n\n")

	b.WriteString("func (s *HotState) Recover(ctx context.Context, conn *ch.Client, db string) error {\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tif err := s.")
		b.WriteString(spec.baseName)
		b.WriteString(".Recover(ctx, conn, db); err != nil {\n\t\treturn err\n\t}\n")
	}
	b.WriteString("\treturn nil\n}\n\n")

	// Generate Update methods
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("func (s *HotState) Update")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("(value ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(") {\n")
		b.WriteString("\ts.mu.Lock()\n")
		b.WriteString("\tdefer s.mu.Unlock()\n")
		b.WriteString("\ts.")
		b.WriteString(spec.baseName)
		b.WriteString(".Set(value)\n")
		b.WriteString("\ts.dirty")
		b.WriteString(spec.baseName)
		b.WriteString("[New")
		b.WriteString(spec.keyType)
		b.WriteString("(value)] = struct{}{}\n")
		b.WriteString("}\n\n")
	}

	// Generate Commit method
	b.WriteString("func (s *HotState) Commit(ctx context.Context, conn *ch.Client, db string) error {\n")
	b.WriteString("\ts.mu.Lock()\n")
	b.WriteString("\tdefer s.mu.Unlock()\n")
	b.WriteString("\tif conn == nil {\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\t\ts.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(" = make(map[")
		b.WriteString(spec.keyType)
		b.WriteString("]struct{})\n")
	}
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tif len(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(") > 0 {\n")
		b.WriteString("\t\tbatch := New")
		b.WriteString(spec.batchType)
		b.WriteString("()\n")
		b.WriteString("\t\tfor key := range s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(" {\n")
		b.WriteString("\t\t\tif val, ok := s.")
		b.WriteString(spec.baseName)
		b.WriteString(".Get(key); ok {\n")
		b.WriteString("\t\t\t\tbatch.Append(val)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tif err := batch.Insert(ctx, conn, db); err != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\ts.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(" = make(map[")
		b.WriteString(spec.keyType)
		b.WriteString("]struct{})\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn nil\n}\n")

		// Generate Restore methods for journal rollback
		for _, spec := range specs {
			if spec.table.IsEvent {
				continue
			}
			b.WriteString("func (s *HotState) Restore")
			b.WriteString(spec.table.GoTypeName)
			b.WriteString("(key ")
			b.WriteString(spec.keyType)
			b.WriteString(", value ")
			b.WriteString(spec.table.GoTypeName)
			b.WriteString(", had bool) {\n")
			b.WriteString("\ts.mu.Lock()\n")
			b.WriteString("\tdefer s.mu.Unlock()\n")
			b.WriteString("\tif had {\n")
			b.WriteString("\t\ts.")
			b.WriteString(spec.baseName)
			b.WriteString(".SetByKey(key, value)\n")
			b.WriteString("\t\ts.dirty")
			b.WriteString(spec.baseName)
			b.WriteString("[key] = struct{}{}\n")
			b.WriteString("\t\treturn\n")
			b.WriteString("\t}\n")
			b.WriteString("\ts.")
			b.WriteString(spec.baseName)
			b.WriteString(".Delete(key)\n")
			b.WriteString("\tdelete(s.dirty")
			b.WriteString(spec.baseName)
			b.WriteString(", key)\n")
			b.WriteString("}\n\n")
		}
}

func renderHotStateHelpers(b *bytes.Buffer, tables []customTableSpec) {
	if customTablesUseBool(tables) {
		b.WriteString("\nfunc hotStateBool(v bool) uint8 {\n\tif v {\n\t\treturn 1\n\t}\n\treturn 0\n}\n")
		b.WriteString("\nfunc hotStateBoolSQL(v bool) string {\n\tif v {\n\t\treturn \"1\"\n\t}\n\treturn \"0\"\n}\n")
	}
	if customTablesUseUint256(tables) || customTablesUseUint256Slice(tables) {
		b.WriteString(`
func hotStateUInt256(v uint256.Int) proto.UInt256 {
	return proto.UInt256{
		Low:  proto.UInt128{Low: v[0], High: v[1]},
		High: proto.UInt128{Low: v[2], High: v[3]},
	}
}

func hotStateUint256(v proto.UInt256) uint256.Int {
	return uint256.Int{v.Low.Low, v.Low.High, v.High.Low, v.High.High}
}
`)
	}
	if customTablesUseDecimal(tables) {
		b.WriteString(`
func hotStateDecimalToDecimal256(d decimal.Decimal) protomath.Decimal256 {
	out, _ := protomath.FromDecimal256ScaledBigInt(d.Shift(18).BigInt())
	return out
}

func hotStateDecimalFromDecimal256(v protomath.Decimal256) decimal.Decimal {
	return decimal.NewFromBigInt(v.ScaledBig(), -18)
}
`)
	}
	if customTablesUseType(tables, "protomath.Decimal256") {
		b.WriteString(`
type decimal256Col struct {
	proto.ColDecimal256
}

func (c *decimal256Col) Type() proto.ColumnType {
	return proto.ColumnType("Decimal(76, 18)")
}
`)
	}
	if customTablesUseHashSlice(tables) {
		b.WriteString(`
func hotStateHashSliceBytes(values []common.Hash, scratch [][]byte) [][]byte {
	scratch = scratch[:0]
	for _, value := range values {
		scratch = append(scratch, value.Bytes())
	}
	return scratch
}

func hotStateHashSlice(values [][]byte) []common.Hash {
	out := make([]common.Hash, 0, len(values))
	for _, value := range values {
		out = append(out, common.BytesToHash(value))
	}
	return out
}
`)
	}
	if customTablesUseUint256Slice(tables) {
		b.WriteString(`
func hotStateUInt256Slice(values []uint256.Int, scratch []proto.UInt256) []proto.UInt256 {
	scratch = scratch[:0]
	for _, value := range values {
		scratch = append(scratch, hotStateUInt256(value))
	}
	return scratch
}

func hotStateUint256Slice(values []proto.UInt256) []uint256.Int {
	out := make([]uint256.Int, 0, len(values))
	for _, value := range values {
		out = append(out, hotStateUint256(value))
	}
	return out
}
`)
	}
}

func renderClockKeyParams(b *bytes.Buffer, fields []customFieldSpec) {
	for i, field := range fields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(lowerFirst(field.Name))
		b.WriteString(" ")
		b.WriteString(field.Type)
	}
}

func hotStateSpecs(tables []customTableSpec) []hotStateSpec {
	used := make(map[string]int)
	specs := make([]hotStateSpec, 0, len(tables))
	for _, table := range tables {
		var base string
		if table.BaseName != "" {
			base = uniqueExported(used, table.BaseName)
		} else {
			base = uniqueExported(used, customClockBaseName(table.GoTypeName))
		}
		specs = append(specs, hotStateSpec{
			table:     table,
			baseName:  base,
			keyType:   base + "ClockKey",
			entryType: base + "ClockEntry",
			cacheType: base + "ClockCache",
			batchType: table.GoTypeName + "Batch",
		})
	}
	return specs
}

func customClockBaseName(typeName string) string {
	name := strings.TrimPrefix(customTableEntityName(typeName), "Memory")
	return pluralizeGoName(name)
}

func pluralizeGoName(name string) string {
	switch {
	case name == "":
		return "Entities"
	case strings.HasSuffix(name, "s"), strings.HasSuffix(name, "S"):
		return name
	case strings.HasSuffix(name, "y"):
		return strings.TrimSuffix(name, "y") + "ies"
	case strings.HasSuffix(name, "Y"):
		return strings.TrimSuffix(name, "Y") + "ies"
	default:
		return name + "s"
	}
}

func lowerFirst(name string) string {
	if name == "" {
		return "value"
	}
	if name == strings.ToUpper(name) {
		return strings.ToLower(name)
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func sortedImportKeys(imports map[string]string) []string {
	keys := make([]string, 0, len(imports))
	for key := range imports {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func batchColumnField(field customFieldSpec) string {
	return "col" + field.Name
}

func batchScratchField(field customFieldSpec) string {
	switch field.Type {
	case "[]common.Hash", "[]uint256.Int":
		return "scratch" + field.Name
	default:
		return ""
	}
}

func batchScratchType(field customFieldSpec) string {
	switch field.Type {
	case "[]common.Hash":
		return "[][]byte"
	case "[]uint256.Int":
		return "[]proto.UInt256"
	default:
		return ""
	}
}

func batchColumnType(field customFieldSpec) string {
	switch field.Type {
	case "bool", "uint8":
		return "proto.ColUInt8"
	case "uint16":
		return "proto.ColUInt16"
	case "uint32":
		return "proto.ColUInt32"
	case "uint", "uint64":
		return "proto.ColUInt64"
	case "int8":
		return "proto.ColInt8"
	case "int16":
		return "proto.ColInt16"
	case "int32":
		return "proto.ColInt32"
	case "int", "int64":
		return "proto.ColInt64"
	case "float32":
		return "proto.ColFloat32"
	case "float64":
		return "proto.ColFloat64"
	case "string", "[]byte":
		return "proto.ColStr"
	case "time.Time":
		return "proto.ColDateTime64"
	case "common.Address", "common.Hash":
		return "proto.ColFixedStr"
	case "uint256.Int":
		return "proto.ColUInt256"
	case "decimal.Decimal":
		return "decimal256Col"
	case "protomath.Decimal256":
		return "decimal256Col"
	case "[]common.Hash":
		return "*proto.ColArr[[]byte]"
	case "[]uint256.Int":
		return "*proto.ColArr[proto.UInt256]"
	case "[]string":
		return "*proto.ColArr[string]"
	default:
		return "proto.ColStr"
	}
}

func resultColumnType(field customFieldSpec) string {
	return batchColumnType(field)
}

func batchInitLines(field customFieldSpec) []string {
	return initLines("b.", field)
}

func resultInitLines(field customFieldSpec) []string {
	if field.Type == "decimal.Decimal" {
		return nil
	}
	return initLines("", field)
}

func initLines(prefix string, field customFieldSpec) []string {
	col := prefix + batchColumnField(field)
	switch field.Type {
	case "common.Address":
		return []string{col + ".SetSize(20)"}
	case "common.Hash":
		return []string{col + ".SetSize(32)"}
	case "time.Time":
		return []string{col + ".WithPrecision(proto.Precision(3))", col + ".WithLocation(time.UTC)"}
	case "[]common.Hash":
		return []string{col + " = (&proto.ColFixedStr{Size: 32}).Array()"}
	case "[]uint256.Int":
		return []string{col + " = new(proto.ColUInt256).Array()"}
	case "[]string":
		return []string{col + " = new(proto.ColStr).Array()"}
	default:
		return nil
	}
}

func batchInputData(field customFieldSpec) string {
	col := "b." + batchColumnField(field)
	switch field.Type {
	case "decimal.Decimal", "protomath.Decimal256":
		return "&" + col
	case "[]common.Hash", "[]uint256.Int", "[]string":
		return col
	default:
		return "&" + col
	}
}

func resultData(field customFieldSpec) string {
	col := batchColumnField(field)
	switch field.Type {
	case "decimal.Decimal", "protomath.Decimal256":
		return "&" + col
	case "[]common.Hash", "[]uint256.Int", "[]string":
		return col
	default:
		return "&" + col
	}
}

func batchColumnRowsExpr(field customFieldSpec) string {
	col := "b." + batchColumnField(field)
	if strings.HasPrefix(field.Type, "[]") {
		return col + ".Rows()"
	}
	return col + ".Rows()"
}

func batchAppendLines(field customFieldSpec) []string {
	col := "b." + batchColumnField(field)
	value := "item." + field.Name
	switch field.Type {
	case "common.Address", "common.Hash":
		return []string{col + ".Append(" + value + ".Bytes())"}
	case "bool":
		return []string{col + ".Append(hotStateBool(" + value + "))"}
	case "[]byte":
		return []string{col + ".AppendBytes(" + value + ")"}
	case "decimal.Decimal":
		return []string{col + ".Append(hotStateDecimalToDecimal256(" + value + ").Proto())"}
	case "protomath.Decimal256":
		return []string{col + ".Append(" + value + ".Proto())"}
	case "uint256.Int":
		return []string{col + ".Append(hotStateUInt256(" + value + "))"}
	case "[]common.Hash":
		return []string{col + ".Append(hotStateHashSliceBytes(" + value + ", b." + batchScratchField(field) + "))"}
	case "[]uint256.Int":
		return []string{col + ".Append(hotStateUInt256Slice(" + value + ", b." + batchScratchField(field) + "))"}
	default:
		return []string{col + ".Append(" + value + ")"}
	}
}

func resultValueExpr(field customFieldSpec) string {
	col := batchColumnField(field)
	switch field.Type {
	case "common.Address":
		return "common.BytesToAddress(" + col + ".Row(i))"
	case "common.Hash":
		return "common.BytesToHash(" + col + ".Row(i))"
	case "bool":
		return col + ".Row(i) != 0"
	case "[]byte":
		return "append([]byte(nil), " + col + ".RowBytes(i)...)"
	case "decimal.Decimal":
		return "hotStateDecimalFromDecimal256(protomath.Decimal256(" + col + ".Row(i)))"
	case "protomath.Decimal256":
		return "protomath.Decimal256(" + col + ".Row(i))"
	case "uint256.Int":
		return "hotStateUint256(" + col + ".Row(i))"
	case "[]common.Hash":
		return "hotStateHashSlice(" + col + ".Row(i))"
	case "[]uint256.Int":
		return "hotStateUint256Slice(" + col + ".Row(i))"
	default:
		return col + ".Row(i)"
	}
}

func customInsertColumnList(table customTableSpec) string {
	columns := make([]string, 0, len(table.Columns))
	for _, column := range table.Columns {
		columns = append(columns, quoteSQLIdent(column.Name))
	}
	return "(" + strings.Join(columns, ", ") + ")"
}

func recoverQuery(table customTableSpec) string {
	selects := make([]string, 0, len(table.Fields))
	for _, field := range table.Fields {
		selects = append(selects, quoteSQLIdent(field.ColumnName))
	}
	return "SELECT " + strings.Join(selects, ", ") + " FROM %s.%s ORDER BY block_number DESC, transaction_index DESC, log_index DESC LIMIT 1 BY " + strings.Join(quotedColumns(table.PrimaryKey), ", ")
}

func quotedColumns(columns []string) []string {
	out := make([]string, 0, len(columns))
	for _, column := range columns {
		out = append(out, quoteSQLIdent(column))
	}
	return out
}

func customTablesUseDecimal(tables []customTableSpec) bool {
	return customTablesUseType(tables, "decimal.Decimal")
}

func customTablesUseBool(tables []customTableSpec) bool {
	return customTablesUseType(tables, "bool")
}

func customTablesUseUint256(tables []customTableSpec) bool {
	return customTablesUseType(tables, "uint256.Int")
}

func customTablesUseHashSlice(tables []customTableSpec) bool {
	return customTablesUseType(tables, "[]common.Hash")
}

func customTablesUseUint256Slice(tables []customTableSpec) bool {
	return customTablesUseType(tables, "[]uint256.Int")
}

func customTablesUseType(tables []customTableSpec, typ string) bool {
	for _, table := range tables {
		for _, field := range table.Fields {
			if field.Type == typ {
				return true
			}
		}
	}
	return false
}

func renderBatchResolver(b *bytes.Buffer, spec hotStateSpec) {
	resolverType := spec.table.GoTypeName + "BatchResolver"
	cacheType := spec.cacheType
	keyType := spec.keyType
	valueType := spec.table.GoTypeName

	b.WriteString("type ")
	b.WriteString(resolverType)
	b.WriteString(" struct {\n\tcache  *")
	b.WriteString(cacheType)
	b.WriteString("\n\tmisses []")
	b.WriteString(keyType)
	b.WriteString("\n}\n\n")

	b.WriteString("func New")
	b.WriteString(resolverType)
	b.WriteString("(cache *")
	b.WriteString(cacheType)
	b.WriteString(") *")
	b.WriteString(resolverType)
	b.WriteString(" {\n\treturn &")
	b.WriteString(resolverType)
	b.WriteString("{\n\t\tcache: cache,\n\t}\n}\n\n")

	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Queue(key ")
	b.WriteString(keyType)
	b.WriteString(") {\n\tif _, ok := r.cache.Get(key); !ok {\n\t\tr.misses = append(r.misses, key)\n\t}\n}\n\n")

	b.WriteString("// Pending reports how many missed keys are queued for the next Resolve.\n")
	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Pending() int {\n\treturn len(r.misses)\n}\n\n")

	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Resolve(ctx context.Context, conn *ch.Client, db string) error {\n")
	b.WriteString("\tif len(r.misses) == 0 {\n\t\treturn nil\n\t}\n\n")
	b.WriteString("\tuniqueKeys := make(map[")
	b.WriteString(keyType)
	b.WriteString("]struct{})\n")
	b.WriteString("\tvar uniqueList []")
	b.WriteString(keyType)
	b.WriteString("\n\tfor _, key := range r.misses {\n")
	b.WriteString("\t\tif _, ok := uniqueKeys[key]; !ok {\n")
	b.WriteString("\t\t\tuniqueKeys[key] = struct{}{}\n")
	b.WriteString("\t\t\tuniqueList = append(uniqueList, key)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tr.misses = nil\n\n")
	b.WriteString("\tif len(uniqueList) == 0 {\n\t\treturn nil\n\t}\n\n")

	keyFields := spec.table.keyFields()
	if len(keyFields) > 1 {
		b.WriteString("\tvar values []string\n")
		b.WriteString("\tfor _, key := range uniqueList {\n")
		b.WriteString("\t\tvalues = append(values, \"(\"")
		for i, field := range keyFields {
			if i > 0 {
				b.WriteString(" + \", \"")
			}
			b.WriteString(" + ")
			b.WriteString(keySQLValueExpr("key."+field.Name, field))
		}
		b.WriteString(" + \")\")\n")
		b.WriteString("\t}\n\n")

		queryBody := fmt.Sprintf("SELECT %s FROM %%s.%s WHERE %s IN (%%s) ORDER BY `block_number` DESC, `transaction_index` DESC, `log_index` DESC LIMIT 1 BY %s",
			customSelectColumnList(spec.table),
			spec.table.Name,
			customInsertColumnList(customTableSpec{Columns: keyColumns(keyFields)}),
			keyColumnExpressionList(keyFields),
		)
		b.WriteString(fmt.Sprintf("\tqueryStr := fmt.Sprintf(%s, quoteIdent(db), strings.Join(values, \", \"))\n\n",
			strconv.Quote(queryBody),
		))
	} else if len(keyFields) == 1 {
		b.WriteString("\tvar values []string\n")
		b.WriteString("\tfor _, key := range uniqueList {\n")
		keyField := keyFields[0]
		b.WriteString("\t\tvalues = append(values, ")
		b.WriteString(keySQLValueExpr("key."+keyField.Name, keyField))
		b.WriteString(")\n")
		b.WriteString("\t}\n\n")

		queryBody := fmt.Sprintf("SELECT %s FROM %%s.%s WHERE %s IN (%%s) ORDER BY `block_number` DESC, `transaction_index` DESC, `log_index` DESC LIMIT 1 BY %s",
			customSelectColumnList(spec.table),
			spec.table.Name,
			quoteSQLIdent(keyField.ColumnName),
			keyColumnExpressionList(keyFields),
		)
		b.WriteString(fmt.Sprintf("\tqueryStr := fmt.Sprintf(%s, quoteIdent(db), strings.Join(values, \", \"))\n\n",
			strconv.Quote(queryBody),
		))
	} else {
		b.WriteString("\tqueryStr := \"\"\n")
	}

	b.WriteString("\tvar (\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(resultColumnType(field))
		b.WriteString("\n")
	}
	b.WriteString("\t)\n")
	for _, field := range spec.table.Fields {
		for _, line := range resultInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tresults := proto.Results{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(resultData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")

	b.WriteString("\tfoundKeys := make(map[")
	b.WriteString(keyType)
	b.WriteString("]struct{})\n")
	b.WriteString("\tq := ch.Query{\n")
	b.WriteString("\t\tBody:   queryStr,\n")
	b.WriteString("\t\tResult: results,\n")
	b.WriteString("\t\tOnResult: func(ctx context.Context, block proto.Block) error {\n")
	b.WriteString("\t\t\tfor i := 0; i < block.Rows; i++ {\n")
	b.WriteString("\t\t\t\titem := ")
	b.WriteString(valueType)
	b.WriteString("{\n")
	if spec.table.IsEvent {
		b.WriteString("\t\t\t\t\tEventMeta: EventMeta{\n")
		for _, field := range spec.table.Fields {
			if field.Name == "BlockNumber" || field.Name == "BlockTimestamp" || field.Name == "TransactionIndex" || field.Name == "LogIndex" {
				b.WriteString("\t\t\t\t\t\t")
				b.WriteString(field.Name)
				b.WriteString(": ")
				b.WriteString(resultValueExpr(field))
				b.WriteString(",\n")
			}
		}
		b.WriteString("\t\t\t\t\t},\n")
		for _, field := range spec.table.Fields {
			if !(field.Name == "BlockNumber" || field.Name == "BlockTimestamp" || field.Name == "TransactionIndex" || field.Name == "LogIndex") {
				b.WriteString("\t\t\t\t\t")
				b.WriteString(field.Name)
				b.WriteString(": ")
				b.WriteString(resultValueExpr(field))
				b.WriteString(",\n")
			}
		}
	} else {
		for _, field := range spec.table.Fields {
			b.WriteString("\t\t\t\t\t")
			b.WriteString(field.Name)
			b.WriteString(": ")
			b.WriteString(resultValueExpr(field))
			b.WriteString(",\n")
		}
	}
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\tr.cache.Set(item)\n")
	b.WriteString("\t\t\t\tfoundKeys[New")
	b.WriteString(keyType)
	b.WriteString("(item)] = struct{}{}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\treturn nil\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := conn.Do(ctx, q); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tfor _, key := range uniqueList {\n")
	b.WriteString("\t\tif _, found := foundKeys[key]; !found {\n")
	b.WriteString("\t\t\ttombstone := ")
	b.WriteString(valueType)
	b.WriteString("{Tombstone: true}\n")
	for _, field := range keyFields {
		b.WriteString("\t\t\ttombstone.")
		b.WriteString(field.Name)
		b.WriteString(" = key.")
		b.WriteString(field.Name)
		b.WriteString("\n")
	}
	b.WriteString("\t\t\tr.cache.SetByKey(key, tombstone)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

func keySQLValueExpr(expr string, field customFieldSpec) string {
	switch field.Type {
	case "common.Address", "common.Hash":
		return fmt.Sprintf("fmt.Sprintf(\"unhex('%%s')\", strings.TrimPrefix(%s.Hex(), \"0x\"))", expr)
	case "string":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", strings.ReplaceAll(%s, \"'\", \"''\"))", expr)
	case "bool":
		return fmt.Sprintf("hotStateBoolSQL(%s)", expr)
	case "uint256.Int":
		return expr + ".Dec()"
	case "decimal.Decimal":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.String())", expr)
	case "protomath.Decimal256":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.String(protomath.Decimal256Scale18))", expr)
	case "float32", "float64":
		return fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", expr)
	case "time.Time":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.UTC().Format(time.RFC3339Nano))", expr)
	default:
		return fmt.Sprintf("fmt.Sprintf(\"%%d\", %s)", expr)
	}
}

func customSelectColumnList(table customTableSpec) string {
	selects := make([]string, 0, len(table.Fields))
	for _, field := range table.Fields {
		selects = append(selects, quoteSQLIdent(field.ColumnName))
	}
	return strings.Join(selects, ", ")
}

func keyColumns(fields []customFieldSpec) []customColumnSpec {
	out := make([]customColumnSpec, 0, len(fields))
	for _, f := range fields {
		out = append(out, customColumnSpec{Name: f.ColumnName})
	}
	return out
}

func keyColumnExpressionList(fields []customFieldSpec) string {
	out := make([]string, 0, len(fields))
	for _, field := range fields {
		out = append(out, quoteSQLIdent(field.ColumnName))
	}
	return strings.Join(out, ", ")
}

func findStateEventSpec(events []eventSpec, state config.StateConfig) (*eventSpec, error) {
	if state.SourceTable != "" {
		for _, ev := range events {
			if ev.TableName == state.SourceTable {
				return &ev, nil
			}
		}
	}
	// Try to resolve from state.Name
	for _, ev := range events {
		if strings.EqualFold(ev.EventName, state.Name) || strings.EqualFold(ev.GoTypeName, state.Name) {
			return &ev, nil
		}
	}
	// Fallback: try to see if any event table contains the state name
	for _, ev := range events {
		if strings.Contains(strings.ToLower(ev.TableName), strings.ToLower(state.Name)) {
			return &ev, nil
		}
	}
	return nil, fmt.Errorf("source table or event matching %q not found in event tables", state.Name)
}
