package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/franz101/sqd-go/internal/config"
)

type hotStateSpec struct {
	table     customTableSpec
	baseName  string
	keyType   string
	entryType string
	cacheType string
	batchType string
}

func generateHotStateGo(tables []customTableSpec, events []eventSpec) ([]byte, error) {
	var b bytes.Buffer
	specs := hotStateSpecs(tables)

	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)
	renderHotStateImports(&b, tables, events)

	b.WriteString("const DefaultClockCacheCapacity uint64 = 100000\n")
	if len(specs) > 0 {
		b.WriteString("const recoveryBucketCount = 8\n")
		b.WriteString("const recoveryConcurrency = 8\n\n")
		b.WriteString(`func recoveryFixedStringRange(column string, bucket int, size int) string {
	if recoveryBucketCount <= 1 {
		return "1"
	}
	width := 256 / recoveryBucketCount
	lower := bucket * width
	lowerHex := fmt.Sprintf("%02x%s", lower, strings.Repeat("00", size-1))
	lowerExpr := fmt.Sprintf("toFixedString(unhex('%s'), %d)", lowerHex, size)
	if bucket >= recoveryBucketCount-1 {
		return fmt.Sprintf("%s >= %s", column, lowerExpr)
	}
	upper := (bucket + 1) * width
	upperHex := fmt.Sprintf("%02x%s", upper, strings.Repeat("00", size-1))
	upperExpr := fmt.Sprintf("toFixedString(unhex('%s'), %d)", upperHex, size)
	return fmt.Sprintf("%s >= %s AND %s < %s", column, lowerExpr, column, upperExpr)
}

func recoveryDialConn(ctx context.Context) (*ch.Client, error) {
	host := os.Getenv("CLICKHOUSE_HOST")
	if host == "" {
		host = "127.0.0.1"
	}
	port := 9000
	if v := os.Getenv("CLICKHOUSE_NATIVE_PORT"); v != "" {
		if p, err := strconv.Atoi(v); err == nil {
			port = p
		}
	}
	user := os.Getenv("CLICKHOUSE_USER")
	if user == "" {
		user = "default"
	}
	return ch.Dial(ctx, ch.Options{
		Address:  fmt.Sprintf("%s:%d", host, port),
		Database: "default",
		User:     user,
		Password: os.Getenv("CLICKHOUSE_PASSWORD"),
	})
}

func recoveryRecencyClause() string {
	v := os.Getenv("SQD_RECOVERY_MIN_BLOCK")
	if v == "" {
		return ""
	}
	mb, err := strconv.ParseUint(v, 10, 64)
	if err != nil || mb == 0 {
		return ""
	}
	return " AND " + quoteIdent("t") + "." + quoteIdent("updated_at_block") + " >= " + strconv.FormatUint(mb, 10)
}

func recoverColdParallel[T any](
	ctx context.Context,
	primary *ch.Client,
	nbuckets int,
	cold *coldcache.Store,
	run func(ctx context.Context, conn *ch.Client, bucket int, emit func(T)) error,
	encode func(v T, put func(key, val []byte) error) error,
) error {
	conc := recoveryConcurrency
	if conc > nbuckets {
		conc = nbuckets
	}
	if conc < 1 {
		conc = 1
	}
	conns := make([]*ch.Client, 1, conc)
	conns[0] = primary
	for len(conns) < conc {
		wc, err := recoveryDialConn(ctx)
		if err != nil {
			break
		}
		conns = append(conns, wc)
	}
	defer func() {
		for _, wc := range conns[1:] {
			_ = wc.Close()
		}
	}()

	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	buckets := make(chan int)
	var (
		wg       sync.WaitGroup
		errMu    sync.Mutex
		firstErr error
	)
	fail := func(err error) {
		if err == nil {
			return
		}
		errMu.Lock()
		if firstErr == nil {
			firstErr = err
			cancel()
		}
		errMu.Unlock()
	}
	for _, conn := range conns {
		wg.Add(1)
		go func(conn *ch.Client) {
			defer wg.Done()
			batch := cold.NewWriteBatch()
			defer func() {
				if err := batch.Close(); err != nil {
					fail(err)
				}
			}()
			emit := func(v T) {
				if err := encode(v, batch.Put); err != nil {
					fail(err)
				}
			}
			for bucket := range buckets {
				if err := run(ctx, conn, bucket, emit); err != nil {
					fail(err)
					return
				}
			}
		}(conn)
	}
feed:
	for bucket := 0; bucket < nbuckets; bucket++ {
		select {
		case buckets <- bucket:
		case <-ctx.Done():
			break feed
		}
	}
	close(buckets)
	wg.Wait()
	return firstErr
}

`)
	} else {
		b.WriteString("\n")
	}
	for _, spec := range specs {
		if !spec.table.IsEvent {
			renderHotStateEntity(&b, spec.table)
		}
		renderClockKey(&b, spec)
		renderClockCache(&b, spec)
		if !spec.table.IsEvent {
			renderCustomBatch(&b, spec)
			renderClockRecover(&b, spec)
		}
		renderBatchResolver(&b, spec)
	}
	renderHotStateType(&b, specs)
	renderHotStateHelpers(&b, tables, events)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format source: %w", err)
	}
	return formatted, nil
}

func renderHotStateImports(b *bytes.Buffer, tables []customTableSpec, events []eventSpec) {
	imports := map[string]string{
		`"context"`:                              "",
		`"encoding/binary"`:                      "",
		`"fmt"`:                                  "",
		`"strings"`:                              "",
		`"sync"`:                                 "",
		`"sync/atomic"`:                          "",
		`"github.com/ClickHouse/ch-go"`:          "",
		`"github.com/ClickHouse/ch-go/proto"`:    "",
		`"github.com/franz101/sqd-go/coldcache"`: "",
	}
	if customTablesUseDecimal(tables) {
		imports[`"encoding/binary"`] = ""
		imports[`"math/big"`] = ""
	}
	if len(tables) > 0 {
		imports[`"os"`] = ""
		imports[`"strconv"`] = ""
		imports[`"time"`] = ""
	}
	if customTablesUseColdCache(tables) {
		// Cold tier (Pebble): pointer-free values are stored as raw bytes via
		// zero-transformation unsafe memcpy; pointer-bearing (but serializable)
		// values go through a generated marshal/unmarshal codec. filepath builds
		// the per-cache dir; unsafe keys the cold lookups (keys are always flat).
		imports[`"path/filepath"`] = ""
		imports[`"unsafe"`] = ""
	}
	for _, table := range tables {
		for _, field := range table.Fields {
			switch {
			case strings.Contains(field.Type, "time."):
				imports[`"time"`] = ""
			case strings.Contains(field.Type, "common."):
				imports[`"github.com/ethereum/go-ethereum/common"`] = ""
			case strings.Contains(field.Type, "uint256."):
				imports[`"github.com/holiman/uint256"`] = ""
			case strings.Contains(field.Type, "decimal."):
				imports[`"github.com/shopspring/decimal"`] = ""
			case strings.Contains(field.Type, "protomath."):
				imports[`"github.com/franz101/sqd-go/protomath"`] = ""
			}
		}
	}
	// Event views (ProtoEventBlock) reference the uint256 hot-state helpers for any
	// event with a uint256/uint256[] arg, even when no custom/hot-state table uses
	// uint256 — so the import must follow event usage too.
	if eventsUseUint256(events) || eventsUseUint256Slice(events) {
		imports[`"github.com/holiman/uint256"`] = ""
	}
	b.WriteString("import (\n")
	for _, imp := range sortedImportKeys(imports) {
		b.WriteString("\t")
		b.WriteString(imp)
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func renderHotStateEntity(b *bytes.Buffer, table customTableSpec) {
	b.WriteString("type ")
	b.WriteString(table.GoTypeName)
	b.WriteString(" struct {\n")
	for _, field := range table.Fields {
		b.WriteString("\t")
		b.WriteString(field.Name)
		b.WriteString(" ")
		b.WriteString(memoryGoType(field, table.IsEvent))
		b.WriteString(" `ch:")
		b.WriteString(strconv.Quote("name=" + field.ColumnName + ";type=" + field.ColumnType))
		b.WriteString("`\n")
	}
	b.WriteString("\tTombstone bool `ch:\"-\"`\n")
	b.WriteString("}\n\n")
}

func renderClockKey(b *bytes.Buffer, spec hotStateSpec) {
	keyFields := spec.table.keyFields()
	b.WriteString("type ")
	b.WriteString(spec.keyType)
	b.WriteString(" struct {\n")
	for _, field := range keyFields {
		b.WriteString("\t")
		b.WriteString(field.Name)
		b.WriteString(" ")
		b.WriteString(field.Type)
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func New")
	b.WriteString(spec.keyType)
	b.WriteString("(value ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(") ")
	b.WriteString(spec.keyType)
	b.WriteString(" {\n\treturn ")
	b.WriteString(spec.keyType)
	b.WriteString("{")
	for i, field := range keyFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(field.Name)
		b.WriteString(": value.")
		b.WriteString(field.Name)
	}
	b.WriteString("}\n}\n\n")
}

func renderClockCache(b *bytes.Buffer, spec hotStateSpec) {
	valueType := spec.table.GoTypeName
	keyFields := spec.table.keyFields()

	b.WriteString("type ")
	b.WriteString(spec.entryType)
	b.WriteString(" struct {\n\tkey ")
	b.WriteString(spec.keyType)
	b.WriteString("\n\tvalue ")
	b.WriteString(valueType)
	b.WriteString("\n\treferenced uint32\n\tinUse uint32\n}\n\n")

	// Cache struct. The index is a pointer-free chained hash over an arena (A3):
	// buckets[h] = ring index of a chain head (-1 = empty); next[ringIdx] = next
	// ring index in the same bucket (-1 = end). Replaces a sync.Map[key]idx whose
	// boxed key+idx interfaces were ~3 GC-scanned objects per live entry. The
	// runtime uses one processor owner after startup. Atomics on slot flags do not
	// make the full cache concurrent-safe because the index and values are plain;
	// they remain because the measured atomic-free candidate was not a consistent
	// full-workload improvement.
	fmt.Fprintf(b, `type %[1]s struct {
	// buckets, next, ring form a fixed-size clock replacement cache.
	// SINGLE-OWNER CONTRACT: This cache is NOT thread-safe. All operations
	// must occur from a single goroutine (the processor). Concurrent access
	// will corrupt the linked-list structures and cause data races.
	// The atomics used for entry flags (inUse, referenced) protect only
	// the per-slot state, NOT the cache index structures.
	buckets  []int32
	next     []int32
	ring     []%[2]s
	mask     uint32
	capacity uint64
	hand     uint64
	size     uint64
	// cold is an optional Pebble-backed tier holding evicted entries (raw bytes for
	// pointer-free entities, or a marshaled payload for serializable ones). nil
	// unless attached via HotState.EnableColdCache.
	cold    *coldcache.Store
	metrics *BatchResolverMetrics
}

func New%[1]s(capacity uint64) *%[1]s {
	if capacity == 0 {
		capacity = DefaultClockCacheCapacity
	}
	bucketCount := uint64(8)
	for bucketCount < capacity*2 {
		bucketCount <<= 1
	}
	c := &%[1]s{
		ring:     make([]%[2]s, capacity),
		buckets:  make([]int32, bucketCount),
		next:     make([]int32, capacity),
		mask:     uint32(bucketCount - 1),
		capacity: capacity,
	}
	for i := range c.buckets {
		c.buckets[i] = -1
	}
	for i := range c.next {
		c.next[i] = -1
	}
	return c
}

`, spec.cacheType, spec.entryType)

	// keyHash folds fixed-width keys by machine words. Hash and address keys are
	// already uniformly distributed, so byte-at-a-time FNV adds work without
	// improving the cache index distribution.
	fmt.Fprintf(b, "func (c *%s) keyHash(key %s) uint32 {\n\th := uint64(1469598103934665603)\n", spec.cacheType, spec.keyType)
	for _, field := range keyFields {
		switch field.Type {
		case "common.Address":
			fmt.Fprintf(b, "\th = clockHash20(h, key.%s[:])\n", field.Name)
		case "common.Hash":
			fmt.Fprintf(b, "\th = clockHash32(h, key.%s[:])\n", field.Name)
		default:
			fmt.Fprintf(b, "\th = clockHashBytes(h, key.%s[:])\n", field.Name)
		}
	}
	b.WriteString("\treturn uint32(h^(h>>32)) & c.mask\n}\n\n")

	fmt.Fprintf(b, `func (c *%[1]s) idxLookup(key %[2]s) (uint64, bool) {
	for i := c.buckets[c.keyHash(key)]; i >= 0; i = c.next[i] {
		if c.ring[i].key == key {
			return uint64(i), true
		}
	}
	return 0, false
}

func (c *%[1]s) idxInsert(key %[2]s, ringIdx uint32) {
	h := c.keyHash(key)
	c.next[ringIdx] = c.buckets[h]
	c.buckets[h] = int32(ringIdx)
}

func (c *%[1]s) idxUnlink(key %[2]s) {
	h := c.keyHash(key)
	prev := int32(-1)
	for i := c.buckets[h]; i >= 0; i = c.next[i] {
		if c.ring[i].key == key {
			if prev < 0 {
				c.buckets[h] = c.next[i]
			} else {
				c.next[prev] = c.next[i]
			}
			c.next[i] = -1
			return
		}
		prev = i
	}
}

`, spec.cacheType, spec.keyType)

	coldOn := entityUsesCold(spec.table)
	coldFree := coldOn && isPointerFreeEntity(spec.table) // raw-bytes unsafe memcpy
	coldSer := coldOn && !coldFree                        // binary marshal/unmarshal codec
	// spill: on CLOCK eviction, write the victim (value or tombstone) to the cold
	// tier BEFORE overwriting it, so a later re-reference is served from disk and a
	// dirty-but-evicted entry isn't lost before Commit reads it.
	spill := ""
	if coldFree {
		spill = "\t\t\tif c.cold != nil {\n" +
			"\t\t\t\tc.cold.Put(unsafe.Slice((*byte)(unsafe.Pointer(&e.key)), unsafe.Sizeof(e.key)), unsafe.Slice((*byte)(unsafe.Pointer(&e.value)), unsafe.Sizeof(e.value)))\n" +
			"\t\t\t}\n"
	} else if coldSer {
		spill = "\t\t\tif c.cold != nil {\n" +
			"\t\t\t\tc.cold.Put(unsafe.Slice((*byte)(unsafe.Pointer(&e.key)), unsafe.Sizeof(e.key)), marshalCold" + valueType + "(e.value))\n" +
			"\t\t\t}\n"
	}
	fmt.Fprintf(b, `func (c *%[1]s) Set(value %[3]s) {
	c.SetByKey(New%[2]s(value), value)
}

func (c *%[1]s) SetByKey(key %[2]s, value %[3]s) {
	if idx, ok := c.idxLookup(key); ok {
		e := &c.ring[idx]
		if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
			e.value = value
			atomic.StoreUint32(&e.referenced, 1)
			return
		}
	}
	for {
		hand := atomic.AddUint64(&c.hand, 1)
		idx := (hand - 1) %% c.capacity
		e := &c.ring[idx]
		if atomic.CompareAndSwapUint32(&e.inUse, 1, 0) {
			if atomic.LoadUint32(&e.referenced) == 1 {
				atomic.StoreUint32(&e.referenced, 0)
				atomic.StoreUint32(&e.inUse, 1)
				continue
			}
%[4]s			c.idxUnlink(e.key)
			e.key = key
			e.value = value
			atomic.StoreUint32(&e.referenced, 0)
			c.idxInsert(key, uint32(idx))
			atomic.StoreUint32(&e.inUse, 1)
			return
		}
		if atomic.LoadUint32(&e.inUse) == 0 {
			if atomic.CompareAndSwapUint32(&e.inUse, 0, 2) {
				e.key = key
				e.value = value
				atomic.StoreUint32(&e.referenced, 0)
				c.idxInsert(key, uint32(idx))
				atomic.AddUint64(&c.size, 1)
				atomic.StoreUint32(&e.inUse, 1)
				return
			}
		}
	}
}

`, spec.cacheType, spec.keyType, valueType, spill)

	if coldFree {
		// Cold-consult on hot miss: an evicted entry (spilled on eviction) is served
		// from Pebble (~8µs) instead of a ClickHouse round-trip (~1.9ms), then
		// promoted back into the hot ring. A cold tombstone round-trips as a value
		// with Tombstone=true, which the state-level Get treats as "absent".
		fmt.Fprintf(b, `func (c *%[1]s) Get(key %[2]s) (%[3]s, bool) {
	if idx, ok := c.idxLookup(key); ok {
		e := &c.ring[idx]
		if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
			atomic.StoreUint32(&e.referenced, 1)
			if c.metrics != nil {
				c.metrics.HotHits++
			}
			return e.value, true
		}
	}
	if c.cold != nil {
		// GetInto copies the stored bytes straight into v (a fixed-size value
		// whose layout matches the bytes written on eviction), avoiding the
		// per-hit []byte allocation that the value-returning cold.Get does. key is
		// copied to a local first: taking &key directly forces the key parameter
		// to the heap on EVERY Get (escape analysis is flow-insensitive), including
		// hot hits that never reach this cold branch. &k keeps the escape contained.
		k := key
		var v %[3]s
		if found, _ := c.cold.GetInto(unsafe.Slice((*byte)(unsafe.Pointer(&v)), unsafe.Sizeof(v)), unsafe.Slice((*byte)(unsafe.Pointer(&k)), unsafe.Sizeof(k))); found {
			c.SetByKey(key, v)
			if c.metrics != nil {
				c.metrics.ColdHits++
			}
			return v, true
		}
	}
	return %[3]s{}, false
}

`, spec.cacheType, spec.keyType, valueType)
	} else if coldSer {
		// Serialized cold-consult: pointer-bearing values can't use the zero-copy
		// GetInto memcpy, so a hot miss fetches the marshaled bytes from Pebble and
		// decodes them (one alloc per cold hit — still far cheaper than a ClickHouse
		// round-trip), then promotes the entry back into the hot ring.
		fmt.Fprintf(b, `func (c *%[1]s) Get(key %[2]s) (%[3]s, bool) {
	if idx, ok := c.idxLookup(key); ok {
		e := &c.ring[idx]
		if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
			atomic.StoreUint32(&e.referenced, 1)
			if c.metrics != nil {
				c.metrics.HotHits++
			}
			return e.value, true
		}
	}
	if c.cold != nil {
		k := key
		if data, found, _ := c.cold.Get(unsafe.Slice((*byte)(unsafe.Pointer(&k)), unsafe.Sizeof(k))); found {
			if v, ok := unmarshalCold%[3]s(data); ok {
				c.SetByKey(key, v)
				if c.metrics != nil {
					c.metrics.ColdHits++
				}
				return v, true
			}
		}
	}
	return %[3]s{}, false
}

`, spec.cacheType, spec.keyType, valueType)
	} else {
		fmt.Fprintf(b, `func (c *%[1]s) Get(key %[2]s) (%[3]s, bool) {
	idx, ok := c.idxLookup(key)
	if !ok {
		return %[3]s{}, false
	}
	e := &c.ring[idx]
	if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
		atomic.StoreUint32(&e.referenced, 1)
		if c.metrics != nil {
			c.metrics.HotHits++
		}
		return e.value, true
	}
	return %[3]s{}, false
}

`, spec.cacheType, spec.keyType, valueType)
	}

	if len(keyFields) > 0 {
		b.WriteString("func (c *")
		b.WriteString(spec.cacheType)
		b.WriteString(") GetByFields(")
		renderClockKeyParams(b, keyFields)
		b.WriteString(") (")
		b.WriteString(valueType)
		b.WriteString(", bool) {\n\treturn c.Get(")
		b.WriteString(spec.keyType)
		b.WriteString("{")
		for i, field := range keyFields {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(field.Name)
			b.WriteString(": ")
			b.WriteString(lowerFirst(field.Name))
		}
		b.WriteString("})\n}\n\n")
	}

	// coldDel mirrors a hard delete into the cold tier so a rolled-back key cannot
	// resurrect from disk on a later miss.
	coldDel := ""
	if coldOn {
		coldDel = "\t\t\tif c.cold != nil {\n" +
			"\t\t\t\tc.cold.Delete(unsafe.Slice((*byte)(unsafe.Pointer(&key)), unsafe.Sizeof(key)))\n" +
			"\t\t\t}\n"
	}
	fmt.Fprintf(b, `func (c *%[1]s) Delete(key %[2]s) bool {
	idx, ok := c.idxLookup(key)
	if !ok {
		return false
	}
	e := &c.ring[idx]
	if atomic.CompareAndSwapUint32(&e.inUse, 1, 0) {
		if e.key == key {
			c.idxUnlink(key)
%[4]s			e.key = %[2]s{}
			e.value = %[3]s{}
			atomic.StoreUint32(&e.referenced, 0)
			atomic.AddUint64(&c.size, ^uint64(0))
			return true
		}
		atomic.StoreUint32(&e.inUse, 1)
	}
	return false
}

func (c *%[1]s) Range(fn func(%[2]s, %[3]s) bool) {
	if fn == nil {
		return
	}
	limit := atomic.LoadUint64(&c.hand)
	if limit > c.capacity {
		limit = c.capacity
	}
	for i := uint64(0); i < limit; i++ {
		e := &c.ring[i]
		if atomic.LoadUint32(&e.inUse) == 1 {
			if !fn(e.key, e.value) {
				return
			}
		}
	}
}

func (c *%[1]s) AppendValues(dst []%[3]s) []%[3]s {
	if c == nil {
		return dst
	}
	if atomic.LoadUint64(&c.size) == 0 {
		return dst
	}
	limit := atomic.LoadUint64(&c.hand)
	if limit > c.capacity {
		limit = c.capacity
	}
	for i := 0; i < int(limit); i++ {
		e := &c.ring[i]
		if atomic.LoadUint32(&e.inUse) == 1 {
			dst = append(dst, e.value)
		}
	}
	return dst
}

func (c *%[1]s) Len() uint64 {
	return atomic.LoadUint64(&c.size)
}

`, spec.cacheType, spec.keyType, valueType, coldDel)
	if coldSer {
		renderColdCodec(b, spec)
	}
}

func renderCustomBatch(b *bytes.Buffer, spec hotStateSpec) {
	b.WriteString("type ")
	b.WriteString(spec.batchType)
	b.WriteString(" struct {\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(batchColumnType(field))
		b.WriteString("\n")
		if scratch := batchScratchField(field); scratch != "" {
			b.WriteString("\t")
			b.WriteString(scratch)
			b.WriteString(" ")
			b.WriteString(batchScratchType(field))
			b.WriteString("\n")
		}
	}
	b.WriteString("\tinput proto.Input\n}\n\n")

	b.WriteString("func New")
	b.WriteString(spec.batchType)
	b.WriteString("() *")
	b.WriteString(spec.batchType)
	b.WriteString(" {\n\tb := &")
	b.WriteString(spec.batchType)
	b.WriteString("{}\n")
	for _, field := range spec.table.Fields {
		for _, line := range batchInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tb.input = proto.Input{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(batchInputData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n\treturn b\n}\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") TableName() string { return ")
	b.WriteString(strconv.Quote(spec.table.Name))
	b.WriteString(" }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Rows() int { return ")
	b.WriteString(batchColumnRowsExpr(spec.table.Fields[0]))
	b.WriteString(" }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Reset() { b.input.Reset() }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Append(item ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(") {\n")
	for _, field := range spec.table.Fields {
		for _, line := range batchAppendLines(field, spec.table.IsEvent) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Inputs() proto.Input { return b.input }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Insert(ctx context.Context, conn *ch.Client, db string) error {\n\tif b.Rows() == 0 {\n\t\treturn nil\n\t}\n\treturn conn.Do(ctx, ch.Query{Body: fmt.Sprintf(")
	b.WriteString(strconv.Quote("INSERT INTO %s.%s " + customInsertColumnList(spec.table) + " VALUES"))
	// wait_for_async_insert MUST be 1: hot-state commits are read back on
	// prefetch/recovery/rollback. With wait=0 (fire-and-forget) a SELECT after
	// Commit can miss un-flushed rows, returning stale/partial state under load.
	b.WriteString(", quoteIdent(db), quoteIdent(b.TableName())), Input: b.input, Settings: []ch.Setting{{Key: \"async_insert\", Value: \"1\", Important: true}, {Key: \"wait_for_async_insert\", Value: \"1\", Important: true}}})\n}\n\n")
}

func renderClockRecover(b *bytes.Buffer, spec hotStateSpec) {
	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Recover(ctx context.Context, conn *ch.Client, db string) error {\n\trun := func(ctx context.Context, conn *ch.Client, bucket int, emit func(")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(")) error {\n\tvar (\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(resultColumnType(field))
		b.WriteString("\n")
	}
	b.WriteString("\t)\n")
	for _, field := range spec.table.Fields {
		for _, line := range resultInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tresults := proto.Results{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(resultData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn conn.Do(ctx, ch.Query{Body: fmt.Sprintf(")
	b.WriteString(strconv.Quote(recoverQuery(spec.table)))
	b.WriteString(", quoteIdent(db), quoteIdent(")
	b.WriteString(strconv.Quote(spec.table.Name))
	b.WriteString("), ")
	b.WriteString(recoverWhereExpr(spec.table))
	b.WriteString("), Result: results, OnResult: func(ctx context.Context, block proto.Block) error {\n\t\tfor i := 0; i < block.Rows; i++ {\n\t\t\temit(")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString("{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t\t\t")
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(resultValueExpr(field, spec.table.IsEvent))
		b.WriteString(",\n")
	}
	b.WriteString("\t\t\t})\n\t\t}\n\t\treturn nil\n\t}})\n\t}\n")
	if isPointerFreeEntity(spec.table) {
		b.WriteString("\tif c.cold != nil {\n\t\treturn recoverColdParallel(ctx, conn, recoveryBucketCount, c.cold, run, func(v ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(", put func(key, val []byte) error) error {\n\t\t\tk := New")
		b.WriteString(spec.keyType)
		b.WriteString("(v)\n\t\t\treturn put(unsafe.Slice((*byte)(unsafe.Pointer(&k)), unsafe.Sizeof(k)), unsafe.Slice((*byte)(unsafe.Pointer(&v)), unsafe.Sizeof(v)))\n\t\t})\n\t}\n")
	} else if isColdSerializableEntity(spec.table) {
		b.WriteString("\tif c.cold != nil {\n\t\treturn recoverColdParallel(ctx, conn, recoveryBucketCount, c.cold, run, func(v ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(", put func(key, val []byte) error) error {\n\t\t\tk := New")
		b.WriteString(spec.keyType)
		b.WriteString("(v)\n\t\t\treturn put(unsafe.Slice((*byte)(unsafe.Pointer(&k)), unsafe.Sizeof(k)), marshalCold")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("(v))\n\t\t})\n\t}\n")
	}
	b.WriteString("\tfor bucket := 0; bucket < recoveryBucketCount; bucket++ {\n\t\tif err := run(ctx, conn, bucket, c.Set); err != nil {\n\t\t\treturn err\n\t\t}\n\t}\n\treturn nil\n}\n\n")
}

func renderHotStateType(b *bytes.Buffer, specs []hotStateSpec) {
	b.WriteString("type HotState struct {\n")
	for _, spec := range specs {
		resolverType := spec.table.GoTypeName + "BatchResolver"
		b.WriteString("\t")
		b.WriteString(spec.baseName)
		b.WriteString(" *")
		b.WriteString(spec.cacheType)
		b.WriteString("\n")

		b.WriteString("\t")
		b.WriteString(spec.baseName)
		b.WriteString("Resolver *")
		b.WriteString(resolverType)
		b.WriteString("\n")

		if !spec.table.IsEvent {
			b.WriteString("\tdirty")
			b.WriteString(spec.baseName)
			b.WriteString(" map[")
			b.WriteString(spec.keyType)
			b.WriteString("]struct{}\n")
		}
	}
	b.WriteString("\tmu sync.Mutex\n")
	b.WriteString("\t// coldAuthoritative is set when the cold tier was opened against an empty\n")
	b.WriteString("\t// ClickHouse (from-genesis backfill): a hot+cold miss is then provably new,\n")
	b.WriteString("\t// so the lazy state Get skips the ClickHouse point-SELECT entirely.\n")
	b.WriteString("\tcoldAuthoritative bool\n")
	b.WriteString("\t// prefetchEnabled turns on the two-pass batch prefetch (--prefetch): each\n")
	b.WriteString("\t// block is dispatched once in recordMode to collect the read-set, resolved in\n")
	b.WriteString("\t// one round-trip per entity, then dispatched again for real against a warm cache.\n")
	b.WriteString("\tprefetchEnabled bool\n")
	b.WriteString("\t// recordMode is set for the duration of a prefetch dry-run pass. While set,\n")
	b.WriteString("\t// the lazy state Get queues misses instead of resolving them synchronously,\n")
	b.WriteString("\t// and Save is suppressed (the dry run has no committed side effects).\n")
	b.WriteString("\trecordMode bool\n")
	b.WriteString("}\n\n")

	b.WriteString("func NewHotState(capacity uint64) *HotState {\n\tif capacity == 0 {\n\t\tcapacity = DefaultClockCacheCapacity\n\t}\n")
	b.WriteString("\tstate := &HotState{\n")
	for _, spec := range specs {
		b.WriteString("\t\t")
		b.WriteString(spec.baseName)
		b.WriteString(": New")
		b.WriteString(spec.cacheType)
		b.WriteString("(capacity),\n")
		if !spec.table.IsEvent {
			b.WriteString("\t\tdirty")
			b.WriteString(spec.baseName)
			b.WriteString(": make(map[")
			b.WriteString(spec.keyType)
			b.WriteString("]struct{}),\n")
		}
	}
	b.WriteString("\t}\n")
	for _, spec := range specs {
		resolverType := spec.table.GoTypeName + "BatchResolver"
		b.WriteString("\tstate.")
		b.WriteString(spec.baseName)
		b.WriteString("Resolver = New")
		b.WriteString(resolverType)
		b.WriteString("(state.")
		b.WriteString(spec.baseName)
		b.WriteString(")\n")
	}
	b.WriteString("\treturn state\n}\n\n")

	// EnableColdCache / CloseColdCache: attach the Pebble cold tier to every
	// pointer-free entity. authoritative=true (from-genesis, empty ClickHouse) lets
	// the lazy Get skip ClickHouse on a hot+cold miss. Default-off — callers that
	// never enable it get byte-for-byte the prior behaviour.
	var coldSpecs []hotStateSpec
	for _, spec := range specs {
		if entityUsesCold(spec.table) {
			coldSpecs = append(coldSpecs, spec)
		}
	}
	if len(coldSpecs) == 0 {
		b.WriteString("func (s *HotState) ColdAuthoritative() bool { return false }\n\n")
		b.WriteString("func (s *HotState) EnableColdCache(dir string, authoritative bool, cacheBytes int64, memTableBytes uint64) error {\n\treturn nil\n}\n\n")
		b.WriteString("func (s *HotState) CloseColdCache() error {\n\treturn nil\n}\n\n")
	} else {
		b.WriteString("func (s *HotState) ColdAuthoritative() bool {\n\treturn s != nil && s.coldAuthoritative\n}\n\n")
		b.WriteString("func (s *HotState) EnableColdCache(dir string, authoritative bool, cacheBytes int64, memTableBytes uint64) error {\n")
		b.WriteString("\tif s == nil {\n\t\treturn nil\n\t}\n")
		b.WriteString("\tvar err error\n")
		for _, spec := range coldSpecs {
			b.WriteString("\tif s.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold, err = coldcache.Open(filepath.Join(dir, ")
			b.WriteString(strconv.Quote(spec.baseName))
			b.WriteString("), cacheBytes, memTableBytes); err != nil {\n\t\treturn err\n\t}\n")
		}
		b.WriteString("\ts.coldAuthoritative = authoritative\n")
		b.WriteString("\treturn nil\n}\n\n")

		b.WriteString("func (s *HotState) CloseColdCache() error {\n")
		b.WriteString("\tif s == nil {\n\t\treturn nil\n\t}\n")
		b.WriteString("\tvar firstErr error\n")
		for _, spec := range coldSpecs {
			b.WriteString("\tif s.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold != nil {\n\t\tif e := s.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold.Close(); e != nil && firstErr == nil {\n\t\t\tfirstErr = e\n\t\t}\n\t\ts.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold = nil\n\t}\n")
		}
		b.WriteString("\ts.coldAuthoritative = false\n")
		b.WriteString("\treturn firstErr\n}\n\n")
	}

	b.WriteString("func (s *HotState) Recover(ctx context.Context, conn *ch.Client, db string) error {\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tif err := s.")
		b.WriteString(spec.baseName)
		b.WriteString(".Recover(ctx, conn, db); err != nil {\n\t\treturn err\n\t}\n")
	}
	if len(coldSpecs) > 0 {
		b.WriteString("\tif ")
		for i, spec := range coldSpecs {
			if i > 0 {
				b.WriteString(" || ")
			}
			b.WriteString("s.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold != nil")
		}
		b.WriteString(" {\n\t\ts.coldAuthoritative = true\n\t}\n")
	}
	b.WriteString("\treturn nil\n}\n\n")

	// Prefetch (--prefetch) plumbing. EnablePrefetch turns on the two-pass batch
	// prefetch; SetRecordMode brackets the dry-run pass; ResolveAllPending drains
	// every entity resolver's queued misses in one round-trip each. Default-off:
	// callers that never enable it get byte-for-byte the prior lazy behaviour.
	b.WriteString("func (s *HotState) EnablePrefetch(enabled bool) {\n\tif s != nil {\n\t\ts.prefetchEnabled = enabled\n\t}\n}\n\n")
	b.WriteString("func (s *HotState) PrefetchEnabled() bool {\n\treturn s != nil && s.prefetchEnabled\n}\n\n")
	b.WriteString("func (s *HotState) SetRecordMode(on bool) {\n\tif s != nil {\n\t\ts.recordMode = on\n\t}\n}\n\n")
	b.WriteString("func (s *HotState) RecordMode() bool {\n\treturn s != nil && s.recordMode\n}\n\n")

	// ResolveAllPending flushes every resolver's queued misses to ClickHouse in a
	// single round-trip per entity (vs the lazy path's one round-trip per missing
	// key). A resolver with no queued misses early-returns, so this is cheap when a
	// block touched only a subset of entities.
	b.WriteString("func (s *HotState) ResolveAllPending(ctx context.Context, conn *ch.Client, db string) error {\n")
	b.WriteString("\tif s == nil || conn == nil {\n\t\treturn nil\n\t}\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tif err := s.")
		b.WriteString(spec.baseName)
		b.WriteString("Resolver.Resolve(ctx, conn, db); err != nil {\n\t\treturn err\n\t}\n")
	}
	b.WriteString("\treturn nil\n}\n\n")

	// Generate Update methods
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("func (s *HotState) Update")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("(value ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(") {\n")
		b.WriteString("\ts.mu.Lock()\n")
		b.WriteString("\tdefer s.mu.Unlock()\n")
		b.WriteString("\ts.")
		b.WriteString(spec.baseName)
		b.WriteString(".Set(value)\n")
		b.WriteString("\ts.dirty")
		b.WriteString(spec.baseName)
		b.WriteString("[New")
		b.WriteString(spec.keyType)
		b.WriteString("(value)] = struct{}{}\n")
		b.WriteString("}\n\n")
	}

	// Generate Commit method
	b.WriteString("func (s *HotState) Commit(ctx context.Context, conn *ch.Client, db string) error {\n")
	b.WriteString("\ts.mu.Lock()\n")
	b.WriteString("\tdefer s.mu.Unlock()\n")
	b.WriteString("\tif conn == nil {\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\t\tclear(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(")\n")
	}
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tif len(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(") > 0 {\n")
		b.WriteString("\t\tbatch := New")
		b.WriteString(spec.batchType)
		b.WriteString("()\n")
		b.WriteString("\t\tfor key := range s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(" {\n")
		b.WriteString("\t\t\tif val, ok := s.")
		b.WriteString(spec.baseName)
		b.WriteString(".Get(key); ok {\n")
		b.WriteString("\t\t\t\tbatch.Append(val)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tif err := batch.Insert(ctx, conn, db); err != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tclear(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(")\n")
		b.WriteString("\t}\n")
	}
	b.WriteString("\treturn nil\n}\n")

	// Generate Restore methods for journal rollback
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("func (s *HotState) Restore")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("(key ")
		b.WriteString(spec.keyType)
		b.WriteString(", value ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(", had bool) {\n")
		b.WriteString("\ts.mu.Lock()\n")
		b.WriteString("\tdefer s.mu.Unlock()\n")
		b.WriteString("\tif had {\n")
		b.WriteString("\t\ts.")
		b.WriteString(spec.baseName)
		b.WriteString(".SetByKey(key, value)\n")
		b.WriteString("\t\ts.dirty")
		b.WriteString(spec.baseName)
		b.WriteString("[key] = struct{}{}\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\ts.")
		b.WriteString(spec.baseName)
		b.WriteString(".Delete(key)\n")
		b.WriteString("\tdelete(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(", key)\n")
		b.WriteString("}\n\n")
	}
}

func renderHotStateHelpers(b *bytes.Buffer, tables []customTableSpec, events []eventSpec) {
	// Shared FNV-1a byte fold used by every clock cache's flat index (A3). The
	// index is a pointer-free open-chained hash over an arena (buckets []int32 head
	// + next []int32 chain), so the GC scans two flat integer slices instead of the
	// millions of boxed interface objects a sync.Map[key]idx allocated.
	b.WriteString(`
// BatchResolverMetrics are cumulative until SnapshotAndResetMetrics is called.
// Resolver access follows the processor's single-owner state contract.
type BatchResolverMetrics struct {
	HotHits      uint64
	ColdHits     uint64
	DBFallbacks  uint64
	QueuedMisses uint64
	UniqueMisses uint64
	RoundTrips   uint64
	ResolveNanos uint64
}

func clockHashWord(seed, word uint64) uint64 {
	return (seed ^ word) * 1099511628211
}

func clockHash20(seed uint64, b []byte) uint64 {
	h := clockHashWord(seed, binary.LittleEndian.Uint64(b[0:8]))
	h = clockHashWord(h, binary.LittleEndian.Uint64(b[8:16]))
	return clockHashWord(h, uint64(binary.LittleEndian.Uint32(b[16:20])))
}

func clockHash32(seed uint64, b []byte) uint64 {
	h := clockHashWord(seed, binary.LittleEndian.Uint64(b[0:8]))
	h = clockHashWord(h, binary.LittleEndian.Uint64(b[8:16]))
	h = clockHashWord(h, binary.LittleEndian.Uint64(b[16:24]))
	return clockHashWord(h, binary.LittleEndian.Uint64(b[24:32]))
}

func clockHashBytes(seed uint64, b []byte) uint64 {
	h := seed
	for _, x := range b {
		h ^= uint64(x)
		h *= 1099511628211
	}
	return h
}
`)
	if customTablesUseBool(tables) {
		b.WriteString("\nfunc hotStateBool(v bool) uint8 {\n\tif v {\n\t\treturn 1\n\t}\n\treturn 0\n}\n")
		b.WriteString("\nfunc hotStateBoolSQL(v bool) string {\n\tif v {\n\t\treturn \"1\"\n\t}\n\treturn \"0\"\n}\n")
	}
	if customTablesUseUint256(tables) || customTablesUseUint256Slice(tables) ||
		eventsUseUint256(events) || eventsUseUint256Slice(events) {
		b.WriteString(`
func hotStateUInt256(v uint256.Int) proto.UInt256 {
	return proto.UInt256{
		Low:  proto.UInt128{Low: v[0], High: v[1]},
		High: proto.UInt128{Low: v[2], High: v[3]},
	}
}

func hotStateUint256(v proto.UInt256) uint256.Int {
	return uint256.Int{v.Low.Low, v.Low.High, v.High.Low, v.High.High}
}
`)
	}
	if customTablesUseDecimal(tables) {
		b.WriteString(`
func hotStateDecimalToDecimal256(d decimal.Decimal) protomath.Decimal256 {
	out, _ := protomath.FromDecimal256ScaledBigInt(d.Shift(18).BigInt())
	return out
}

func hotStateDecimalFromDecimal256(v protomath.Decimal256) decimal.Decimal {
	return decimal.NewFromBigInt(v.ScaledBig(), -18)
}
`)
	}
	if customTablesUseType(tables, "protomath.Decimal256") {
		b.WriteString(`
type decimal256Col struct {
	proto.ColDecimal256
}

func (c *decimal256Col) Type() proto.ColumnType {
	return proto.ColumnType("Decimal(76, 18)")
}
`)
	}
	if customTablesUseHashSlice(tables) {
		b.WriteString(`
func hotStateHashSliceBytes(values []common.Hash, scratch [][]byte) [][]byte {
	scratch = scratch[:0]
	for _, value := range values {
		scratch = append(scratch, value.Bytes())
	}
	return scratch
}

func hotStateHashSlice(values [][]byte) []common.Hash {
	out := make([]common.Hash, 0, len(values))
	for _, value := range values {
		out = append(out, common.BytesToHash(value))
	}
	return out
}
`)
	}
	if customTablesUseUint256Slice(tables) || eventsUseUint256Slice(events) {
		b.WriteString(`
func hotStateUInt256Slice(values []uint256.Int, scratch []proto.UInt256) []proto.UInt256 {
	scratch = scratch[:0]
	for _, value := range values {
		scratch = append(scratch, hotStateUInt256(value))
	}
	return scratch
}

func hotStateUint256Slice(values []proto.UInt256) []uint256.Int {
	out := make([]uint256.Int, 0, len(values))
	for _, value := range values {
		out = append(out, hotStateUint256(value))
	}
	return out
}
`)
	}
}

func renderClockKeyParams(b *bytes.Buffer, fields []customFieldSpec) {
	for i, field := range fields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(lowerFirst(field.Name))
		b.WriteString(" ")
		b.WriteString(field.Type)
	}
}

func hotStateSpecs(tables []customTableSpec) []hotStateSpec {
	used := make(map[string]int)
	specs := make([]hotStateSpec, 0, len(tables))
	for _, table := range tables {
		var base string
		if table.BaseName != "" {
			base = uniqueExported(used, table.BaseName)
		} else {
			base = uniqueExported(used, customClockBaseName(table.GoTypeName))
		}
		specs = append(specs, hotStateSpec{
			table:     table,
			baseName:  base,
			keyType:   base + "ClockKey",
			entryType: base + "ClockEntry",
			cacheType: base + "ClockCache",
			batchType: table.GoTypeName + "Batch",
		})
	}
	return specs
}

func customClockBaseName(typeName string) string {
	name := strings.TrimPrefix(customTableEntityName(typeName), "Memory")
	return pluralizeGoName(name)
}

func pluralizeGoName(name string) string {
	switch {
	case name == "":
		return "Entities"
	case strings.HasSuffix(name, "s"), strings.HasSuffix(name, "S"):
		return name
	case strings.HasSuffix(name, "y"):
		return strings.TrimSuffix(name, "y") + "ies"
	case strings.HasSuffix(name, "Y"):
		return strings.TrimSuffix(name, "Y") + "ies"
	default:
		return name + "s"
	}
}

func lowerFirst(name string) string {
	if name == "" {
		return "value"
	}
	if name == strings.ToUpper(name) {
		return strings.ToLower(name)
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func sortedImportKeys(imports map[string]string) []string {
	keys := make([]string, 0, len(imports))
	for key := range imports {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func batchColumnField(field customFieldSpec) string {
	return "col" + field.Name
}

func batchScratchField(field customFieldSpec) string {
	switch field.Type {
	case "[]common.Hash", "[]uint256.Int":
		return "scratch" + field.Name
	default:
		return ""
	}
}

func batchScratchType(field customFieldSpec) string {
	switch field.Type {
	case "[]common.Hash":
		return "[][]byte"
	case "[]uint256.Int":
		return "[]proto.UInt256"
	default:
		return ""
	}
}

// memoryGoType returns the in-memory Go type for a hot-state value-struct field,
// which may differ from the schema/source type to keep the rings pointer-free
// (A2). Timestamps are stored as int64 unix-millis in memory — the ClickHouse
// column stays DateTime64(3, 'UTC') — so MemoryUserPosition et al. carry no
// *time.Location pointer and the GC skips the whole ring backing array on every
// mark, instead of scanning all N entries. Conversions happen at Append/Recover
// (see batchAppendLines / resultValueExpr) and at assignment (state.go Save).
func memoryGoType(field customFieldSpec, isEvent bool) string {
	// Event value-structs embed EventMeta (shared with the ingestion/handler layer,
	// where BlockTimestamp is a time.Time), so they keep time.Time. Only the derived
	// entity rings (UserPositions et al.) — the ones that grow to capacity — are
	// converted to int64 to make their backing arrays pointer-free.
	if isEvent {
		return field.Type
	}
	switch field.Type {
	case "time.Time":
		return "int64"
	default:
		return field.Type
	}
}

func batchColumnType(field customFieldSpec) string {
	switch field.Type {
	case "bool", "uint8":
		return "proto.ColUInt8"
	case "uint16":
		return "proto.ColUInt16"
	case "uint32":
		return "proto.ColUInt32"
	case "uint", "uint64":
		return "proto.ColUInt64"
	case "int8":
		return "proto.ColInt8"
	case "int16":
		return "proto.ColInt16"
	case "int32":
		return "proto.ColInt32"
	case "int", "int64":
		return "proto.ColInt64"
	case "float32":
		return "proto.ColFloat32"
	case "float64":
		return "proto.ColFloat64"
	case "string", "[]byte":
		return "proto.ColStr"
	case "time.Time":
		return "proto.ColDateTime64"
	case "common.Address", "common.Hash":
		return "proto.ColFixedStr"
	case "uint256.Int":
		return "proto.ColUInt256"
	case "decimal.Decimal":
		return "decimal256Col"
	case "protomath.Decimal256":
		return "decimal256Col"
	case "[]common.Hash":
		return "*proto.ColArr[[]byte]"
	case "[]uint256.Int":
		return "*proto.ColArr[proto.UInt256]"
	case "[]string":
		return "*proto.ColArr[string]"
	default:
		return "proto.ColStr"
	}
}

func resultColumnType(field customFieldSpec) string {
	return batchColumnType(field)
}

func batchInitLines(field customFieldSpec) []string {
	return initLines("b.", field)
}

func resultInitLines(field customFieldSpec) []string {
	if field.Type == "decimal.Decimal" {
		return nil
	}
	return initLines("", field)
}

func initLines(prefix string, field customFieldSpec) []string {
	col := prefix + batchColumnField(field)
	switch field.Type {
	case "common.Address":
		return []string{col + ".SetSize(20)"}
	case "common.Hash":
		return []string{col + ".SetSize(32)"}
	case "time.Time":
		return []string{col + ".WithPrecision(proto.Precision(3))", col + ".WithLocation(time.UTC)"}
	case "[]common.Hash":
		return []string{col + " = (&proto.ColFixedStr{Size: 32}).Array()"}
	case "[]uint256.Int":
		return []string{col + " = new(proto.ColUInt256).Array()"}
	case "[]string":
		return []string{col + " = new(proto.ColStr).Array()"}
	default:
		return nil
	}
}

func batchInputData(field customFieldSpec) string {
	col := "b." + batchColumnField(field)
	switch field.Type {
	case "decimal.Decimal", "protomath.Decimal256":
		return "&" + col
	case "[]common.Hash", "[]uint256.Int", "[]string":
		return col
	default:
		return "&" + col
	}
}

func resultData(field customFieldSpec) string {
	col := batchColumnField(field)
	switch field.Type {
	case "decimal.Decimal", "protomath.Decimal256":
		return "&" + col
	case "[]common.Hash", "[]uint256.Int", "[]string":
		return col
	default:
		return "&" + col
	}
}

func batchColumnRowsExpr(field customFieldSpec) string {
	col := "b." + batchColumnField(field)
	if strings.HasPrefix(field.Type, "[]") {
		return col + ".Rows()"
	}
	return col + ".Rows()"
}

func batchAppendLines(field customFieldSpec, isEvent bool) []string {
	col := "b." + batchColumnField(field)
	value := "item." + field.Name
	if !isEvent && field.Type == "time.Time" {
		// In-memory value is int64 unix-millis (A2); the DateTime64(3) column's raw
		// units are also milliseconds, so append the raw value directly — no
		// time.Time is constructed on the hot insert path.
		return []string{col + ".AppendRaw(proto.DateTime64(" + value + "))"}
	}
	switch field.Type {
	case "common.Address", "common.Hash":
		return []string{col + ".Append(" + value + ".Bytes())"}
	case "bool":
		return []string{col + ".Append(hotStateBool(" + value + "))"}
	case "[]byte":
		return []string{col + ".AppendBytes(" + value + ")"}
	case "decimal.Decimal":
		return []string{col + ".Append(hotStateDecimalToDecimal256(" + value + ").Proto())"}
	case "protomath.Decimal256":
		return []string{col + ".Append(" + value + ".Proto())"}
	case "uint256.Int":
		return []string{col + ".Append(hotStateUInt256(" + value + "))"}
	case "[]common.Hash":
		return []string{col + ".Append(hotStateHashSliceBytes(" + value + ", b." + batchScratchField(field) + "))"}
	case "[]uint256.Int":
		return []string{col + ".Append(hotStateUInt256Slice(" + value + ", b." + batchScratchField(field) + "))"}
	default:
		return []string{col + ".Append(" + value + ")"}
	}
}

func resultValueExpr(field customFieldSpec, isEvent bool) string {
	col := batchColumnField(field)
	if !isEvent && field.Type == "time.Time" {
		// Recover path (cold): read the DateTime64 instant back as int64 unix-millis
		// to match the in-memory representation (A2). UnixMilli is timezone-
		// independent, so it round-trips the millisecond raw value exactly.
		return col + ".Row(i).UnixMilli()"
	}
	switch field.Type {
	case "common.Address":
		return "common.BytesToAddress(" + col + ".Row(i))"
	case "common.Hash":
		return "common.BytesToHash(" + col + ".Row(i))"
	case "bool":
		return col + ".Row(i) != 0"
	case "[]byte":
		return "append([]byte(nil), " + col + ".RowBytes(i)...)"
	case "decimal.Decimal":
		return "hotStateDecimalFromDecimal256(protomath.Decimal256(" + col + ".Row(i)))"
	case "protomath.Decimal256":
		return "protomath.Decimal256(" + col + ".Row(i))"
	case "uint256.Int":
		return "hotStateUint256(" + col + ".Row(i))"
	case "[]common.Hash":
		return "hotStateHashSlice(" + col + ".Row(i))"
	case "[]uint256.Int":
		return "hotStateUint256Slice(" + col + ".Row(i))"
	default:
		return col + ".Row(i)"
	}
}

func customInsertColumnList(table customTableSpec) string {
	columns := make([]string, 0, len(table.Columns))
	for _, column := range table.Columns {
		columns = append(columns, quoteSQLIdent(column.Name))
	}
	return "(" + strings.Join(columns, ", ") + ")"
}

func recoverQuery(table customTableSpec) string {
	q := func(col string) string { return "`t`." + quoteSQLIdent(col) }
	selects := make([]string, 0, len(table.Fields))
	for _, field := range table.Fields {
		selects = append(selects, q(field.ColumnName)+" AS "+quoteSQLIdent(field.ColumnName))
	}
	orderBy := make([]string, 0, len(table.PrimaryKey)+3)
	for _, k := range table.PrimaryKey {
		orderBy = append(orderBy, q(k)+" DESC")
	}
	orderBy = append(orderBy, q("block_number")+" DESC", q("transaction_index")+" DESC", q("log_index")+" DESC")
	limitBy := make([]string, 0, len(table.PrimaryKey))
	for _, k := range table.PrimaryKey {
		limitBy = append(limitBy, q(k))
	}
	return "SELECT " + strings.Join(selects, ", ") + " FROM %s.%s AS `t` WHERE %s ORDER BY " + strings.Join(orderBy, ", ") + " LIMIT 1 BY " + strings.Join(limitBy, ", ") + " SETTINGS optimize_read_in_order = 1"
}

func recoverWhereExpr(table customTableSpec) string {
	base := recoverBucketWhereExpr(table)
	for _, field := range table.Fields {
		if field.ColumnName == "updated_at_block" {
			return base + " + recoveryRecencyClause()"
		}
	}
	return base
}

func recoverBucketWhereExpr(table customTableSpec) string {
	if len(table.PrimaryKey) == 0 {
		return strconv.Quote("1")
	}
	firstKey := table.PrimaryKey[0]
	for _, field := range table.Fields {
		if field.ColumnName != firstKey {
			continue
		}
		if size, ok := fixedStringColumnSize(field.ColumnType); ok {
			return fmt.Sprintf("recoveryFixedStringRange(%s, bucket, %d)", strconv.Quote("`t`."+quoteSQLIdent(firstKey)), size)
		}
		break
	}
	q := func(col string) string { return "`t`." + quoteSQLIdent(col) }
	hashCols := make([]string, 0, len(table.PrimaryKey))
	for _, k := range table.PrimaryKey {
		hashCols = append(hashCols, q(k))
	}
	return "fmt.Sprintf(" + strconv.Quote("cityHash64("+strings.Join(hashCols, ", ")+") %% %d = %d") + ", recoveryBucketCount, bucket)"
}

func fixedStringColumnSize(chType string) (int, bool) {
	const prefix = "FixedString("
	if !strings.HasPrefix(chType, prefix) || !strings.HasSuffix(chType, ")") {
		return 0, false
	}
	n, err := strconv.Atoi(strings.TrimSuffix(strings.TrimPrefix(chType, prefix), ")"))
	if err != nil || n <= 0 {
		return 0, false
	}
	return n, true
}

func quotedColumns(columns []string) []string {
	out := make([]string, 0, len(columns))
	for _, column := range columns {
		out = append(out, quoteSQLIdent(column))
	}
	return out
}

func customTablesUseDecimal(tables []customTableSpec) bool {
	return customTablesUseType(tables, "decimal.Decimal")
}

func customTablesUseBool(tables []customTableSpec) bool {
	return customTablesUseType(tables, "bool")
}

func customTablesUseUint256(tables []customTableSpec) bool {
	return customTablesUseType(tables, "uint256.Int")
}

func customTablesUseHashSlice(tables []customTableSpec) bool {
	return customTablesUseType(tables, "[]common.Hash")
}

func customTablesUseUint256Slice(tables []customTableSpec) bool {
	return customTablesUseType(tables, "[]uint256.Int")
}

func eventsUseUint256(events []eventSpec) bool {
	return eventsUseType(events, "uint256.Int")
}

func eventsUseUint256Slice(events []eventSpec) bool {
	return eventsUseType(events, "[]uint256.Int")
}

func eventsUseType(events []eventSpec, typ string) bool {
	for _, ev := range events {
		for _, arg := range ev.Args {
			if arg.GoType == typ {
				return true
			}
		}
	}
	return false
}

func customTablesUseType(tables []customTableSpec, typ string) bool {
	for _, table := range tables {
		for _, field := range table.Fields {
			if field.Type == typ {
				return true
			}
		}
	}
	return false
}

// notFlatType reports whether a Go type string carries a pointer/slice/map/string
// (or time.Time), disqualifying it from the zero-transformation unsafe memcpy used
// by the pointer-free cold path, and (for keys) from the cold tier entirely.
func notFlatType(t string) bool {
	return strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "*") ||
		strings.HasPrefix(t, "map[") || strings.Contains(t, "string") ||
		t == "time.Time"
}

// isPointerFreeEntity reports whether the entity's in-memory value AND key are
// free of pointers/slices/strings, so they can be stored in the Pebble cold tier
// as raw bytes via unsafe memcpy (zero-transformation). Slice-bearing entities
// (e.g. Array(UInt256) payouts, Array(FixedString(32)) question_ids) are excluded
// and keep the ClickHouse-fallback lazy-load path. Note: memoryGoType maps
// time.Time -> int64 for non-event entities, so timestamps don't disqualify them.
func isPointerFreeEntity(table customTableSpec) bool {
	for _, field := range table.Fields {
		if notFlatType(memoryGoType(field, table.IsEvent)) {
			return false
		}
	}
	for _, field := range table.keyFields() {
		if notFlatType(field.Type) {
			return false
		}
	}
	return true
}

// coldFieldEncodable reports whether a field's (memory-resolved) Go type can be
// encoded by the generated binary cold codec: fixed scalars, fixed-size byte
// arrays (common.Hash/common.Address/uint256.Int), and slices whose elements are
// fixed-size byte arrays. Strings, decimals, maps and structs are NOT encodable —
// an entity with such a field stays on the ClickHouse-fallback lazy-load path.
func coldFieldEncodable(field customFieldSpec, isEvent bool) bool {
	switch memoryGoType(field, isEvent) {
	case "bool", "uint8", "int8", "uint16", "int16", "uint32", "int32",
		"uint", "int", "uint64", "int64":
		return true
	case "common.Hash", "common.Address", "uint256.Int":
		return true
	case "[]common.Hash", "[]uint256.Int", "[]common.Address":
		return true
	}
	return false
}

// isColdSerializableEntity reports whether a pointer-BEARING entity can still use
// the Pebble cold tier via a generated marshal/unmarshal codec (its only pointers
// are slices of fixed-size elements). The key must be pointer-free because cold
// keys are always encoded via unsafe memcpy; values are encoded field-by-field.
// This lets slice-bearing entities (Condition's []uint256.Int payouts, Market's
// []common.Hash question_ids) avoid the per-miss ClickHouse SELECT storm.
func isColdSerializableEntity(table customTableSpec) bool {
	for _, field := range table.keyFields() {
		if notFlatType(field.Type) {
			return false
		}
	}
	for _, field := range table.Fields {
		if !coldFieldEncodable(field, table.IsEvent) {
			return false
		}
	}
	return true
}

// entityUsesCold reports whether a (non-event) entity participates in the Pebble
// cold tier — either as a pointer-free value (raw-bytes memcpy) or a serializable
// one (binary codec). Events are append-only (no lazy Get-by-key), so they never
// need it.
func entityUsesCold(table customTableSpec) bool {
	return !table.IsEvent && (isPointerFreeEntity(table) || isColdSerializableEntity(table))
}

// customTablesUseColdCache reports whether any entity can use the cold tier;
// drives the "unsafe" + "path/filepath" imports in the generated hot state.
func customTablesUseColdCache(tables []customTableSpec) bool {
	for _, table := range tables {
		if entityUsesCold(table) {
			return true
		}
	}
	return false
}

// coldFixedWidth returns the on-wire byte width of a fixed-size resolved Go type
// (scalar or [N]byte array), or 0 for slices (variable length). Used to size
// decode bounds checks and the slice-element sanity cap.
func coldFixedWidth(goType string) int {
	switch goType {
	case "bool", "uint8", "int8":
		return 1
	case "uint16", "int16":
		return 2
	case "uint32", "int32":
		return 4
	case "uint", "int", "uint64", "int64":
		return 8
	case "common.Hash":
		return 32
	case "common.Address":
		return 20
	case "uint256.Int":
		return 32
	}
	return 0
}

// coldSliceElem maps a slice element type to its resolved Go element type for the
// types the cold codec supports ([]common.Hash, []uint256.Int, []common.Address).
// Returns ("", false) for unsupported element types.
func coldSliceElem(goType string) (string, bool) {
	switch goType {
	case "[]common.Hash":
		return "common.Hash", true
	case "[]uint256.Int":
		return "uint256.Int", true
	case "[]common.Address":
		return "common.Address", true
	}
	return "", false
}

// coldEncodeExpr returns a Go statement that appends the encoding of expression
// `e` (of resolved Go type `t`) to the []byte `b`. Only valid for fixed types.
func coldEncodeExpr(e, t string) string {
	switch t {
	case "bool":
		return "if " + e + " { b = append(b, 1) } else { b = append(b, 0) }"
	case "uint8", "int8":
		return "b = append(b, byte(" + e + "))"
	case "uint16", "int16":
		return "b = binary.LittleEndian.AppendUint16(b, uint16(" + e + "))"
	case "uint32", "int32":
		return "b = binary.LittleEndian.AppendUint32(b, uint32(" + e + "))"
	case "uint", "int", "uint64", "int64":
		return "b = binary.LittleEndian.AppendUint64(b, uint64(" + e + "))"
	case "common.Hash", "common.Address":
		return "b = append(b, " + e + "[:]...)"
	case "uint256.Int":
		return "{ _x := " + e + ".Bytes32(); b = append(b, _x[:]...) }"
	}
	return ""
}

// coldDecodeAssign returns Go statements that read one value of resolved Go type
// `t` from data[off:] into the lvalue `dst`, advancing off, with a bounds guard
// that returns (zero, false) on truncation. Only valid for fixed types.
func coldDecodeAssign(dst, t string) []string {
	w := coldFixedWidth(t)
	switch t {
	case "bool":
		return []string{"if off+1 > len(data) { return v, false }", dst + " = data[off] != 0", "off++"}
	case "uint8":
		return []string{"if off+1 > len(data) { return v, false }", dst + " = uint8(data[off])", "off++"}
	case "int8":
		return []string{"if off+1 > len(data) { return v, false }", dst + " = int8(data[off])", "off++"}
	case "uint16":
		return []string{"if off+2 > len(data) { return v, false }", dst + " = binary.LittleEndian.Uint16(data[off:])", "off += 2"}
	case "int16":
		return []string{"if off+2 > len(data) { return v, false }", dst + " = int16(binary.LittleEndian.Uint16(data[off:]))", "off += 2"}
	case "uint32":
		return []string{"if off+4 > len(data) { return v, false }", dst + " = binary.LittleEndian.Uint32(data[off:])", "off += 4"}
	case "int32":
		return []string{"if off+4 > len(data) { return v, false }", dst + " = int32(binary.LittleEndian.Uint32(data[off:]))", "off += 4"}
	case "uint", "uint64":
		return []string{"if off+8 > len(data) { return v, false }", dst + " = binary.LittleEndian.Uint64(data[off:])", "off += 8"}
	case "int", "int64":
		return []string{"if off+8 > len(data) { return v, false }", dst + " = int64(binary.LittleEndian.Uint64(data[off:]))", "off += 8"}
	case "common.Hash", "common.Address":
		return []string{
			fmt.Sprintf("if off+%d > len(data) { return v, false }", w),
			fmt.Sprintf("copy(%s[:], data[off:off+%d])", dst, w),
			fmt.Sprintf("off += %d", w),
		}
	case "uint256.Int":
		return []string{"if off+32 > len(data) { return v, false }", dst + ".SetBytes32(data[off:off+32])", "off += 32"}
	}
	return nil
}

// renderColdCodec emits marshalCold<T>/unmarshalCold<T> for a serializable
// (pointer-bearing) entity: a compact, deterministic binary encoding (LE
// scalars, raw bytes for Hash/Address/uint256, uvarint-length-prefixed slices,
// Tombstone trailer). Used by the spill/Get/Recover cold paths in place of the
// unsafe memcpy used by pointer-free entities.
func renderColdCodec(b *bytes.Buffer, spec hotStateSpec) {
	t := spec.table.GoTypeName
	b.WriteString("func marshalCold")
	b.WriteString(t)
	b.WriteString("(v ")
	b.WriteString(t)
	b.WriteString(") []byte {\n")
	b.WriteString("\tb := make([]byte, 0, 128)\n")
	for _, field := range spec.table.Fields {
		gt := memoryGoType(field, spec.table.IsEvent)
		if elem, ok := coldSliceElem(gt); ok {
			b.WriteString("\tb = binary.AppendUvarint(b, uint64(len(v.")
			b.WriteString(field.Name)
			b.WriteString(")))\n")
			b.WriteString("\tfor i := range v.")
			b.WriteString(field.Name)
			b.WriteString(" {\n\t\t")
			b.WriteString(coldEncodeExpr("v."+field.Name+"[i]", elem))
			b.WriteString("\n\t}\n")
			continue
		}
		b.WriteString("\t")
		b.WriteString(coldEncodeExpr("v."+field.Name, gt))
		b.WriteString("\n")
	}
	b.WriteString("\tif v.Tombstone { b = append(b, 1) } else { b = append(b, 0) }\n")
	b.WriteString("\treturn b\n}\n\n")

	b.WriteString("func unmarshalCold")
	b.WriteString(t)
	b.WriteString("(data []byte) (")
	b.WriteString(t)
	b.WriteString(", bool) {\n")
	b.WriteString("\tv, off := ")
	b.WriteString(t)
	b.WriteString("{}, 0\n")
	for _, field := range spec.table.Fields {
		gt := memoryGoType(field, spec.table.IsEvent)
		if elem, ok := coldSliceElem(gt); ok {
			w := coldFixedWidth(elem)
			b.WriteString("\t{\n")
			b.WriteString("\t\tif off > len(data) { return v, false }\n")
			b.WriteString("\t\tn, sz := binary.Uvarint(data[off:])\n")
			b.WriteString("\t\tif sz <= 0 { return v, false }\n")
			b.WriteString("\t\toff += sz\n")
			fmt.Fprintf(b, "\t\tif n > uint64(len(data)-off)/%d { return v, false }\n", w)
			b.WriteString("\t\tv.")
			b.WriteString(field.Name)
			b.WriteString(" = make([]")
			b.WriteString(elem)
			b.WriteString(", n)\n")
			b.WriteString("\t\tfor i := range v.")
			b.WriteString(field.Name)
			b.WriteString(" {\n")
			for _, line := range coldDecodeAssign("v."+field.Name+"[i]", elem) {
				b.WriteString("\t\t\t")
				b.WriteString(line)
				b.WriteString("\n")
			}
			b.WriteString("\t\t}\n")
			b.WriteString("\t}\n")
			continue
		}
		for _, line := range coldDecodeAssign("v."+field.Name, gt) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tif off+1 > len(data) { return v, false }\n")
	b.WriteString("\tv.Tombstone = data[off] != 0\n")
	b.WriteString("\treturn v, true\n}\n\n")
}

func renderBatchResolver(b *bytes.Buffer, spec hotStateSpec) {
	resolverType := spec.table.GoTypeName + "BatchResolver"
	cacheType := spec.cacheType
	keyType := spec.keyType
	valueType := spec.table.GoTypeName

	b.WriteString("type ")
	b.WriteString(resolverType)
	b.WriteString(" struct {\n\tcache  *")
	b.WriteString(cacheType)
	b.WriteString("\n\tmisses []")
	b.WriteString(keyType)
	// C4: per-Resolve scratch reused across blocks (cleared, not reallocated).
	// The resolver is single-owner (consumer goroutine; see GEN-003B), so no
	// synchronization is needed on these.
	b.WriteString("\n\tuniqueKeys map[")
	b.WriteString(keyType)
	b.WriteString("]struct{}")
	b.WriteString("\n\tuniqueList []")
	b.WriteString(keyType)
	b.WriteString("\n\tfoundKeys map[")
	b.WriteString(keyType)
	b.WriteString("]struct{}")
	b.WriteString("\n\tmetricsEnabled bool\n\tmetrics BatchResolverMetrics\n}\n\n")

	b.WriteString("func New")
	b.WriteString(resolverType)
	b.WriteString("(cache *")
	b.WriteString(cacheType)
	b.WriteString(") *")
	b.WriteString(resolverType)
	b.WriteString(" {\n\treturn &")
	b.WriteString(resolverType)
	b.WriteString("{\n\t\tcache: cache,\n\t}\n}\n\n")

	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Lookup(key ")
	b.WriteString(keyType)
	b.WriteString(") (")
	b.WriteString(valueType)
	b.WriteString(", bool) {\n")
	b.WriteString("\treturn r.cache.Get(key)\n}\n\n")

	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Queue(key ")
	b.WriteString(keyType)
	b.WriteString(") {\n\tif _, ok := r.Lookup(key); !ok {\n")
	b.WriteString("\t\tif r.metricsEnabled {\n\t\t\tr.metrics.QueuedMisses++\n\t\t}\n")
	b.WriteString("\t\tr.misses = append(r.misses, key)\n\t}\n}\n\n")

	b.WriteString("// Pending reports how many missed keys are queued for the next Resolve.\n")
	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Pending() int {\n\treturn len(r.misses)\n}\n\n")

	b.WriteString("// EnableMetrics toggles resolver counters for a bounded observation interval.\n")
	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") EnableMetrics(enabled bool) {\n")
	b.WriteString("\tr.metricsEnabled = enabled\n")
	b.WriteString("\tif enabled {\n\t\tr.cache.metrics = &r.metrics\n\t} else {\n\t\tr.cache.metrics = nil\n\t}\n")
	b.WriteString("}\n\n")

	b.WriteString("// MetricsEnabled reports whether resolver counters are active.\n")
	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") MetricsEnabled() bool {\n\treturn r.metricsEnabled\n}\n\n")

	b.WriteString("// Metrics returns cumulative single-owner resolver counters.\n")
	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Metrics() BatchResolverMetrics {\n\treturn r.metrics\n}\n\n")

	b.WriteString("// SnapshotAndResetMetrics returns the current counters and starts a new interval.\n")
	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") SnapshotAndResetMetrics() BatchResolverMetrics {\n")
	b.WriteString("\tmetrics := r.metrics\n\tr.metrics = BatchResolverMetrics{}\n\treturn metrics\n}\n\n")

	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Resolve(ctx context.Context, conn *ch.Client, db string) error {\n")
	b.WriteString("\tif len(r.misses) == 0 {\n\t\treturn nil\n\t}\n\n")
	b.WriteString("\tif r.uniqueKeys == nil {\n\t\tr.uniqueKeys = make(map[")
	b.WriteString(keyType)
	b.WriteString("]struct{})\n\t}\n")
	b.WriteString("\tclear(r.uniqueKeys)\n")
	b.WriteString("\tuniqueList := r.uniqueList[:0]\n")
	b.WriteString("\tfor _, key := range r.misses {\n")
	b.WriteString("\t\tif _, ok := r.uniqueKeys[key]; !ok {\n")
	b.WriteString("\t\t\tr.uniqueKeys[key] = struct{}{}\n")
	b.WriteString("\t\t\tuniqueList = append(uniqueList, key)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tr.uniqueList = uniqueList\n")
	b.WriteString("\tr.misses = r.misses[:0]\n\n")
	b.WriteString("\tif len(uniqueList) == 0 {\n\t\treturn nil\n\t}\n\n")
	b.WriteString("\tif r.metricsEnabled {\n")
	b.WriteString("\t\tr.metrics.UniqueMisses += uint64(len(uniqueList))\n")
	b.WriteString("\t\tr.metrics.DBFallbacks += uint64(len(uniqueList))\n")
	b.WriteString("\t}\n\n")

	keyFields := spec.table.keyFields()
	if len(keyFields) > 1 {
		b.WriteString("\tvar values []string\n")
		b.WriteString("\tfor _, key := range uniqueList {\n")
		b.WriteString("\t\tvalues = append(values, \"(\"")
		for i, field := range keyFields {
			if i > 0 {
				b.WriteString(" + \", \"")
			}
			b.WriteString(" + ")
			b.WriteString(keySQLValueExpr("key."+field.Name, field))
		}
		b.WriteString(" + \")\")\n")
		b.WriteString("\t}\n\n")

		queryBody := fmt.Sprintf("SELECT %s FROM %%s.%s WHERE %s IN (%%s) ORDER BY `block_number` DESC, `transaction_index` DESC, `log_index` DESC LIMIT 1 BY %s",
			customSelectColumnList(spec.table),
			spec.table.Name,
			customInsertColumnList(customTableSpec{Columns: keyColumns(keyFields)}),
			keyColumnExpressionList(keyFields),
		)
		b.WriteString(fmt.Sprintf("\tqueryStr := fmt.Sprintf(%s, quoteIdent(db), strings.Join(values, \", \"))\n\n",
			strconv.Quote(queryBody),
		))
	} else if len(keyFields) == 1 {
		b.WriteString("\tvar values []string\n")
		b.WriteString("\tfor _, key := range uniqueList {\n")
		keyField := keyFields[0]
		b.WriteString("\t\tvalues = append(values, ")
		b.WriteString(keySQLValueExpr("key."+keyField.Name, keyField))
		b.WriteString(")\n")
		b.WriteString("\t}\n\n")

		queryBody := fmt.Sprintf("SELECT %s FROM %%s.%s WHERE %s IN (%%s) ORDER BY `block_number` DESC, `transaction_index` DESC, `log_index` DESC LIMIT 1 BY %s",
			customSelectColumnList(spec.table),
			spec.table.Name,
			quoteSQLIdent(keyField.ColumnName),
			keyColumnExpressionList(keyFields),
		)
		b.WriteString(fmt.Sprintf("\tqueryStr := fmt.Sprintf(%s, quoteIdent(db), strings.Join(values, \", \"))\n\n",
			strconv.Quote(queryBody),
		))
	} else {
		b.WriteString("\tqueryStr := \"\"\n")
	}

	b.WriteString("\tvar (\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(resultColumnType(field))
		b.WriteString("\n")
	}
	b.WriteString("\t)\n")
	for _, field := range spec.table.Fields {
		for _, line := range resultInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tresults := proto.Results{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(resultData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")

	b.WriteString("\tif r.foundKeys == nil {\n\t\tr.foundKeys = make(map[")
	b.WriteString(keyType)
	b.WriteString("]struct{})\n\t}\n")
	b.WriteString("\tclear(r.foundKeys)\n")
	b.WriteString("\tfoundKeys := r.foundKeys\n")
	b.WriteString("\tq := ch.Query{\n")
	b.WriteString("\t\tBody:   queryStr,\n")
	b.WriteString("\t\tResult: results,\n")
	b.WriteString("\t\tOnResult: func(ctx context.Context, block proto.Block) error {\n")
	b.WriteString("\t\t\tfor i := 0; i < block.Rows; i++ {\n")
	b.WriteString("\t\t\t\titem := ")
	b.WriteString(valueType)
	b.WriteString("{\n")
	if spec.table.IsEvent {
		b.WriteString("\t\t\t\t\tEventMeta: EventMeta{\n")
		for _, field := range spec.table.Fields {
			if field.Name == "BlockNumber" || field.Name == "BlockTimestamp" || field.Name == "TransactionIndex" || field.Name == "LogIndex" {
				b.WriteString("\t\t\t\t\t\t")
				b.WriteString(field.Name)
				b.WriteString(": ")
				b.WriteString(resultValueExpr(field, spec.table.IsEvent))
				b.WriteString(",\n")
			}
		}
		b.WriteString("\t\t\t\t\t},\n")
		for _, field := range spec.table.Fields {
			if !(field.Name == "BlockNumber" || field.Name == "BlockTimestamp" || field.Name == "TransactionIndex" || field.Name == "LogIndex") {
				b.WriteString("\t\t\t\t\t")
				b.WriteString(field.Name)
				b.WriteString(": ")
				b.WriteString(resultValueExpr(field, spec.table.IsEvent))
				b.WriteString(",\n")
			}
		}
	} else {
		for _, field := range spec.table.Fields {
			b.WriteString("\t\t\t\t\t")
			b.WriteString(field.Name)
			b.WriteString(": ")
			b.WriteString(resultValueExpr(field, spec.table.IsEvent))
			b.WriteString(",\n")
		}
	}
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\tr.cache.Set(item)\n")
	b.WriteString("\t\t\t\tfoundKeys[New")
	b.WriteString(keyType)
	b.WriteString("(item)] = struct{}{}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t\treturn nil\n")
	b.WriteString("\t\t},\n")
	b.WriteString("\t}\n")
	b.WriteString("\tvar resolveStart time.Time\n")
	b.WriteString("\tif r.metricsEnabled {\n\t\tr.metrics.RoundTrips++\n\t\tresolveStart = time.Now()\n\t}\n")
	b.WriteString("\terr := conn.Do(ctx, q)\n")
	b.WriteString("\tif r.metricsEnabled {\n\t\tr.metrics.ResolveNanos += uint64(time.Since(resolveStart))\n\t}\n")
	b.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tfor _, key := range uniqueList {\n")
	b.WriteString("\t\tif _, found := foundKeys[key]; !found {\n")
	b.WriteString("\t\t\ttombstone := ")
	b.WriteString(valueType)
	b.WriteString("{Tombstone: true}\n")
	for _, field := range keyFields {
		b.WriteString("\t\t\ttombstone.")
		b.WriteString(field.Name)
		b.WriteString(" = key.")
		b.WriteString(field.Name)
		b.WriteString("\n")
	}
	b.WriteString("\t\t\tr.cache.SetByKey(key, tombstone)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

func keySQLValueExpr(expr string, field customFieldSpec) string {
	switch field.Type {
	case "common.Address", "common.Hash":
		return fmt.Sprintf("fmt.Sprintf(\"unhex('%%s')\", strings.TrimPrefix(%s.Hex(), \"0x\"))", expr)
	case "string":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", strings.ReplaceAll(%s, \"'\", \"''\"))", expr)
	case "bool":
		return fmt.Sprintf("hotStateBoolSQL(%s)", expr)
	case "uint256.Int":
		return expr + ".Dec()"
	case "decimal.Decimal":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.String())", expr)
	case "protomath.Decimal256":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.String(protomath.Decimal256Scale18))", expr)
	case "float32", "float64":
		return fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", expr)
	case "time.Time":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.UTC().Format(time.RFC3339Nano))", expr)
	default:
		return fmt.Sprintf("fmt.Sprintf(\"%%d\", %s)", expr)
	}
}

func customSelectColumnList(table customTableSpec) string {
	selects := make([]string, 0, len(table.Fields))
	for _, field := range table.Fields {
		selects = append(selects, quoteSQLIdent(field.ColumnName))
	}
	return strings.Join(selects, ", ")
}

func keyColumns(fields []customFieldSpec) []customColumnSpec {
	out := make([]customColumnSpec, 0, len(fields))
	for _, f := range fields {
		out = append(out, customColumnSpec{Name: f.ColumnName})
	}
	return out
}

func keyColumnExpressionList(fields []customFieldSpec) string {
	out := make([]string, 0, len(fields))
	for _, field := range fields {
		out = append(out, quoteSQLIdent(field.ColumnName))
	}
	return strings.Join(out, ", ")
}

func findStateEventSpec(events []eventSpec, state config.StateConfig) (*eventSpec, error) {
	if state.SourceTable != "" {
		for _, ev := range events {
			if ev.TableName == state.SourceTable {
				return &ev, nil
			}
		}
	}
	// Try to resolve from state.Name
	for _, ev := range events {
		if strings.EqualFold(ev.EventName, state.Name) || strings.EqualFold(ev.GoTypeName, state.Name) {
			return &ev, nil
		}
	}
	// Fallback: try to see if any event table contains the state name
	for _, ev := range events {
		if strings.Contains(strings.ToLower(ev.TableName), strings.ToLower(state.Name)) {
			return &ev, nil
		}
	}
	return nil, fmt.Errorf("source table or event matching %q not found in event tables", state.Name)
}
