package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"

	"github.com/franz101/sqd-go/internal/config"
)

type hotStateSpec struct {
	table     customTableSpec
	baseName  string
	keyType   string
	entryType string
	cacheType string
	batchType string
}

func generateHotStateGo(tables []customTableSpec, events []eventSpec) ([]byte, error) {
	var b bytes.Buffer
	specs := hotStateSpecs(tables)

	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)
	renderHotStateImports(&b, tables, events)

	b.WriteString("const DefaultClockCacheCapacity uint64 = 100000\n")
	b.WriteString("const recoveryBucketCount = 8\n")
	// recoveryConcurrency bounds how many bucket queries run at once during
	// Recover. Beyond ~8 the latest-per-key scan is decompression-bound, so 8
	// saturates a typical box without extra connections.
	b.WriteString("const recoveryConcurrency = 8\n\n")
	if customTablesUseSerializedCold(tables) {
		b.WriteString("// coldBoolByte packs a bool for the cold-tier value codec.\n")
		b.WriteString("func coldBoolByte(x bool) byte {\n\tif x {\n\t\treturn 1\n\t}\n\treturn 0\n}\n\n")
	}
	b.WriteString(`func recoveryFixedStringRange(column string, bucket int, size int) string {
	if recoveryBucketCount <= 1 {
		return "1"
	}
	width := 256 / recoveryBucketCount
	lower := bucket * width
	lowerHex := fmt.Sprintf("%02x%s", lower, strings.Repeat("00", size-1))
	lowerExpr := fmt.Sprintf("toFixedString(unhex('%s'), %d)", lowerHex, size)
	if bucket >= recoveryBucketCount-1 {
		return fmt.Sprintf("%s >= %s", column, lowerExpr)
	}
	upper := (bucket + 1) * width
	upperHex := fmt.Sprintf("%02x%s", upper, strings.Repeat("00", size-1))
	upperExpr := fmt.Sprintf("toFixedString(unhex('%s'), %d)", upperHex, size)
	return fmt.Sprintf("%s >= %s AND %s < %s", column, lowerExpr, column, upperExpr)
}

func recoveryDialConn(ctx context.Context) (*ch.Client, error) {
	host := os.Getenv("CLICKHOUSE_HOST")
	if host == "" {
		host = "127.0.0.1"
	}
	port := 9000
	if v := os.Getenv("CLICKHOUSE_NATIVE_PORT"); v != "" {
		if p, err := strconv.Atoi(v); err == nil {
			port = p
		}
	}
	user := os.Getenv("CLICKHOUSE_USER")
	if user == "" {
		user = "default"
	}
	return ch.Dial(ctx, ch.Options{
		Address:  fmt.Sprintf("%s:%d", host, port),
		Database: "default",
		User:     user,
		Password: os.Getenv("CLICKHOUSE_PASSWORD"),
	})
}

// recoverBucketsParallel runs the latest-per-key scan for nbuckets disjoint
// key-prefix buckets concurrently, then applies every decoded row on a single
// goroutine. Each worker owns its own ch.Client (ch-go connections are not safe
// for concurrent Do): the pool is the caller's primary connection plus up to
// recoveryConcurrency-1 freshly dialed ones, and a dial failure just means fewer
// workers rather than an error. run executes one bucket against a connection and
// hands each decoded block to flush; set applies one row to the cache. The cache
// and its cold tier are not safe for concurrent writers, so the queries fan out
// while every set runs on the lone consumer. Buckets partition the keyspace, so
// no key is ever set twice and set ordering is irrelevant.
func recoverBucketsParallel[T any](
	ctx context.Context,
	primary *ch.Client,
	nbuckets int,
	run func(ctx context.Context, conn *ch.Client, bucket int, flush func([]T)) error,
	set func(T),
) error {
	if nbuckets <= 1 {
		return run(ctx, primary, 0, func(batch []T) {
			for i := range batch {
				set(batch[i])
			}
		})
	}

	conc := recoveryConcurrency
	if conc > nbuckets {
		conc = nbuckets
	}
	conns := make([]*ch.Client, 1, conc)
	conns[0] = primary
	for len(conns) < conc {
		wc, err := recoveryDialConn(ctx)
		if err != nil {
			break
		}
		conns = append(conns, wc)
	}
	defer func() {
		for _, wc := range conns[1:] {
			_ = wc.Close()
		}
	}()

	ctx, cancel := context.WithCancel(ctx)
	defer cancel()

	items := make(chan []T, len(conns)*2)
	var consumerWG sync.WaitGroup
	consumerWG.Add(1)
	go func() {
		defer consumerWG.Done()
		for batch := range items {
			for i := range batch {
				set(batch[i])
			}
		}
	}()

	buckets := make(chan int)
	var (
		workerWG sync.WaitGroup
		errMu    sync.Mutex
		firstErr error
	)
	fail := func(err error) {
		if err == nil {
			return
		}
		errMu.Lock()
		if firstErr == nil {
			firstErr = err
			cancel()
		}
		errMu.Unlock()
	}
	flush := func(batch []T) {
		if len(batch) == 0 {
			return
		}
		select {
		case items <- batch:
		case <-ctx.Done():
		}
	}
	for _, conn := range conns {
		workerWG.Add(1)
		go func(conn *ch.Client) {
			defer workerWG.Done()
			for bucket := range buckets {
				if err := run(ctx, conn, bucket, flush); err != nil {
					fail(err)
					return
				}
			}
		}(conn)
	}
feed:
	for bucket := 0; bucket < nbuckets; bucket++ {
		select {
		case buckets <- bucket:
		case <-ctx.Done():
			break feed
		}
	}
	close(buckets)
	workerWG.Wait()
	close(items)
	consumerWG.Wait()
	return firstErr
}

`)
	for _, spec := range specs {
		if !spec.table.IsEvent {
			renderHotStateEntity(&b, spec.table)
		}
		renderClockKey(&b, spec)
		renderClockCache(&b, spec)
		if !spec.table.IsEvent {
			renderCustomBatch(&b, spec)
			renderClockRecover(&b, spec)
		}
		renderBatchResolver(&b, spec)
	}
	renderHotStateType(&b, specs)
	renderHotStateHelpers(&b, tables, events)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format source: %w", err)
	}
	return formatted, nil
}

func renderHotStateImports(b *bytes.Buffer, tables []customTableSpec, events []eventSpec) {
	imports := map[string]string{
		`"context"`:                           "",
		`"fmt"`:                               "",
		`"os"`:                                "",
		`"strconv"`:                           "",
		`"strings"`:                           "",
		`"sync"`:                              "",
		`"sync/atomic"`:                       "",
		`"github.com/ClickHouse/ch-go"`:       "",
		`"github.com/ClickHouse/ch-go/proto"`: "",
		`"github.com/franz101/sqd-go/internal/coldcache"`: "",
	}
	if customTablesUseDecimal(tables) {
		imports[`"encoding/binary"`] = ""
		imports[`"math/big"`] = ""
	}
	if customTablesUseColdCache(tables) {
		// Cold tier (Pebble) stores pointer-free hot values as raw bytes; the
		// unsafe memcpy is zero-transformation and filepath builds the per-cache dir.
		imports[`"path/filepath"`] = ""
		imports[`"unsafe"`] = ""
	}
	if customTablesUseSerializedCold(tables) {
		// Slice-bearing entities spill to / load from the cold tier via the
		// generated byte codec, which packs scalars little-endian.
		imports[`"encoding/binary"`] = ""
		// math.Float*bits only appears in the codec for float-valued cold fields.
		for _, table := range tables {
			if !entityUsesSerializedCold(table) {
				continue
			}
			for _, field := range table.Fields {
				if t := memoryGoType(field, table.IsEvent); t == "float32" || t == "float64" {
					imports[`"math"`] = ""
				}
			}
		}
	}
	for _, table := range tables {
		for _, field := range table.Fields {
			switch {
			case strings.Contains(field.Type, "time."):
				imports[`"time"`] = ""
			case strings.Contains(field.Type, "common."):
				imports[`"github.com/ethereum/go-ethereum/common"`] = ""
			case strings.Contains(field.Type, "uint256."):
				imports[`"github.com/holiman/uint256"`] = ""
			case strings.Contains(field.Type, "decimal."):
				imports[`"github.com/shopspring/decimal"`] = ""
			case strings.Contains(field.Type, "protomath."):
				imports[`"github.com/franz101/sqd-go/drafts/protomath"`] = ""
			}
		}
	}
	// Event views (ProtoEventBlock) reference the uint256 hot-state helpers for any
	// event with a uint256/uint256[] arg, even when no custom/hot-state table uses
	// uint256 — so the import must follow event usage too.
	if eventsUseUint256(events) || eventsUseUint256Slice(events) {
		imports[`"github.com/holiman/uint256"`] = ""
	}
	b.WriteString("import (\n")
	for _, imp := range sortedImportKeys(imports) {
		b.WriteString("\t")
		b.WriteString(imp)
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func renderHotStateEntity(b *bytes.Buffer, table customTableSpec) {
	b.WriteString("type ")
	b.WriteString(table.GoTypeName)
	b.WriteString(" struct {\n")
	for _, field := range table.Fields {
		b.WriteString("\t")
		b.WriteString(field.Name)
		b.WriteString(" ")
		b.WriteString(memoryGoType(field, table.IsEvent))
		b.WriteString(" `ch:")
		b.WriteString(strconv.Quote("name=" + field.ColumnName + ";type=" + field.ColumnType))
		b.WriteString("`\n")
	}
	b.WriteString("\tTombstone bool `ch:\"-\"`\n")
	b.WriteString("}\n\n")
}

func renderClockKey(b *bytes.Buffer, spec hotStateSpec) {
	keyFields := spec.table.keyFields()
	b.WriteString("type ")
	b.WriteString(spec.keyType)
	b.WriteString(" struct {\n")
	for _, field := range keyFields {
		b.WriteString("\t")
		b.WriteString(field.Name)
		b.WriteString(" ")
		b.WriteString(field.Type)
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("func New")
	b.WriteString(spec.keyType)
	b.WriteString("(value ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(") ")
	b.WriteString(spec.keyType)
	b.WriteString(" {\n\treturn ")
	b.WriteString(spec.keyType)
	b.WriteString("{")
	for i, field := range keyFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(field.Name)
		b.WriteString(": value.")
		b.WriteString(field.Name)
	}
	b.WriteString("}\n}\n\n")
}

func renderClockCache(b *bytes.Buffer, spec hotStateSpec) {
	valueType := spec.table.GoTypeName
	keyFields := spec.table.keyFields()

	b.WriteString("type ")
	b.WriteString(spec.entryType)
	b.WriteString(" struct {\n\tkey ")
	b.WriteString(spec.keyType)
	b.WriteString("\n\tvalue ")
	b.WriteString(valueType)
	b.WriteString("\n\treferenced uint32\n\tinUse uint32\n}\n\n")

	// Cache struct. The index is a pointer-free chained hash over an arena (A3):
	// buckets[h] = ring index of a chain head (-1 = empty); next[ringIdx] = next
	// ring index in the same bucket (-1 = end). Replaces a sync.Map[key]idx whose
	// boxed key+idx interfaces were ~3 GC-scanned objects per live entry. Single
	// writer (one processor goroutine) => the index needs no locking; the CLOCK
	// entry flags stay atomic so concurrent readers (if ever reintroduced) still see
	// torn-free flag transitions.
	fmt.Fprintf(b, `type %[1]s struct {
	buckets  []int32
	next     []int32
	ring     []%[2]s
	mask     uint32
	capacity uint64
	hand     uint64
	size     uint64
	// evictions counts entries overwritten by CLOCK replacement. While zero,
	// the hot ring still holds everything ever Set — so under an authoritative
	// (from-genesis) run, hot contents are a superset of the entity's
	// ClickHouse rows and a hot miss proves a database miss.
	evictions uint64
	// cold is an optional Pebble-backed tier holding evicted entries (raw bytes).
	// nil unless attached via HotState.EnableColdCache (pointer-free entities only).
	cold *coldcache.Store
}

// Evictions reports how many entries CLOCK replacement has overwritten.
func (c *%[1]s) Evictions() uint64 {
	return atomic.LoadUint64(&c.evictions)
}

func New%[1]s(capacity uint64) *%[1]s {
	if capacity == 0 {
		capacity = DefaultClockCacheCapacity
	}
	bucketCount := uint64(8)
	for bucketCount < capacity*2 {
		bucketCount <<= 1
	}
	c := &%[1]s{
		ring:     make([]%[2]s, capacity),
		buckets:  make([]int32, bucketCount),
		next:     make([]int32, capacity),
		mask:     uint32(bucketCount - 1),
		capacity: capacity,
	}
	for i := range c.buckets {
		c.buckets[i] = -1
	}
	for i := range c.next {
		c.next[i] = -1
	}
	return c
}

`, spec.cacheType, spec.entryType)

	// keyHash folds every key field's bytes (all keys are common.Hash/Address byte
	// arrays) into a bucket index.
	fmt.Fprintf(b, "func (c *%s) keyHash(key %s) uint32 {\n\th := uint64(1469598103934665603)\n", spec.cacheType, spec.keyType)
	for _, field := range keyFields {
		fmt.Fprintf(b, "\th = clockHash64(h, key.%s[:])\n", field.Name)
	}
	b.WriteString("\treturn uint32(h^(h>>32)) & c.mask\n}\n\n")

	fmt.Fprintf(b, `func (c *%[1]s) idxLookup(key %[2]s) (uint64, bool) {
	for i := c.buckets[c.keyHash(key)]; i >= 0; i = c.next[i] {
		if c.ring[i].key == key {
			return uint64(i), true
		}
	}
	return 0, false
}

func (c *%[1]s) idxInsert(key %[2]s, ringIdx uint32) {
	h := c.keyHash(key)
	c.next[ringIdx] = c.buckets[h]
	c.buckets[h] = int32(ringIdx)
}

func (c *%[1]s) idxUnlink(key %[2]s) {
	h := c.keyHash(key)
	prev := int32(-1)
	for i := c.buckets[h]; i >= 0; i = c.next[i] {
		if c.ring[i].key == key {
			if prev < 0 {
				c.buckets[h] = c.next[i]
			} else {
				c.next[prev] = c.next[i]
			}
			c.next[i] = -1
			return
		}
		prev = i
	}
}

`, spec.cacheType, spec.keyType)

	coldOn := entityUsesCold(spec.table)
	serializedCold := entityUsesSerializedCold(spec.table)
	// spill: on CLOCK eviction, write the victim (value or tombstone) to the cold
	// tier BEFORE overwriting it, so a later re-reference is served from disk and a
	// dirty-but-evicted entry isn't lost before Commit reads it. Pointer-free values
	// blit as raw struct bytes; slice-bearing values go through the byte codec.
	spill := ""
	if coldOn {
		valuePut := "unsafe.Slice((*byte)(unsafe.Pointer(&e.value)), unsafe.Sizeof(e.value))"
		if serializedCold {
			valuePut = "coldEncode" + valueType + "(&e.value)"
		}
		spill = "\t\t\tif c.cold != nil {\n" +
			"\t\t\t\tc.cold.Put(unsafe.Slice((*byte)(unsafe.Pointer(&e.key)), unsafe.Sizeof(e.key)), " + valuePut + ")\n" +
			"\t\t\t}\n"
	}
	fmt.Fprintf(b, `func (c *%[1]s) Set(value %[3]s) {
	c.SetByKey(New%[2]s(value), value)
}

func (c *%[1]s) SetByKey(key %[2]s, value %[3]s) {
	if idx, ok := c.idxLookup(key); ok {
		e := &c.ring[idx]
		if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
			e.value = value
			atomic.StoreUint32(&e.referenced, 1)
			return
		}
	}
	for {
		hand := atomic.AddUint64(&c.hand, 1)
		idx := (hand - 1) %% c.capacity
		e := &c.ring[idx]
		if atomic.CompareAndSwapUint32(&e.inUse, 1, 0) {
			if atomic.LoadUint32(&e.referenced) == 1 {
				atomic.StoreUint32(&e.referenced, 0)
				atomic.StoreUint32(&e.inUse, 1)
				continue
			}
%[4]s			atomic.AddUint64(&c.evictions, 1)
			c.idxUnlink(e.key)
			e.key = key
			e.value = value
			atomic.StoreUint32(&e.referenced, 0)
			c.idxInsert(key, uint32(idx))
			atomic.StoreUint32(&e.inUse, 1)
			return
		}
		if atomic.LoadUint32(&e.inUse) == 0 {
			if atomic.CompareAndSwapUint32(&e.inUse, 0, 2) {
				e.key = key
				e.value = value
				atomic.StoreUint32(&e.referenced, 0)
				c.idxInsert(key, uint32(idx))
				atomic.AddUint64(&c.size, 1)
				atomic.StoreUint32(&e.inUse, 1)
				return
			}
		}
	}
}

`, spec.cacheType, spec.keyType, valueType, spill)

	if coldOn && serializedCold {
		// Cold-consult on hot miss, byte-codec variant: the slice-bearing value is
		// decoded from the Pebble bytes, then promoted back into the hot ring. A cold
		// tombstone round-trips as a value with Tombstone=true (state Get treats it as
		// "absent"). Serving from disk (~8µs) replaces the ClickHouse SELECT (~1.9ms).
		fmt.Fprintf(b, `func (c *%[1]s) Get(key %[2]s) (%[3]s, bool) {
	if idx, ok := c.idxLookup(key); ok {
		e := &c.ring[idx]
		if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
			atomic.StoreUint32(&e.referenced, 1)
			return e.value, true
		}
	}
	if c.cold != nil {
		if raw, found, _ := c.cold.Get(unsafe.Slice((*byte)(unsafe.Pointer(&key)), unsafe.Sizeof(key))); found {
			v := coldDecode%[3]s(raw)
			c.SetByKey(key, v)
			return v, true
		}
	}
	return %[3]s{}, false
}

`, spec.cacheType, spec.keyType, valueType)
	} else if coldOn {
		// Cold-consult on hot miss: an evicted entry (spilled on eviction) is served
		// from Pebble (~8µs) instead of a ClickHouse round-trip (~1.9ms), then
		// promoted back into the hot ring. A cold tombstone round-trips as a value
		// with Tombstone=true, which the state-level Get treats as "absent".
		fmt.Fprintf(b, `func (c *%[1]s) Get(key %[2]s) (%[3]s, bool) {
	if idx, ok := c.idxLookup(key); ok {
		e := &c.ring[idx]
		if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
			atomic.StoreUint32(&e.referenced, 1)
			return e.value, true
		}
	}
	if c.cold != nil {
		var v %[3]s
		if found, _ := c.cold.GetInto(unsafe.Slice((*byte)(unsafe.Pointer(&v)), unsafe.Sizeof(v)), unsafe.Slice((*byte)(unsafe.Pointer(&key)), unsafe.Sizeof(key))); found {
			c.SetByKey(key, v)
			return v, true
		}
	}
	return %[3]s{}, false
}

`, spec.cacheType, spec.keyType, valueType)
	} else {
		fmt.Fprintf(b, `func (c *%[1]s) Get(key %[2]s) (%[3]s, bool) {
	idx, ok := c.idxLookup(key)
	if !ok {
		return %[3]s{}, false
	}
	e := &c.ring[idx]
	if atomic.LoadUint32(&e.inUse) == 1 && e.key == key {
		atomic.StoreUint32(&e.referenced, 1)
		return e.value, true
	}
	return %[3]s{}, false
}

`, spec.cacheType, spec.keyType, valueType)
	}

	if len(keyFields) > 0 {
		b.WriteString("func (c *")
		b.WriteString(spec.cacheType)
		b.WriteString(") GetByFields(")
		renderClockKeyParams(b, keyFields)
		b.WriteString(") (")
		b.WriteString(valueType)
		b.WriteString(", bool) {\n\treturn c.Get(")
		b.WriteString(spec.keyType)
		b.WriteString("{")
		for i, field := range keyFields {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(field.Name)
			b.WriteString(": ")
			b.WriteString(lowerFirst(field.Name))
		}
		b.WriteString("})\n}\n\n")
	}

	// coldDel mirrors a hard delete into the cold tier so a rolled-back key cannot
	// resurrect from disk on a later miss.
	coldDel := ""
	if coldOn {
		coldDel = "\t\t\tif c.cold != nil {\n" +
			"\t\t\t\tc.cold.Delete(unsafe.Slice((*byte)(unsafe.Pointer(&key)), unsafe.Sizeof(key)))\n" +
			"\t\t\t}\n"
	}
	fmt.Fprintf(b, `func (c *%[1]s) Delete(key %[2]s) bool {
	idx, ok := c.idxLookup(key)
	if !ok {
		return false
	}
	e := &c.ring[idx]
	if atomic.CompareAndSwapUint32(&e.inUse, 1, 0) {
		if e.key == key {
			c.idxUnlink(key)
%[4]s			e.key = %[2]s{}
			e.value = %[3]s{}
			atomic.StoreUint32(&e.referenced, 0)
			atomic.AddUint64(&c.size, ^uint64(0))
			return true
		}
		atomic.StoreUint32(&e.inUse, 1)
	}
	return false
}

func (c *%[1]s) Range(fn func(%[2]s, %[3]s) bool) {
	if fn == nil {
		return
	}
	limit := atomic.LoadUint64(&c.hand)
	if limit > c.capacity {
		limit = c.capacity
	}
	for i := uint64(0); i < limit; i++ {
		e := &c.ring[i]
		if atomic.LoadUint32(&e.inUse) == 1 {
			if !fn(e.key, e.value) {
				return
			}
		}
	}
}

func (c *%[1]s) AppendValues(dst []%[3]s) []%[3]s {
	if c == nil {
		return dst
	}
	if atomic.LoadUint64(&c.size) == 0 {
		return dst
	}
	limit := atomic.LoadUint64(&c.hand)
	if limit > c.capacity {
		limit = c.capacity
	}
	for i := 0; i < int(limit); i++ {
		e := &c.ring[i]
		if atomic.LoadUint32(&e.inUse) == 1 {
			dst = append(dst, e.value)
		}
	}
	return dst
}

func (c *%[1]s) Len() uint64 {
	return atomic.LoadUint64(&c.size)
}

`, spec.cacheType, spec.keyType, valueType, coldDel)

	if serializedCold {
		renderColdValueCodec(b, spec)
	}
}

// renderColdValueCodec emits coldEncode<Type>/coldDecode<Type> for a slice-bearing
// cold entity: a compact, self-describing byte image of the in-memory value struct
// (every field in declaration order, plus the runtime Tombstone flag). Scalars are
// little-endian; slices are uint32-count-prefixed. The format must round-trip the
// exact in-memory representation (memoryGoType: time.Time -> int64), since the cold
// tier is the authoritative overflow store, not a re-derivable cache.
func renderColdValueCodec(b *bytes.Buffer, spec hotStateSpec) {
	valueType := spec.table.GoTypeName
	fields := append([]customFieldSpec{}, spec.table.Fields...)
	fields = append(fields, customFieldSpec{Name: "Tombstone", Type: "bool"})

	fmt.Fprintf(b, "func coldEncode%[1]s(v *%[1]s) []byte {\n\tb := make([]byte, 0, %d)\n", valueType, coldEncodeHint(fields))
	for _, f := range fields {
		b.WriteString(coldEncodeField(f))
	}
	b.WriteString("\treturn b\n}\n\n")

	fmt.Fprintf(b, "func coldDecode%[1]s(p []byte) %[1]s {\n\tvar v %[1]s\n\toff := 0\n", valueType)
	for _, f := range fields {
		b.WriteString(coldDecodeField(f))
	}
	b.WriteString("\t_ = off\n\treturn v\n}\n\n")
}

// coldEncodeHint pre-sizes the encode buffer to the sum of the fixed-width fields
// (slices grow it as needed); purely an allocation hint.
func coldEncodeHint(fields []customFieldSpec) int {
	n := 0
	for _, f := range fields {
		switch memoryGoType(f, false) {
		case "common.Hash", "uint256.Int":
			n += 32
		case "common.Address":
			n += 20
		case "protomath.Decimal256":
			n += 32
		case "bool", "uint8", "int8":
			n += 1
		case "uint16", "int16":
			n += 2
		case "uint32", "int32", "float32":
			n += 4
		case "uint", "uint64", "int", "int64", "float64":
			n += 8
		default:
			n += 8 // slices / variable: count prefix
		}
	}
	return n
}

// coldEncodeField returns the encode statement(s) for one value-struct field.
// Panics at codegen time on an unsupported type rather than emitting a value that
// silently fails to round-trip.
func coldEncodeField(f customFieldSpec) string {
	v := "v." + f.Name
	switch memoryGoType(f, false) {
	case "common.Hash", "common.Address":
		return "\tb = append(b, " + v + "[:]...)\n"
	case "uint256.Int":
		return "\t{\n\t\tbs := " + v + ".Bytes32()\n\t\tb = append(b, bs[:]...)\n\t}\n"
	case "protomath.Decimal256":
		return "\t{\n\t\tbs := " + v + ".Bytes32()\n\t\tb = append(b, bs[:]...)\n\t}\n"
	case "bool":
		return "\tb = append(b, coldBoolByte(" + v + "))\n"
	case "uint8":
		return "\tb = append(b, " + v + ")\n"
	case "int8":
		return "\tb = append(b, byte(" + v + "))\n"
	case "uint16":
		return "\tb = binary.LittleEndian.AppendUint16(b, " + v + ")\n"
	case "int16":
		return "\tb = binary.LittleEndian.AppendUint16(b, uint16(" + v + "))\n"
	case "uint32":
		return "\tb = binary.LittleEndian.AppendUint32(b, " + v + ")\n"
	case "int32":
		return "\tb = binary.LittleEndian.AppendUint32(b, uint32(" + v + "))\n"
	case "float32":
		return "\tb = binary.LittleEndian.AppendUint32(b, math.Float32bits(" + v + "))\n"
	case "uint", "uint64":
		return "\tb = binary.LittleEndian.AppendUint64(b, uint64(" + v + "))\n"
	case "int", "int64":
		return "\tb = binary.LittleEndian.AppendUint64(b, uint64(" + v + "))\n"
	case "float64":
		return "\tb = binary.LittleEndian.AppendUint64(b, math.Float64bits(" + v + "))\n"
	case "[]uint256.Int":
		return "\tb = binary.LittleEndian.AppendUint32(b, uint32(len(" + v + ")))\n" +
			"\tfor i := range " + v + " {\n\t\tbs := " + v + "[i].Bytes32()\n\t\tb = append(b, bs[:]...)\n\t}\n"
	case "[]common.Hash":
		return "\tb = binary.LittleEndian.AppendUint32(b, uint32(len(" + v + ")))\n" +
			"\tfor i := range " + v + " {\n\t\tb = append(b, " + v + "[i][:]...)\n\t}\n"
	case "[]common.Address":
		return "\tb = binary.LittleEndian.AppendUint32(b, uint32(len(" + v + ")))\n" +
			"\tfor i := range " + v + " {\n\t\tb = append(b, " + v + "[i][:]...)\n\t}\n"
	default:
		panic(fmt.Sprintf("coldEncodeField: unsupported cold-tier field type %q for %s; add a codec case", memoryGoType(f, false), f.Name))
	}
}

// coldDecodeField returns the decode statement(s) for one value-struct field,
// advancing the running offset `off`.
func coldDecodeField(f customFieldSpec) string {
	v := "v." + f.Name
	switch memoryGoType(f, false) {
	case "common.Hash":
		return "\tcopy(" + v + "[:], p[off:off+32])\n\toff += 32\n"
	case "common.Address":
		return "\tcopy(" + v + "[:], p[off:off+20])\n\toff += 20\n"
	case "uint256.Int", "protomath.Decimal256":
		return "\t" + v + ".SetBytes(p[off : off+32])\n\toff += 32\n"
	case "bool":
		return "\t" + v + " = p[off] != 0\n\toff++\n"
	case "uint8":
		return "\t" + v + " = p[off]\n\toff++\n"
	case "int8":
		return "\t" + v + " = int8(p[off])\n\toff++\n"
	case "uint16":
		return "\t" + v + " = binary.LittleEndian.Uint16(p[off : off+2])\n\toff += 2\n"
	case "int16":
		return "\t" + v + " = int16(binary.LittleEndian.Uint16(p[off : off+2]))\n\toff += 2\n"
	case "uint32":
		return "\t" + v + " = binary.LittleEndian.Uint32(p[off : off+4])\n\toff += 4\n"
	case "int32":
		return "\t" + v + " = int32(binary.LittleEndian.Uint32(p[off : off+4]))\n\toff += 4\n"
	case "float32":
		return "\t" + v + " = math.Float32frombits(binary.LittleEndian.Uint32(p[off : off+4]))\n\toff += 4\n"
	case "uint", "uint64":
		return "\t" + v + " = binary.LittleEndian.Uint64(p[off : off+8])\n\toff += 8\n"
	case "int", "int64":
		return "\t" + v + " = int64(binary.LittleEndian.Uint64(p[off : off+8]))\n\toff += 8\n"
	case "float64":
		return "\t" + v + " = math.Float64frombits(binary.LittleEndian.Uint64(p[off : off+8]))\n\toff += 8\n"
	case "[]uint256.Int":
		return "\t{\n\t\tn := int(binary.LittleEndian.Uint32(p[off : off+4]))\n\t\toff += 4\n" +
			"\t\tif n > 0 {\n\t\t\t" + v + " = make([]uint256.Int, n)\n" +
			"\t\t\tfor i := 0; i < n; i++ {\n\t\t\t\t" + v + "[i].SetBytes(p[off : off+32])\n\t\t\t\toff += 32\n\t\t\t}\n\t\t}\n\t}\n"
	case "[]common.Hash":
		return "\t{\n\t\tn := int(binary.LittleEndian.Uint32(p[off : off+4]))\n\t\toff += 4\n" +
			"\t\tif n > 0 {\n\t\t\t" + v + " = make([]common.Hash, n)\n" +
			"\t\t\tfor i := 0; i < n; i++ {\n\t\t\t\tcopy(" + v + "[i][:], p[off:off+32])\n\t\t\t\toff += 32\n\t\t\t}\n\t\t}\n\t}\n"
	case "[]common.Address":
		return "\t{\n\t\tn := int(binary.LittleEndian.Uint32(p[off : off+4]))\n\t\toff += 4\n" +
			"\t\tif n > 0 {\n\t\t\t" + v + " = make([]common.Address, n)\n" +
			"\t\t\tfor i := 0; i < n; i++ {\n\t\t\t\tcopy(" + v + "[i][:], p[off:off+20])\n\t\t\t\toff += 20\n\t\t\t}\n\t\t}\n\t}\n"
	default:
		panic(fmt.Sprintf("coldDecodeField: unsupported cold-tier field type %q for %s; add a codec case", memoryGoType(f, false), f.Name))
	}
}

func renderCustomBatch(b *bytes.Buffer, spec hotStateSpec) {
	b.WriteString("type ")
	b.WriteString(spec.batchType)
	b.WriteString(" struct {\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(batchColumnType(field))
		b.WriteString("\n")
		if scratch := batchScratchField(field); scratch != "" {
			b.WriteString("\t")
			b.WriteString(scratch)
			b.WriteString(" ")
			b.WriteString(batchScratchType(field))
			b.WriteString("\n")
		}
	}
	b.WriteString("\tinput proto.Input\n}\n\n")

	b.WriteString("func New")
	b.WriteString(spec.batchType)
	b.WriteString("() *")
	b.WriteString(spec.batchType)
	b.WriteString(" {\n\tb := &")
	b.WriteString(spec.batchType)
	b.WriteString("{}\n")
	for _, field := range spec.table.Fields {
		for _, line := range batchInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tb.input = proto.Input{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(batchInputData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n\treturn b\n}\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") TableName() string { return ")
	b.WriteString(strconv.Quote(spec.table.Name))
	b.WriteString(" }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Rows() int { return ")
	b.WriteString(batchColumnRowsExpr(spec.table.Fields[0]))
	b.WriteString(" }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Reset() { b.input.Reset() }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Append(item ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(") {\n")
	for _, field := range spec.table.Fields {
		for _, line := range batchAppendLines(field, spec.table.IsEvent) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("}\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Inputs() proto.Input { return b.input }\n\n")

	b.WriteString("func (b *")
	b.WriteString(spec.batchType)
	b.WriteString(") Insert(ctx context.Context, conn *ch.Client, db string) error {\n\tif b.Rows() == 0 {\n\t\treturn nil\n\t}\n\treturn conn.Do(ctx, ch.Query{Body: fmt.Sprintf(")
	b.WriteString(strconv.Quote("INSERT INTO %s.%s " + customInsertColumnList(spec.table) + " VALUES"))
	// wait_for_async_insert is 0 (fire-and-forget) so a Commit with N dirty tables
	// issues N pipelined inserts without blocking on each table's server-side flush
	// (each block on the async busy-timeout was the dominant backfill cost). The
	// read-back invariant the old wait=1 protected — recovery/rollback/resolver
	// SELECTs must see committed rows — is instead upheld by HotState.Commit, which
	// issues ONE "SYSTEM FLUSH ASYNC INSERT QUEUE" barrier (under s.mu) after the
	// inserts and before returning, draining every buffer. Same durability, one
	// flush per commit instead of one wait per table: ~2.3x faster end-to-end.
	b.WriteString(", quoteIdent(db), quoteIdent(b.TableName())), Input: b.input, Settings: []ch.Setting{{Key: \"async_insert\", Value: \"1\", Important: true}, {Key: \"wait_for_async_insert\", Value: \"0\", Important: true}}})\n}\n\n")
}

func renderClockRecover(b *bytes.Buffer, spec hotStateSpec) {
	b.WriteString("func (c *")
	b.WriteString(spec.cacheType)
	b.WriteString(") Recover(ctx context.Context, conn *ch.Client, db string) error {\n\trun := func(ctx context.Context, conn *ch.Client, bucket int, flush func([]")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(")) error {\n\tvar (\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(resultColumnType(field))
		b.WriteString("\n")
	}
	b.WriteString("\t)\n")
	for _, field := range spec.table.Fields {
		for _, line := range resultInitLines(field) {
			b.WriteString("\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\tresults := proto.Results{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(resultData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t}\n")
	b.WriteString("\treturn conn.Do(ctx, ch.Query{Body: fmt.Sprintf(")
	b.WriteString(strconv.Quote(recoverQuery(spec.table)))
	b.WriteString(", quoteIdent(db), quoteIdent(")
	b.WriteString(strconv.Quote(spec.table.Name))
	b.WriteString("), ")
	b.WriteString(recoverWhereExpr(spec.table))
	b.WriteString("), Result: results, OnResult: func(ctx context.Context, block proto.Block) error {\n\t\tbatch := make([]")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString(", 0, block.Rows)\n\t\tfor i := 0; i < block.Rows; i++ {\n\t\t\tbatch = append(batch, ")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString("{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t\t\t")
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(resultValueExpr(field, spec.table.IsEvent))
		b.WriteString(",\n")
	}
	b.WriteString("\t\t\t})\n\t\t}\n\t\tflush(batch)\n\t\treturn nil\n\t}})\n\t}\n\treturn recoverBucketsParallel[")
	b.WriteString(spec.table.GoTypeName)
	b.WriteString("](ctx, conn, recoveryBucketCount, run, c.Set)\n}\n\n")
}

func renderHotStateType(b *bytes.Buffer, specs []hotStateSpec) {
	b.WriteString("type HotState struct {\n")
	for _, spec := range specs {
		resolverType := spec.table.GoTypeName + "BatchResolver"
		b.WriteString("\t")
		b.WriteString(spec.baseName)
		b.WriteString(" *")
		b.WriteString(spec.cacheType)
		b.WriteString("\n")

		b.WriteString("\t")
		b.WriteString(spec.baseName)
		b.WriteString("Resolver *")
		b.WriteString(resolverType)
		b.WriteString("\n")

		if !spec.table.IsEvent {
			b.WriteString("\tdirty")
			b.WriteString(spec.baseName)
			b.WriteString(" map[")
			b.WriteString(spec.keyType)
			b.WriteString("]struct{}\n")
		}
	}
	b.WriteString("\tmu sync.Mutex\n")
	b.WriteString("\t// coldAuthoritative is set when hot∪cold provably covers every persisted\n")
	b.WriteString("\t// state row: either the cold tier was opened against an empty ClickHouse\n")
	b.WriteString("\t// (from-genesis backfill), or a full rebuild-from-ClickHouse just streamed\n")
	b.WriteString("\t// every state table through the caches with the cold tier attached. A\n")
	b.WriteString("\t// hot+cold miss is then provably new, so the lazy state Get skips the\n")
	b.WriteString("\t// ClickHouse point-SELECT entirely.\n")
	b.WriteString("\tcoldAuthoritative bool\n")
	b.WriteString("\t// coldDir / coldCacheBytes / coldMemTableBytes remember the EnableColdCache\n")
	b.WriteString("\t// configuration so the tier can be re-opened fresh on a rebuild.\n")
	b.WriteString("\tcoldDir           string\n")
	b.WriteString("\tcoldCacheBytes    int64\n")
	b.WriteString("\tcoldMemTableBytes uint64\n")
	b.WriteString("\t// coldCache is the single off-heap block cache shared by every entity's\n")
	b.WriteString("\t// cold tier, so total cold-cache RAM is bounded by ONE budget regardless of\n")
	b.WriteString("\t// how many state entities are persisted.\n")
	b.WriteString("\tcoldCache *coldcache.SharedCache\n")
	b.WriteString("}\n\n")

	b.WriteString("func NewHotState(capacity uint64) *HotState {\n\tif capacity == 0 {\n\t\tcapacity = DefaultClockCacheCapacity\n\t}\n")
	b.WriteString("\tstate := &HotState{\n")
	for _, spec := range specs {
		b.WriteString("\t\t")
		b.WriteString(spec.baseName)
		b.WriteString(": New")
		b.WriteString(spec.cacheType)
		b.WriteString("(capacity),\n")
		if !spec.table.IsEvent {
			b.WriteString("\t\tdirty")
			b.WriteString(spec.baseName)
			b.WriteString(": make(map[")
			b.WriteString(spec.keyType)
			b.WriteString("]struct{}),\n")
		}
	}
	b.WriteString("\t}\n")
	for _, spec := range specs {
		resolverType := spec.table.GoTypeName + "BatchResolver"
		b.WriteString("\tstate.")
		b.WriteString(spec.baseName)
		b.WriteString("Resolver = New")
		b.WriteString(resolverType)
		b.WriteString("(state.")
		b.WriteString(spec.baseName)
		b.WriteString(")\n")
	}
	b.WriteString("\treturn state\n}\n\n")

	// EnableColdCache / CloseColdCache: attach the Pebble cold tier to every
	// pointer-free entity. authoritative=true (from-genesis, empty ClickHouse) lets
	// the lazy Get skip ClickHouse on a hot+cold miss. Default-off — callers that
	// never enable it get byte-for-byte the prior behaviour.
	var coldSpecs []hotStateSpec
	for _, spec := range specs {
		if entityUsesCold(spec.table) {
			coldSpecs = append(coldSpecs, spec)
		}
	}
	b.WriteString("// ColdAuthoritative reports whether the cold tier is authoritative for misses\n")
	b.WriteString("// (opened against an empty ClickHouse): a hot+cold miss is provably new, so\n")
	b.WriteString("// callers batching their own resolver round-trips may skip them entirely.\n")
	b.WriteString("func (s *HotState) ColdAuthoritative() bool {\n\treturn s != nil && s.coldAuthoritative\n}\n\n")
	if len(coldSpecs) == 0 {
		b.WriteString("func (s *HotState) EnableColdCache(dir string, authoritative bool, cacheBytes int64, memTableBytes uint64) error {\n\treturn nil\n}\n\n")
		b.WriteString("func (s *HotState) ReopenColdCacheFresh() (bool, error) {\n\treturn false, nil\n}\n\n")
		b.WriteString("func (s *HotState) CloseColdCache() error {\n\treturn nil\n}\n\n")
	} else {
		b.WriteString("func (s *HotState) EnableColdCache(dir string, authoritative bool, cacheBytes int64, memTableBytes uint64) error {\n")
		b.WriteString("\tif s == nil {\n\t\treturn nil\n\t}\n")
		b.WriteString("\t// One shared block cache for every entity's cold tier: total off-heap\n")
		b.WriteString("\t// cache RAM is bounded by a single budget, the on-disk Pebble stores grow\n")
		b.WriteString("\t// unbounded.\n")
		b.WriteString("\ts.coldCache = coldcache.NewSharedCache(cacheBytes)\n")
		b.WriteString("\tvar err error\n")
		for _, spec := range coldSpecs {
			b.WriteString("\tif s.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold, err = coldcache.OpenWithCache(filepath.Join(dir, ")
			b.WriteString(strconv.Quote(spec.baseName))
			b.WriteString("), s.coldCache, memTableBytes); err != nil {\n\t\t_ = s.CloseColdCache()\n\t\treturn err\n\t}\n")
		}
		b.WriteString("\ts.coldAuthoritative = authoritative\n")
		b.WriteString("\ts.coldDir = dir\n")
		b.WriteString("\ts.coldCacheBytes = cacheBytes\n")
		b.WriteString("\ts.coldMemTableBytes = memTableBytes\n")
		b.WriteString("\treturn nil\n}\n\n")

		b.WriteString("// ReopenColdCacheFresh closes and re-opens the cold tier at its configured\n")
		b.WriteString("// directory (coldcache.Open wipes the dir, so any entries from before a\n")
		b.WriteString("// rollback are discarded). Authoritative stays false until the caller proves\n")
		b.WriteString("// coverage. Reports whether a cold tier is configured; no-op without one.\n")
		b.WriteString("func (s *HotState) ReopenColdCacheFresh() (bool, error) {\n")
		b.WriteString("\tif s == nil || s.coldDir == \"\" {\n\t\treturn false, nil\n\t}\n")
		b.WriteString("\tdir, cacheBytes, memTableBytes := s.coldDir, s.coldCacheBytes, s.coldMemTableBytes\n")
		b.WriteString("\t_ = s.CloseColdCache()\n")
		b.WriteString("\tif err := s.EnableColdCache(dir, false, cacheBytes, memTableBytes); err != nil {\n\t\treturn false, err\n\t}\n")
		b.WriteString("\treturn true, nil\n}\n\n")

		b.WriteString("func (s *HotState) CloseColdCache() error {\n")
		b.WriteString("\tif s == nil {\n\t\treturn nil\n\t}\n")
		b.WriteString("\tvar firstErr error\n")
		for _, spec := range coldSpecs {
			b.WriteString("\tif s.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold != nil {\n\t\tif e := s.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold.Close(); e != nil && firstErr == nil {\n\t\t\tfirstErr = e\n\t\t}\n\t\ts.")
			b.WriteString(spec.baseName)
			b.WriteString(".cold = nil\n\t}\n")
		}
		b.WriteString("\t// Release the shared block cache only after every store sharing it is\n")
		b.WriteString("\t// closed (Pebble ref-counts it).\n")
		b.WriteString("\tif s.coldCache != nil {\n\t\ts.coldCache.Close()\n\t\ts.coldCache = nil\n\t}\n")
		b.WriteString("\ts.coldAuthoritative = false\n")
		b.WriteString("\treturn firstErr\n}\n\n")
	}

	b.WriteString("func (s *HotState) Recover(ctx context.Context, conn *ch.Client, db string) error {\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tif err := s.")
		b.WriteString(spec.baseName)
		b.WriteString(".Recover(ctx, conn, db); err != nil {\n\t\treturn err\n\t}\n")
	}
	b.WriteString("\treturn nil\n}\n\n")

	// Generate Update methods
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("func (s *HotState) Update")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("(value ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(") {\n")
		b.WriteString("\ts.mu.Lock()\n")
		b.WriteString("\tdefer s.mu.Unlock()\n")
		b.WriteString("\ts.")
		b.WriteString(spec.baseName)
		b.WriteString(".Set(value)\n")
		b.WriteString("\ts.dirty")
		b.WriteString(spec.baseName)
		b.WriteString("[New")
		b.WriteString(spec.keyType)
		b.WriteString("(value)] = struct{}{}\n")
		b.WriteString("}\n\n")
	}

	// Generate Commit method
	b.WriteString("func (s *HotState) Commit(ctx context.Context, conn *ch.Client, db string) error {\n")
	b.WriteString("\ts.mu.Lock()\n")
	b.WriteString("\tdefer s.mu.Unlock()\n")
	b.WriteString("\tif conn == nil {\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\t\tclear(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(")\n")
	}
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	// hadWork: true if any non-event table is dirty this commit. Gates the single
	// async-flush barrier below so an empty commit issues no server round-trip.
	b.WriteString("\thadWork := ")
	hadWorkFirst := true
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		if !hadWorkFirst {
			b.WriteString(" || ")
		}
		b.WriteString("len(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(") > 0")
		hadWorkFirst = false
	}
	if hadWorkFirst {
		b.WriteString("false")
	}
	b.WriteString("\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tif len(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(") > 0 {\n")
		b.WriteString("\t\tbatch := New")
		b.WriteString(spec.batchType)
		b.WriteString("()\n")
		b.WriteString("\t\tfor key := range s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(" {\n")
		b.WriteString("\t\t\tif val, ok := s.")
		b.WriteString(spec.baseName)
		b.WriteString(".Get(key); ok {\n")
		b.WriteString("\t\t\t\tbatch.Append(val)\n")
		b.WriteString("\t\t\t}\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tif err := batch.Insert(ctx, conn, db); err != nil {\n")
		b.WriteString("\t\t\treturn err\n")
		b.WriteString("\t\t}\n")
		b.WriteString("\t\tclear(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(")\n")
		b.WriteString("\t}\n")
	}
	// Single async-flush barrier: the per-table inserts above are
	// wait_for_async_insert=0, so this one server flush makes all of them durable
	// and queryable before Commit returns (still under s.mu), preserving the
	// recovery/rollback/resolver read-back invariant at one flush per commit
	// instead of one wait per table insert.
	b.WriteString("\tif hadWork {\n")
	b.WriteString("\t\tif err := conn.Do(ctx, ch.Query{Body: \"SYSTEM FLUSH ASYNC INSERT QUEUE\"}); err != nil {\n")
	b.WriteString("\t\t\treturn err\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n}\n")

	// Generate Restore methods for journal rollback
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("func (s *HotState) Restore")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("(key ")
		b.WriteString(spec.keyType)
		b.WriteString(", value ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(", had bool) {\n")
		b.WriteString("\ts.mu.Lock()\n")
		b.WriteString("\tdefer s.mu.Unlock()\n")
		b.WriteString("\tif had {\n")
		b.WriteString("\t\ts.")
		b.WriteString(spec.baseName)
		b.WriteString(".SetByKey(key, value)\n")
		b.WriteString("\t\ts.dirty")
		b.WriteString(spec.baseName)
		b.WriteString("[key] = struct{}{}\n")
		b.WriteString("\t\treturn\n")
		b.WriteString("\t}\n")
		b.WriteString("\ts.")
		b.WriteString(spec.baseName)
		b.WriteString(".Delete(key)\n")
		b.WriteString("\tdelete(s.dirty")
		b.WriteString(spec.baseName)
		b.WriteString(", key)\n")
		b.WriteString("}\n\n")
	}
}

func renderHotStateHelpers(b *bytes.Buffer, tables []customTableSpec, events []eventSpec) {
	// Shared FNV-1a byte fold used by every clock cache's flat index (A3). The
	// index is a pointer-free open-chained hash over an arena (buckets []int32 head
	// + next []int32 chain), so the GC scans two flat integer slices instead of the
	// millions of boxed interface objects a sync.Map[key]idx allocated.
	b.WriteString(`
func clockHash64(seed uint64, b []byte) uint64 {
	h := seed
	for _, x := range b {
		h ^= uint64(x)
		h *= 1099511628211
	}
	return h
}
`)
	if customTablesUseBool(tables) {
		b.WriteString("\nfunc hotStateBool(v bool) uint8 {\n\tif v {\n\t\treturn 1\n\t}\n\treturn 0\n}\n")
		b.WriteString("\nfunc hotStateBoolSQL(v bool) string {\n\tif v {\n\t\treturn \"1\"\n\t}\n\treturn \"0\"\n}\n")
	}
	if customTablesUseUint256(tables) || customTablesUseUint256Slice(tables) ||
		eventsUseUint256(events) || eventsUseUint256Slice(events) {
		b.WriteString(`
func hotStateUInt256(v uint256.Int) proto.UInt256 {
	return proto.UInt256{
		Low:  proto.UInt128{Low: v[0], High: v[1]},
		High: proto.UInt128{Low: v[2], High: v[3]},
	}
}

func hotStateUint256(v proto.UInt256) uint256.Int {
	return uint256.Int{v.Low.Low, v.Low.High, v.High.Low, v.High.High}
}
`)
	}
	if customTablesUseDecimal(tables) {
		b.WriteString(`
func hotStateDecimalToDecimal256(d decimal.Decimal) protomath.Decimal256 {
	out, _ := protomath.FromDecimal256ScaledBigInt(d.Shift(18).BigInt())
	return out
}

func hotStateDecimalFromDecimal256(v protomath.Decimal256) decimal.Decimal {
	return decimal.NewFromBigInt(v.ScaledBig(), -18)
}
`)
	}
	if customTablesUseType(tables, "protomath.Decimal256") {
		b.WriteString(`
type decimal256Col struct {
	proto.ColDecimal256
}

func (c *decimal256Col) Type() proto.ColumnType {
	return proto.ColumnType("Decimal(76, 18)")
}
`)
	}
	if customTablesUseHashSlice(tables) {
		b.WriteString(`
func hotStateHashSliceBytes(values []common.Hash, scratch [][]byte) [][]byte {
	scratch = scratch[:0]
	for _, value := range values {
		scratch = append(scratch, value.Bytes())
	}
	return scratch
}

func hotStateHashSlice(values [][]byte) []common.Hash {
	out := make([]common.Hash, 0, len(values))
	for _, value := range values {
		out = append(out, common.BytesToHash(value))
	}
	return out
}
`)
	}
	if customTablesUseUint256Slice(tables) || eventsUseUint256Slice(events) {
		b.WriteString(`
func hotStateUInt256Slice(values []uint256.Int, scratch []proto.UInt256) []proto.UInt256 {
	scratch = scratch[:0]
	for _, value := range values {
		scratch = append(scratch, hotStateUInt256(value))
	}
	return scratch
}

func hotStateUint256Slice(values []proto.UInt256) []uint256.Int {
	out := make([]uint256.Int, 0, len(values))
	for _, value := range values {
		out = append(out, hotStateUint256(value))
	}
	return out
}
`)
	}
}

func renderClockKeyParams(b *bytes.Buffer, fields []customFieldSpec) {
	for i, field := range fields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(lowerFirst(field.Name))
		b.WriteString(" ")
		b.WriteString(field.Type)
	}
}

func hotStateSpecs(tables []customTableSpec) []hotStateSpec {
	used := make(map[string]int)
	specs := make([]hotStateSpec, 0, len(tables))
	for _, table := range tables {
		var base string
		if table.BaseName != "" {
			base = uniqueExported(used, table.BaseName)
		} else {
			base = uniqueExported(used, customClockBaseName(table.GoTypeName))
		}
		specs = append(specs, hotStateSpec{
			table:     table,
			baseName:  base,
			keyType:   base + "ClockKey",
			entryType: base + "ClockEntry",
			cacheType: base + "ClockCache",
			batchType: table.GoTypeName + "Batch",
		})
	}
	return specs
}

func customClockBaseName(typeName string) string {
	name := strings.TrimPrefix(customTableEntityName(typeName), "Memory")
	return pluralizeGoName(name)
}

func pluralizeGoName(name string) string {
	switch {
	case name == "":
		return "Entities"
	case strings.HasSuffix(name, "s"), strings.HasSuffix(name, "S"):
		return name
	case strings.HasSuffix(name, "y"):
		return strings.TrimSuffix(name, "y") + "ies"
	case strings.HasSuffix(name, "Y"):
		return strings.TrimSuffix(name, "Y") + "ies"
	default:
		return name + "s"
	}
}

func lowerFirst(name string) string {
	if name == "" {
		return "value"
	}
	if name == strings.ToUpper(name) {
		return strings.ToLower(name)
	}
	return strings.ToLower(name[:1]) + name[1:]
}

func sortedImportKeys(imports map[string]string) []string {
	keys := make([]string, 0, len(imports))
	for key := range imports {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func batchColumnField(field customFieldSpec) string {
	return "col" + field.Name
}

func batchScratchField(field customFieldSpec) string {
	switch field.Type {
	case "[]common.Hash", "[]uint256.Int":
		return "scratch" + field.Name
	default:
		return ""
	}
}

func batchScratchType(field customFieldSpec) string {
	switch field.Type {
	case "[]common.Hash":
		return "[][]byte"
	case "[]uint256.Int":
		return "[]proto.UInt256"
	default:
		return ""
	}
}

// memoryGoType returns the in-memory Go type for a hot-state value-struct field,
// which may differ from the schema/source type to keep the rings pointer-free
// (A2). Timestamps are stored as int64 unix-millis in memory — the ClickHouse
// column stays DateTime64(3, 'UTC') — so MemoryUserPosition et al. carry no
// *time.Location pointer and the GC skips the whole ring backing array on every
// mark, instead of scanning all N entries. Conversions happen at Append/Recover
// (see batchAppendLines / resultValueExpr) and at assignment (state.go Save).
func memoryGoType(field customFieldSpec, isEvent bool) string {
	// Event value-structs embed EventMeta (shared with the ingestion/handler layer,
	// where BlockTimestamp is a time.Time), so they keep time.Time. Only the derived
	// entity rings (UserPositions et al.) — the ones that grow to capacity — are
	// converted to int64 to make their backing arrays pointer-free.
	if isEvent {
		return field.Type
	}
	switch field.Type {
	case "time.Time":
		return "int64"
	default:
		return field.Type
	}
}

func batchColumnType(field customFieldSpec) string {
	switch field.Type {
	case "bool", "uint8":
		return "proto.ColUInt8"
	case "uint16":
		return "proto.ColUInt16"
	case "uint32":
		return "proto.ColUInt32"
	case "uint", "uint64":
		return "proto.ColUInt64"
	case "int8":
		return "proto.ColInt8"
	case "int16":
		return "proto.ColInt16"
	case "int32":
		return "proto.ColInt32"
	case "int", "int64":
		return "proto.ColInt64"
	case "float32":
		return "proto.ColFloat32"
	case "float64":
		return "proto.ColFloat64"
	case "string", "[]byte":
		return "proto.ColStr"
	case "time.Time":
		return "proto.ColDateTime64"
	case "common.Address", "common.Hash":
		return "proto.ColFixedStr"
	case "uint256.Int":
		return "proto.ColUInt256"
	case "decimal.Decimal":
		return "decimal256Col"
	case "protomath.Decimal256":
		return "decimal256Col"
	case "[]common.Hash":
		return "*proto.ColArr[[]byte]"
	case "[]uint256.Int":
		return "*proto.ColArr[proto.UInt256]"
	case "[]string":
		return "*proto.ColArr[string]"
	default:
		return "proto.ColStr"
	}
}

func resultColumnType(field customFieldSpec) string {
	return batchColumnType(field)
}

func batchInitLines(field customFieldSpec) []string {
	return initLines("b.", field)
}

func resultInitLines(field customFieldSpec) []string {
	if field.Type == "decimal.Decimal" {
		return nil
	}
	return initLines("", field)
}

func initLines(prefix string, field customFieldSpec) []string {
	col := prefix + batchColumnField(field)
	switch field.Type {
	case "common.Address":
		return []string{col + ".SetSize(20)"}
	case "common.Hash":
		return []string{col + ".SetSize(32)"}
	case "time.Time":
		return []string{col + ".WithPrecision(proto.Precision(3))", col + ".WithLocation(time.UTC)"}
	case "[]common.Hash":
		return []string{col + " = (&proto.ColFixedStr{Size: 32}).Array()"}
	case "[]uint256.Int":
		return []string{col + " = new(proto.ColUInt256).Array()"}
	case "[]string":
		return []string{col + " = new(proto.ColStr).Array()"}
	default:
		return nil
	}
}

func batchInputData(field customFieldSpec) string {
	col := "b." + batchColumnField(field)
	switch field.Type {
	case "decimal.Decimal", "protomath.Decimal256":
		return "&" + col
	case "[]common.Hash", "[]uint256.Int", "[]string":
		return col
	default:
		return "&" + col
	}
}

func resultData(field customFieldSpec) string {
	col := batchColumnField(field)
	switch field.Type {
	case "decimal.Decimal", "protomath.Decimal256":
		return "&" + col
	case "[]common.Hash", "[]uint256.Int", "[]string":
		return col
	default:
		return "&" + col
	}
}

func batchColumnRowsExpr(field customFieldSpec) string {
	col := "b." + batchColumnField(field)
	if strings.HasPrefix(field.Type, "[]") {
		return col + ".Rows()"
	}
	return col + ".Rows()"
}

func batchAppendLines(field customFieldSpec, isEvent bool) []string {
	col := "b." + batchColumnField(field)
	value := "item." + field.Name
	if !isEvent && field.Type == "time.Time" {
		// In-memory value is int64 unix-millis (A2); the DateTime64(3) column's raw
		// units are also milliseconds, so append the raw value directly — no
		// time.Time is constructed on the hot insert path.
		return []string{col + ".AppendRaw(proto.DateTime64(" + value + "))"}
	}
	switch field.Type {
	case "common.Address", "common.Hash":
		return []string{col + ".Append(" + value + ".Bytes())"}
	case "bool":
		return []string{col + ".Append(hotStateBool(" + value + "))"}
	case "[]byte":
		return []string{col + ".AppendBytes(" + value + ")"}
	case "decimal.Decimal":
		return []string{col + ".Append(hotStateDecimalToDecimal256(" + value + ").Proto())"}
	case "protomath.Decimal256":
		return []string{col + ".Append(" + value + ".Proto())"}
	case "uint256.Int":
		return []string{col + ".Append(hotStateUInt256(" + value + "))"}
	case "[]common.Hash":
		return []string{col + ".Append(hotStateHashSliceBytes(" + value + ", b." + batchScratchField(field) + "))"}
	case "[]uint256.Int":
		return []string{col + ".Append(hotStateUInt256Slice(" + value + ", b." + batchScratchField(field) + "))"}
	default:
		return []string{col + ".Append(" + value + ")"}
	}
}

func resultValueExpr(field customFieldSpec, isEvent bool) string {
	col := batchColumnField(field)
	if !isEvent && field.Type == "time.Time" {
		// Recover path (cold): read the DateTime64 instant back as int64 unix-millis
		// to match the in-memory representation (A2). UnixMilli is timezone-
		// independent, so it round-trips the millisecond raw value exactly.
		return col + ".Row(i).UnixMilli()"
	}
	switch field.Type {
	case "common.Address":
		return "common.BytesToAddress(" + col + ".Row(i))"
	case "common.Hash":
		return "common.BytesToHash(" + col + ".Row(i))"
	case "bool":
		return col + ".Row(i) != 0"
	case "[]byte":
		return "append([]byte(nil), " + col + ".RowBytes(i)...)"
	case "decimal.Decimal":
		return "hotStateDecimalFromDecimal256(protomath.Decimal256(" + col + ".Row(i)))"
	case "protomath.Decimal256":
		return "protomath.Decimal256(" + col + ".Row(i))"
	case "uint256.Int":
		return "hotStateUint256(" + col + ".Row(i))"
	case "[]common.Hash":
		return "hotStateHashSlice(" + col + ".Row(i))"
	case "[]uint256.Int":
		return "hotStateUint256Slice(" + col + ".Row(i))"
	default:
		return col + ".Row(i)"
	}
}

func customInsertColumnList(table customTableSpec) string {
	columns := make([]string, 0, len(table.Columns))
	for _, column := range table.Columns {
		columns = append(columns, quoteSQLIdent(column.Name))
	}
	return "(" + strings.Join(columns, ", ") + ")"
}

// recoverQuery returns the latest row per primary key from a ReplacingMergeTree
// state table. It uses argMax(col, version) ... GROUP BY key in deterministic
// primary-key ranges when the leading key is FixedString. A single global
// aggregation is fastest when it fits, but the live polymarket positions table
// can require >50 GiB of temp space; bucketed aggregation preserves the same
// result while bounding each ClickHouse query and letting ClickHouse prune by
// primary key. Non-FixedString keys fall back to hash buckets.
// version is the (block_number, transaction_index, log_index) tuple — the same
// ordering LIMIT 1 BY would use — so the selected row is identical. Key columns
// are emitted as the GROUP BY key; every other column, including version columns,
// takes argMax over the version tuple. Result columns keep their original names
// via AS, so the columnar decode that maps by name is unchanged.
func recoverQuery(table customTableSpec) string {
	// Recover the latest row per primary key by streaming the part in reverse
	// sorting-key order (optimize_read_in_order) and taking the first row seen for
	// each key via LIMIT 1 BY. The memory_* tables are ReplacingMergeTree ORDER BY
	// (pk..., block_number, transaction_index, log_index), so a full-key DESC scan
	// visits each key's highest (block_number, transaction_index, log_index) — its
	// latest version — first.
	//
	// This deliberately avoids `argMax(col, version) GROUP BY key`: argMax builds an
	// aggregation hash table with one entry per distinct key, which on the 129M-key
	// memory_user_positions table costs ~50 GiB of RAM and ~350s. The read-in-order
	// stream holds <1 GiB (no per-key state) and is bounded only by decompression
	// throughput. Every column is selected directly (no aggregate), so the version
	// columns are read as-is and the `t` alias is only needed to qualify the bucket
	// WHERE / ORDER BY against the (range- or hash-) bucket predicate.
	q := func(col string) string { return "`t`." + quoteSQLIdent(col) }
	selects := make([]string, 0, len(table.Fields))
	for _, field := range table.Fields {
		selects = append(selects, q(field.ColumnName)+" AS "+quoteSQLIdent(field.ColumnName))
	}
	orderBy := make([]string, 0, len(table.PrimaryKey)+3)
	for _, k := range table.PrimaryKey {
		orderBy = append(orderBy, q(k)+" DESC")
	}
	orderBy = append(orderBy, q("block_number")+" DESC", q("transaction_index")+" DESC", q("log_index")+" DESC")
	limitBy := make([]string, 0, len(table.PrimaryKey))
	for _, k := range table.PrimaryKey {
		limitBy = append(limitBy, q(k))
	}
	return "SELECT " + strings.Join(selects, ", ") + " FROM %s.%s AS `t` WHERE %s ORDER BY " + strings.Join(orderBy, ", ") + " LIMIT 1 BY " + strings.Join(limitBy, ", ") + " SETTINGS optimize_read_in_order = 1"
}

func recoverWhereExpr(table customTableSpec) string {
	if len(table.PrimaryKey) == 0 {
		return strconv.Quote("1")
	}
	firstKey := table.PrimaryKey[0]
	for _, field := range table.Fields {
		if field.ColumnName != firstKey {
			continue
		}
		if size, ok := fixedStringColumnSize(field.ColumnType); ok {
			return fmt.Sprintf("recoveryFixedStringRange(%s, bucket, %d)", strconv.Quote("`t`."+quoteSQLIdent(firstKey)), size)
		}
		break
	}
	q := func(col string) string { return "`t`." + quoteSQLIdent(col) }
	hashCols := make([]string, 0, len(table.PrimaryKey))
	for _, k := range table.PrimaryKey {
		hashCols = append(hashCols, q(k))
	}
	return "fmt.Sprintf(" + strconv.Quote("cityHash64("+strings.Join(hashCols, ", ")+") %% %d = %d") + ", recoveryBucketCount, bucket)"
}

func fixedStringColumnSize(chType string) (int, bool) {
	const prefix = "FixedString("
	if !strings.HasPrefix(chType, prefix) || !strings.HasSuffix(chType, ")") {
		return 0, false
	}
	n, err := strconv.Atoi(strings.TrimSuffix(strings.TrimPrefix(chType, prefix), ")"))
	if err != nil || n <= 0 {
		return 0, false
	}
	return n, true
}

func quotedColumns(columns []string) []string {
	out := make([]string, 0, len(columns))
	for _, column := range columns {
		out = append(out, quoteSQLIdent(column))
	}
	return out
}

func customTablesUseDecimal(tables []customTableSpec) bool {
	return customTablesUseType(tables, "decimal.Decimal")
}

func customTablesUseBool(tables []customTableSpec) bool {
	return customTablesUseType(tables, "bool")
}

func customTablesUseUint256(tables []customTableSpec) bool {
	return customTablesUseType(tables, "uint256.Int")
}

func customTablesUseHashSlice(tables []customTableSpec) bool {
	return customTablesUseType(tables, "[]common.Hash")
}

func customTablesUseUint256Slice(tables []customTableSpec) bool {
	return customTablesUseType(tables, "[]uint256.Int")
}

func eventsUseUint256(events []eventSpec) bool {
	return eventsUseType(events, "uint256.Int")
}

func eventsUseUint256Slice(events []eventSpec) bool {
	return eventsUseType(events, "[]uint256.Int")
}

func eventsUseType(events []eventSpec, typ string) bool {
	for _, ev := range events {
		for _, arg := range ev.Args {
			if arg.GoType == typ {
				return true
			}
		}
	}
	return false
}

func customTablesUseType(tables []customTableSpec, typ string) bool {
	for _, table := range tables {
		for _, field := range table.Fields {
			if field.Type == typ {
				return true
			}
		}
	}
	return false
}

// isPointerFreeEntity reports whether the entity's in-memory value AND key are
// free of pointers/slices/strings, so they can be stored in the Pebble cold tier
// as raw bytes via unsafe memcpy (zero-transformation). Slice-bearing entities
// (e.g. Array(UInt256) payouts, Array(FixedString(32)) question_ids) are excluded
// and keep the ClickHouse-fallback lazy-load path. Note: memoryGoType maps
// time.Time -> int64 for non-event entities, so timestamps don't disqualify them.
func isPointerFreeEntity(table customTableSpec) bool {
	notFlat := func(t string) bool {
		return strings.HasPrefix(t, "[]") || strings.HasPrefix(t, "*") ||
			strings.HasPrefix(t, "map[") || strings.Contains(t, "string") ||
			t == "time.Time"
	}
	for _, field := range table.Fields {
		if notFlat(memoryGoType(field, table.IsEvent)) {
			return false
		}
	}
	for _, field := range table.keyFields() {
		if notFlat(field.Type) {
			return false
		}
	}
	return true
}

// entityUsesCold reports whether a (non-event) entity participates in the Pebble
// cold tier. Events are append-only (no lazy Get-by-key), so they never need it.
// Every derived state entity does: pointer-free values are spilled/served as raw
// bytes (unsafe memcpy), slice-bearing values via the generated byte codec
// (entityUsesSerializedCold). Keeping slice-bearing entities (e.g. Condition's
// []uint256.Int payouts) OUT of the cold tier was the root of the resumed-run
// ClickHouse point-SELECT storm: once their hot ring evicted, every miss fell
// back to a synchronous CH lookup with no disk tier to absorb it.
func entityUsesCold(table customTableSpec) bool {
	return !table.IsEvent
}

// entityUsesSerializedCold reports whether a cold entity must use the generated
// byte codec (encode/decode) rather than the zero-copy unsafe memcpy: true when
// its in-memory value carries a slice/pointer field that can't be blitted as raw
// struct bytes. The KEY stays fixed-size (pointer-free) in both cases, so the
// cold lookup key is always an unsafe slice of the key struct.
func entityUsesSerializedCold(table customTableSpec) bool {
	return entityUsesCold(table) && !isPointerFreeEntity(table)
}

// customTablesUseColdCache reports whether any entity can use the cold tier;
// drives the "unsafe" + "path/filepath" imports in the generated hot state.
func customTablesUseColdCache(tables []customTableSpec) bool {
	for _, table := range tables {
		if entityUsesCold(table) {
			return true
		}
	}
	return false
}

// customTablesUseSerializedCold reports whether any cold entity needs the byte
// codec (drives the "encoding/binary" import and the shared codec helpers).
func customTablesUseSerializedCold(tables []customTableSpec) bool {
	for _, table := range tables {
		if entityUsesSerializedCold(table) {
			return true
		}
	}
	return false
}

func renderBatchResolver(b *bytes.Buffer, spec hotStateSpec) {
	resolverType := spec.table.GoTypeName + "BatchResolver"
	cacheType := spec.cacheType
	keyType := spec.keyType
	valueType := spec.table.GoTypeName

	b.WriteString("type ")
	b.WriteString(resolverType)
	b.WriteString(" struct {\n\tcache  *")
	b.WriteString(cacheType)
	b.WriteString("\n\tmisses []")
	b.WriteString(keyType)
	b.WriteString("\n}\n\n")

	b.WriteString("func New")
	b.WriteString(resolverType)
	b.WriteString("(cache *")
	b.WriteString(cacheType)
	b.WriteString(") *")
	b.WriteString(resolverType)
	b.WriteString(" {\n\treturn &")
	b.WriteString(resolverType)
	b.WriteString("{\n\t\tcache: cache,\n\t}\n}\n\n")

	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Queue(key ")
	b.WriteString(keyType)
	b.WriteString(") {\n\tif _, ok := r.cache.Get(key); !ok {\n\t\tr.misses = append(r.misses, key)\n\t}\n}\n\n")

	b.WriteString("// Pending reports how many missed keys are queued for the next Resolve.\n")
	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Pending() int {\n\treturn len(r.misses)\n}\n\n")

	b.WriteString("func (r *")
	b.WriteString(resolverType)
	b.WriteString(") Resolve(ctx context.Context, conn *ch.Client, db string) error {\n")
	b.WriteString("\tif len(r.misses) == 0 {\n\t\treturn nil\n\t}\n\n")
	b.WriteString("\tuniqueKeys := make(map[")
	b.WriteString(keyType)
	b.WriteString("]struct{})\n")
	b.WriteString("\tvar uniqueList []")
	b.WriteString(keyType)
	b.WriteString("\n\tfor _, key := range r.misses {\n")
	b.WriteString("\t\tif _, ok := uniqueKeys[key]; !ok {\n")
	b.WriteString("\t\t\tuniqueKeys[key] = struct{}{}\n")
	b.WriteString("\t\t\tuniqueList = append(uniqueList, key)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tr.misses = nil\n\n")
	b.WriteString("\tif len(uniqueList) == 0 {\n\t\treturn nil\n\t}\n\n")
	b.WriteString("\tfoundKeys := make(map[")
	b.WriteString(keyType)
	b.WriteString("]struct{})\n")
	b.WriteString("\tconst resolverChunkSize = 4000\n")
	b.WriteString("\tfor chunkStart := 0; chunkStart < len(uniqueList); chunkStart += resolverChunkSize {\n")
	b.WriteString("\t\tchunkEnd := chunkStart + resolverChunkSize\n")
	b.WriteString("\t\tif chunkEnd > len(uniqueList) {\n\t\t\tchunkEnd = len(uniqueList)\n\t\t}\n")
	b.WriteString("\t\tchunk := uniqueList[chunkStart:chunkEnd]\n\n")

	keyFields := spec.table.keyFields()
	if len(keyFields) > 1 && keyFieldsExternalFixed(keyFields) {
		for _, field := range keyFields {
			colName := "keyCol" + field.Name
			size := 32
			if field.Type == "common.Address" {
				size = 20
			}
			b.WriteString("\t\tvar ")
			b.WriteString(colName)
			b.WriteString(" proto.ColFixedStr\n")
			b.WriteString("\t\t")
			b.WriteString(colName)
			b.WriteString(".SetSize(")
			b.WriteString(strconv.Itoa(size))
			b.WriteString(")\n")
		}
		b.WriteString("\t\tfor _, key := range chunk {\n")
		for _, field := range keyFields {
			b.WriteString("\t\t\tkeyCol")
			b.WriteString(field.Name)
			b.WriteString(".Append(key.")
			b.WriteString(field.Name)
			b.WriteString(".Bytes())\n")
		}
		b.WriteString("\t\t}\n\n")
		queryBody := fmt.Sprintf("SELECT %s FROM %%s.%s AS `t` INNER JOIN _resolver_keys AS `k` ON %s ORDER BY `t`.`block_number` DESC, `t`.`transaction_index` DESC, `t`.`log_index` DESC LIMIT 1 BY %s",
			customSelectColumnListQualified(spec.table, "`t`"),
			spec.table.Name,
			keyJoinCondition(keyFields, "`t`", "`k`"),
			keyColumnExpressionListQualified(keyFields, "`t`"),
		)
		b.WriteString(fmt.Sprintf("\t\tqueryStr := fmt.Sprintf(%s, quoteIdent(db))\n\n",
			strconv.Quote(queryBody),
		))
	} else if len(keyFields) > 1 {
		b.WriteString("\t\tvar values []string\n")
		b.WriteString("\t\tfor _, key := range chunk {\n")
		b.WriteString("\t\t\tvalues = append(values, \"(\"")
		for i, field := range keyFields {
			if i > 0 {
				b.WriteString(" + \", \"")
			}
			b.WriteString(" + ")
			b.WriteString(keySQLValueExpr("key."+field.Name, field))
		}
		b.WriteString(" + \")\")\n")
		b.WriteString("\t\t}\n\n")

		queryBody := fmt.Sprintf("SELECT %s FROM %%s.%s WHERE %s IN (%%s) ORDER BY `block_number` DESC, `transaction_index` DESC, `log_index` DESC LIMIT 1 BY %s",
			customSelectColumnList(spec.table),
			spec.table.Name,
			customInsertColumnList(customTableSpec{Columns: keyColumns(keyFields)}),
			keyColumnExpressionList(keyFields),
		)
		b.WriteString(fmt.Sprintf("\t\tqueryStr := fmt.Sprintf(%s, quoteIdent(db), strings.Join(values, \", \"))\n\n",
			strconv.Quote(queryBody),
		))
	} else if len(keyFields) == 1 {
		b.WriteString("\t\tvar values []string\n")
		b.WriteString("\t\tfor _, key := range chunk {\n")
		keyField := keyFields[0]
		b.WriteString("\t\t\tvalues = append(values, ")
		b.WriteString(keySQLValueExpr("key."+keyField.Name, keyField))
		b.WriteString(")\n")
		b.WriteString("\t\t}\n\n")

		queryBody := fmt.Sprintf("SELECT %s FROM %%s.%s WHERE %s IN (%%s) ORDER BY `block_number` DESC, `transaction_index` DESC, `log_index` DESC LIMIT 1 BY %s",
			customSelectColumnList(spec.table),
			spec.table.Name,
			quoteSQLIdent(keyField.ColumnName),
			keyColumnExpressionList(keyFields),
		)
		b.WriteString(fmt.Sprintf("\t\tqueryStr := fmt.Sprintf(%s, quoteIdent(db), strings.Join(values, \", \"))\n\n",
			strconv.Quote(queryBody),
		))
	} else {
		b.WriteString("\t\tqueryStr := \"\"\n")
	}

	b.WriteString("\t\tvar (\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t\t")
		b.WriteString(batchColumnField(field))
		b.WriteString(" ")
		b.WriteString(resultColumnType(field))
		b.WriteString("\n")
	}
	b.WriteString("\t\t)\n")
	for _, field := range spec.table.Fields {
		for _, line := range resultInitLines(field) {
			b.WriteString("\t\t")
			b.WriteString(line)
			b.WriteString("\n")
		}
	}
	b.WriteString("\t\tresults := proto.Results{\n")
	for _, field := range spec.table.Fields {
		b.WriteString("\t\t\t{Name: ")
		b.WriteString(strconv.Quote(field.ColumnName))
		b.WriteString(", Data: ")
		b.WriteString(resultData(field))
		b.WriteString("},\n")
	}
	b.WriteString("\t\t}\n")

	b.WriteString("\t\tq := ch.Query{\n")
	b.WriteString("\t\t\tBody:   queryStr,\n")
	b.WriteString("\t\t\tResult: results,\n")
	b.WriteString("\t\t\tSettings: []ch.Setting{{Key: \"max_query_size\", Value: \"10485760\"}},\n")
	if len(keyFields) > 1 && keyFieldsExternalFixed(keyFields) {
		b.WriteString("\t\t\tExternalTable: \"_resolver_keys\",\n")
		b.WriteString("\t\t\tExternalData: []proto.InputColumn{\n")
		for _, field := range keyFields {
			b.WriteString("\t\t\t\t{Name: ")
			b.WriteString(strconv.Quote(field.ColumnName))
			b.WriteString(", Data: keyCol")
			b.WriteString(field.Name)
			b.WriteString("},\n")
		}
		b.WriteString("\t\t\t},\n")
	}
	b.WriteString("\t\t\tOnResult: func(ctx context.Context, block proto.Block) error {\n")
	b.WriteString("\t\t\t\tfor i := 0; i < block.Rows; i++ {\n")
	b.WriteString("\t\t\t\t\titem := ")
	b.WriteString(valueType)
	b.WriteString("{\n")
	if spec.table.IsEvent {
		b.WriteString("\t\t\t\t\t\tEventMeta: EventMeta{\n")
		for _, field := range spec.table.Fields {
			if field.Name == "BlockNumber" || field.Name == "BlockTimestamp" || field.Name == "TransactionIndex" || field.Name == "LogIndex" {
				b.WriteString("\t\t\t\t\t\t\t")
				b.WriteString(field.Name)
				b.WriteString(": ")
				b.WriteString(resultValueExpr(field, spec.table.IsEvent))
				b.WriteString(",\n")
			}
		}
		b.WriteString("\t\t\t\t\t\t},\n")
		for _, field := range spec.table.Fields {
			if !(field.Name == "BlockNumber" || field.Name == "BlockTimestamp" || field.Name == "TransactionIndex" || field.Name == "LogIndex") {
				b.WriteString("\t\t\t\t\t\t")
				b.WriteString(field.Name)
				b.WriteString(": ")
				b.WriteString(resultValueExpr(field, spec.table.IsEvent))
				b.WriteString(",\n")
			}
		}
	} else {
		for _, field := range spec.table.Fields {
			b.WriteString("\t\t\t\t\t\t")
			b.WriteString(field.Name)
			b.WriteString(": ")
			b.WriteString(resultValueExpr(field, spec.table.IsEvent))
			b.WriteString(",\n")
		}
	}
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t\tr.cache.Set(item)\n")
	b.WriteString("\t\t\t\t\tfoundKeys[New")
	b.WriteString(keyType)
	b.WriteString("(item)] = struct{}{}\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t\treturn nil\n")
	b.WriteString("\t\t\t},\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\tif err := conn.Do(ctx, q); err != nil {\n\t\t\treturn err\n\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\tfor _, key := range uniqueList {\n")
	b.WriteString("\t\tif _, found := foundKeys[key]; !found {\n")
	b.WriteString("\t\t\ttombstone := ")
	b.WriteString(valueType)
	b.WriteString("{Tombstone: true}\n")
	for _, field := range keyFields {
		b.WriteString("\t\t\ttombstone.")
		b.WriteString(field.Name)
		b.WriteString(" = key.")
		b.WriteString(field.Name)
		b.WriteString("\n")
	}
	b.WriteString("\t\t\tr.cache.SetByKey(key, tombstone)\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

func keySQLValueExpr(expr string, field customFieldSpec) string {
	switch field.Type {
	case "common.Address", "common.Hash":
		return fmt.Sprintf("fmt.Sprintf(\"unhex('%%s')\", strings.TrimPrefix(%s.Hex(), \"0x\"))", expr)
	case "string":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", strings.ReplaceAll(%s, \"'\", \"''\"))", expr)
	case "bool":
		return fmt.Sprintf("hotStateBoolSQL(%s)", expr)
	case "uint256.Int":
		return expr + ".Dec()"
	case "decimal.Decimal":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.String())", expr)
	case "protomath.Decimal256":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.String(protomath.Decimal256Scale18))", expr)
	case "float32", "float64":
		return fmt.Sprintf("fmt.Sprintf(\"%%v\", %s)", expr)
	case "time.Time":
		return fmt.Sprintf("fmt.Sprintf(\"'%%s'\", %s.UTC().Format(time.RFC3339Nano))", expr)
	default:
		return fmt.Sprintf("fmt.Sprintf(\"%%d\", %s)", expr)
	}
}

func customSelectColumnList(table customTableSpec) string {
	selects := make([]string, 0, len(table.Fields))
	for _, field := range table.Fields {
		selects = append(selects, quoteSQLIdent(field.ColumnName))
	}
	return strings.Join(selects, ", ")
}

func customSelectColumnListQualified(table customTableSpec, alias string) string {
	selects := make([]string, 0, len(table.Fields))
	for _, field := range table.Fields {
		col := quoteSQLIdent(field.ColumnName)
		selects = append(selects, alias+"."+col+" AS "+col)
	}
	return strings.Join(selects, ", ")
}

func keyColumns(fields []customFieldSpec) []customColumnSpec {
	out := make([]customColumnSpec, 0, len(fields))
	for _, f := range fields {
		out = append(out, customColumnSpec{Name: f.ColumnName})
	}
	return out
}

func keyColumnExpressionList(fields []customFieldSpec) string {
	out := make([]string, 0, len(fields))
	for _, field := range fields {
		out = append(out, quoteSQLIdent(field.ColumnName))
	}
	return strings.Join(out, ", ")
}

func keyColumnExpressionListQualified(fields []customFieldSpec, alias string) string {
	out := make([]string, 0, len(fields))
	for _, field := range fields {
		out = append(out, alias+"."+quoteSQLIdent(field.ColumnName))
	}
	return strings.Join(out, ", ")
}

func keyJoinCondition(fields []customFieldSpec, leftAlias, rightAlias string) string {
	out := make([]string, 0, len(fields))
	for _, field := range fields {
		col := quoteSQLIdent(field.ColumnName)
		out = append(out, leftAlias+"."+col+" = "+rightAlias+"."+col)
	}
	return strings.Join(out, " AND ")
}

func keyFieldsExternalFixed(fields []customFieldSpec) bool {
	for _, field := range fields {
		if field.Type != "common.Address" && field.Type != "common.Hash" {
			return false
		}
	}
	return len(fields) > 0
}

func findStateEventSpec(events []eventSpec, state config.StateConfig) (*eventSpec, error) {
	if state.SourceTable != "" {
		for _, ev := range events {
			if ev.TableName == state.SourceTable {
				return &ev, nil
			}
		}
	}
	// Try to resolve from state.Name
	for _, ev := range events {
		if strings.EqualFold(ev.EventName, state.Name) || strings.EqualFold(ev.GoTypeName, state.Name) {
			return &ev, nil
		}
	}
	// Fallback: try to see if any event table contains the state name
	for _, ev := range events {
		if strings.Contains(strings.ToLower(ev.TableName), strings.ToLower(state.Name)) {
			return &ev, nil
		}
	}
	return nil, fmt.Errorf("source table or event matching %q not found in event tables", state.Name)
}
