package codegen

import (
	"bytes"
	"go/format"
	"strconv"
	"strings"
)

func generateInserterGo(events []eventSpec) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/ClickHouse/ch-go"
	"github.com/ClickHouse/ch-go/proto"
	"github.com/ethereum/go-ethereum/common"
	"github.com/holiman/uint256"
)

type ClickHouseEventBatch interface {
	TableName() string
	ColumnNames() []string
	Inputs() []proto.InputColumn
	Rows() int
	Reset()
	Append(meta EventMeta, value any) bool
}

var ClickHouseCommonColumnNames = []string{
	"chain_id",
	"block_number",
	"block_timestamp",
	"block_hash",
	"contract_address",
	"transaction_hash",
	"transaction_index",
	"log_index",
}

type clickHouseCommonColumns struct {
	colChain           proto.ColUInt64
	colBlock           proto.ColUInt64
	colTimestamp       proto.ColDateTime64
	colBlockHash       proto.ColFixedStr
	colContractAddress proto.ColFixedStr
	colTxHash          proto.ColFixedStr
	colTxIndex         proto.ColUInt64
	colLogIndex        proto.ColUInt64
}

func (c *clickHouseCommonColumns) init() {
	c.colTimestamp.WithPrecision(proto.Precision(3))
	c.colTimestamp.WithLocation(time.UTC)
	c.colBlockHash.SetSize(32)
	c.colContractAddress.SetSize(20)
	c.colTxHash.SetSize(32)
}

func (c *clickHouseCommonColumns) Reset() {
	c.colChain.Reset()
	c.colBlock.Reset()
	c.colTimestamp.Reset()
	c.colBlockHash.Reset()
	c.colContractAddress.Reset()
	c.colTxHash.Reset()
	c.colTxIndex.Reset()
	c.colLogIndex.Reset()
}

func (c *clickHouseCommonColumns) Append(meta EventMeta) {
	c.colChain.Append(meta.ChainID)
	c.colBlock.Append(meta.BlockNumber)
	c.colTimestamp.Append(meta.BlockTimestamp)
	c.colBlockHash.Append(common.HexToHash(meta.BlockHash).Bytes())
	c.colContractAddress.Append(common.HexToAddress(meta.ContractAddress).Bytes())
	c.colTxHash.Append(common.HexToHash(meta.TransactionHash).Bytes())
	c.colTxIndex.Append(meta.TransactionIndex)
	c.colLogIndex.Append(meta.LogIndex)
}

func (c *clickHouseCommonColumns) Rows() int {
	return c.colBlock.Rows()
}

func (c *clickHouseCommonColumns) Inputs() []proto.InputColumn {
	return []proto.InputColumn{
		{Name: "chain_id", Data: &c.colChain},
		{Name: "block_number", Data: &c.colBlock},
		{Name: "block_timestamp", Data: &c.colTimestamp},
		{Name: "block_hash", Data: &c.colBlockHash},
		{Name: "contract_address", Data: &c.colContractAddress},
		{Name: "transaction_hash", Data: &c.colTxHash},
		{Name: "transaction_index", Data: &c.colTxIndex},
		{Name: "log_index", Data: &c.colLogIndex},
	}
}

func clickHouseColumnNames(valueColumns []string) []string {
	names := make([]string, 0, len(ClickHouseCommonColumnNames)+len(valueColumns))
	names = append(names, ClickHouseCommonColumnNames...)
	names = append(names, valueColumns...)
	return names
}

func InsertEventBatch(ctx context.Context, conn *ch.Client, db string, batch ClickHouseEventBatch) error {
	if batch.Rows() == 0 {
		return nil
	}
	cols := batch.ColumnNames()
	quoted := make([]string, 0, len(cols))
	for _, col := range cols {
		quoted = append(quoted, quoteIdent(col))
	}
	return conn.Do(ctx, ch.Query{
		Body:  fmt.Sprintf("INSERT INTO %s.%s (%s) VALUES", quoteIdent(db), quoteIdent(batch.TableName()), strings.Join(quoted, ", ")),
		Input: batch.Inputs(),
	})
}

func clickHouseUInt256(v uint256.Int) proto.UInt256 {
	return proto.UInt256{
		Low:  proto.UInt128{Low: v[0], High: v[1]},
		High: proto.UInt128{Low: v[2], High: v[3]},
	}
}

func clickHouseBool(v bool) uint8 {
	if v {
		return 1
	}
	return 0
}

func clickHouseBytes(v []byte) string {
	return "0x" + common.Bytes2Hex(v)
}

func quoteIdent(name string) string {
	return "\x60" + strings.ReplaceAll(name, "\x60", "\x60\x60") + "\x60"
}

`)
	for _, ev := range events {
		renderBatchType(&b, ev)
	}
	b.WriteString("func NewClickHouseEventBatch(eventName string) ClickHouseEventBatch {\n\tswitch eventName {\n")
	usedCases := make(map[string]struct{})
	for _, ev := range events {
		var cases []string
		for _, name := range []string{ev.EventName, ev.GoTypeName} {
			if _, ok := usedCases[name]; ok {
				continue
			}
			usedCases[name] = struct{}{}
			cases = append(cases, strconv.Quote(name))
		}
		if len(cases) == 0 {
			continue
		}
		b.WriteString("\tcase ")
		b.WriteString(strings.Join(cases, ", "))
		b.WriteString(":\n\t\treturn New")
		b.WriteString(ev.GoTypeName)
		b.WriteString("Batch()\n")
	}
	b.WriteString("\tdefault:\n\t\treturn nil\n\t}\n}\n")
	return format.Source(b.Bytes())
}

func renderBatchType(b *bytes.Buffer, ev eventSpec) {
	batchType := ev.GoTypeName + "Batch"
	b.WriteString("\ntype ")
	b.WriteString(batchType)
	b.WriteString(" struct {\n\tcommon clickHouseCommonColumns\n")
	for _, arg := range ev.Args {
		b.WriteString("\tcol")
		b.WriteString(arg.GoFieldName)
		b.WriteString(" ")
		b.WriteString(protoColumnType(arg.ClickHouseType))
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("func New")
	b.WriteString(batchType)
	b.WriteString("() *")
	b.WriteString(batchType)
	b.WriteString(" {\n\tb := &")
	b.WriteString(batchType)
	b.WriteString("{}\n\tb.common.init()\n")
	for _, arg := range ev.Args {
		if init := protoColumnInit(arg); init != "" {
			b.WriteString("\tb.col")
			b.WriteString(arg.GoFieldName)
			b.WriteString(" = ")
			b.WriteString(init)
			b.WriteString("\n")
		}
	}
	b.WriteString("\treturn b\n}\n\n")
	b.WriteString("func (b *")
	b.WriteString(batchType)
	b.WriteString(") TableName() string { return ")
	b.WriteString(strconv.Quote(ev.TableName))
	b.WriteString(" }\n")
	b.WriteString("func (b *")
	b.WriteString(batchType)
	b.WriteString(") Rows() int { return b.common.Rows() }\n")
	b.WriteString("func (b *")
	b.WriteString(batchType)
	b.WriteString(") Reset() {\n\tb.common.Reset()\n")
	for _, arg := range ev.Args {
		b.WriteString("\tb.col")
		b.WriteString(arg.GoFieldName)
		b.WriteString(".Reset()\n")
	}
	b.WriteString("}\n")
	b.WriteString("func (b *")
	b.WriteString(batchType)
	b.WriteString(") ColumnNames() []string {\n\treturn clickHouseColumnNames([]string{")
	for i, arg := range ev.Args {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(arg.ColumnName))
	}
	b.WriteString("})\n}\n")
	b.WriteString("func (b *")
	b.WriteString(batchType)
	b.WriteString(") Inputs() []proto.InputColumn {\n\tinputs := b.common.Inputs()\n")
	if len(ev.Args) == 0 {
		b.WriteString("\treturn inputs\n}\n")
	} else {
		b.WriteString("\treturn append(inputs")
		for _, arg := range ev.Args {
			b.WriteString(", proto.InputColumn{Name: ")
			b.WriteString(strconv.Quote(arg.ColumnName))
			b.WriteString(", Data: &b.col")
			b.WriteString(arg.GoFieldName)
			b.WriteString("}")
		}
		b.WriteString(")\n}\n")
	}
	b.WriteString("func (b *")
	b.WriteString(batchType)
	b.WriteString(") Append(meta EventMeta, value any) bool {\n\tev, ok := value.(*")
	b.WriteString(ev.GoTypeName)
	b.WriteString(")\n\tif !ok {\n\t\treturn false\n\t}\n\tb.common.Append(meta)\n")
	for _, arg := range ev.Args {
		b.WriteString("\tb.col")
		b.WriteString(arg.GoFieldName)
		b.WriteString(".Append(")
		b.WriteString(appendExpr(arg))
		b.WriteString(")\n")
	}
	b.WriteString("\treturn true\n}\n")
}

func protoColumnType(chType string) string {
	switch {
	case chType == "UInt8":
		return "proto.ColUInt8"
	case chType == "UInt256":
		return "proto.ColUInt256"
	case chType == "FixedString(20)", chType == "FixedString(32)", strings.HasPrefix(chType, "FixedString("):
		return "proto.ColFixedStr"
	default:
		return "proto.ColStr"
	}
}

func protoColumnInit(arg eventArg) string {
	if strings.HasPrefix(arg.ClickHouseType, "FixedString(") {
		return "proto.ColFixedStr{Size: " + strconv.Itoa(fixedStringSize(arg.ClickHouseType)) + "}"
	}
	return ""
}

func appendExpr(arg eventArg) string {
	switch {
	case arg.ClickHouseType == "UInt8":
		return "clickHouseBool(ev." + arg.GoFieldName + ")"
	case arg.ClickHouseType == "UInt256":
		return "clickHouseUInt256(ev." + arg.GoFieldName + ")"
	case arg.ClickHouseType == "FixedString(20)", arg.ClickHouseType == "FixedString(32)":
		return "ev." + arg.GoFieldName + ".Bytes()"
	case strings.HasPrefix(arg.ClickHouseType, "FixedString("):
		return "ev." + arg.GoFieldName + "[:]"
	case arg.SolidityType == "bytes":
		return "clickHouseBytes(ev." + arg.GoFieldName + ")"
	default:
		return "fmt.Sprint(ev." + arg.GoFieldName + ")"
	}
}

func fixedStringSize(chType string) int {
	open := strings.IndexByte(chType, '(')
	close := strings.IndexByte(chType, ')')
	if open < 0 || close <= open+1 {
		return 0
	}
	n, _ := strconv.Atoi(chType[open+1 : close])
	return n
}
