package codegen

import (
	"bytes"
	"fmt"
	"go/format"
)

func generateRingBufferGo(events []eventSpec) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

import (
	"fmt"
)

type EventType uint8

const (
	EventTypeUnknown EventType = 0
`)

	for i, ev := range events {
		buf.WriteString(fmt.Sprintf("\tEventType%s EventType = %d\n", ev.GoTypeName, i+1))
	}

	buf.WriteString(`)

type BlockEventsSlot struct {
	BlockNumber   uint64
	BlockHash     string
	Sequence      []uint8
`)

	for _, ev := range events {
		buf.WriteString(fmt.Sprintf("\t%ss []%s\n", ev.GoTypeName, ev.GoTypeName))
	}

	buf.WriteString(`}

type OrderedHistoricRingBuffer struct {
	slots         []BlockEventsSlot
	blockNumbers  []uint64
	length        uint32
	bitWiseLength uint32
	headIndex     uint32
	tailIndex     uint32
	count         uint32
}

func NewOrderedHistoricRingBuffer(size uint32) (*OrderedHistoricRingBuffer, error) {
	if size == 0 || (size&(size-1) != 0) {
		return nil, fmt.Errorf("buffer size must be a power of two")
	}
	slots := make([]BlockEventsSlot, size)
	for i := range slots {
		slots[i] = BlockEventsSlot{
			Sequence: make([]uint8, 0, 128),
`)

	for _, ev := range events {
		buf.WriteString(fmt.Sprintf("\t\t\t%ss: make([]%s, 0, 128),\n", ev.GoTypeName, ev.GoTypeName))
	}

	buf.WriteString(`		}
	}
	return &OrderedHistoricRingBuffer{
		slots:         slots,
		blockNumbers:  make([]uint64, size),
		length:        size,
		bitWiseLength: size - 1,
	}, nil
}

func (r *OrderedHistoricRingBuffer) Push(blockNum uint64, blockHash string, logs []DecodedLog) {
	targetIdx := r.headIndex & r.bitWiseLength
	slot := &r.slots[targetIdx]

	slot.BlockNumber = blockNum
	slot.BlockHash = blockHash
	slot.Sequence = slot.Sequence[:0]

`)

	for _, ev := range events {
		buf.WriteString(fmt.Sprintf("\tslot.%ss = slot.%ss[:0]\n", ev.GoTypeName, ev.GoTypeName))
	}

	buf.WriteString(`
	for _, log := range logs {
		switch ev := log.Value.(type) {
`)

	for _, ev := range events {
		buf.WriteString(fmt.Sprintf(`		case *%s:
			slot.%ss = append(slot.%ss, *ev)
			slot.Sequence = append(slot.Sequence, uint8(EventType%s))
`, ev.GoTypeName, ev.GoTypeName, ev.GoTypeName, ev.GoTypeName))
	}

	buf.WriteString(`		}
	}

	r.blockNumbers[targetIdx] = blockNum
	r.headIndex = (r.headIndex + 1) & r.bitWiseLength
	if r.count < r.length {
		r.count++
	} else {
		r.tailIndex = (r.tailIndex + 1) & r.bitWiseLength
	}
}

func (r *OrderedHistoricRingBuffer) GetBlockNumber(idx uint32) uint64 {
	return r.blockNumbers[idx&r.bitWiseLength]
}

func (r *OrderedHistoricRingBuffer) GetBlockEvents(blockNum uint64) (*BlockEventsSlot, bool) {
	curr := r.tailIndex
	for i := uint32(0); i < r.count; i++ {
		slotIdx := curr & r.bitWiseLength
		if r.blockNumbers[slotIdx] == blockNum {
			return &r.slots[slotIdx], true
		}
		curr = (curr + 1) & r.bitWiseLength
	}
	return nil, false
}

func (slot *BlockEventsSlot) Reconstruct(
`)

	for _, ev := range events {
		buf.WriteString(fmt.Sprintf("\ton%s func(*%s) error,\n", ev.GoTypeName, ev.GoTypeName))
	}

	buf.WriteString(`) error {
`)

	for _, ev := range events {
		buf.WriteString(fmt.Sprintf("\tvar %sIdx int\n", ev.GoTypeName))
	}

	buf.WriteString(`
	for _, typ := range slot.Sequence {
		switch EventType(typ) {
`)

	for _, ev := range events {
		buf.WriteString(fmt.Sprintf(`		case EventType%s:
			ev := &slot.%ss[%sIdx]
			if err := on%s(ev); err != nil {
				return err
			}
			%sIdx++
`, ev.GoTypeName, ev.GoTypeName, ev.GoTypeName, ev.GoTypeName, ev.GoTypeName))
	}

	buf.WriteString(`		}
	}
	return nil
}
`)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("format source: %w", err)
	}
	return formatted, nil
}
