package codegen

import (
	"bytes"
	"go/format"
	"sort"
	"strings"

	"github.com/franz101/sqd-go/internal/config"
)

type stateHandleSpec struct {
	name      string
	stateType string
	valueName string
	valueType string
	spec      hotStateSpec
}

func generateStateGo(tables []customTableSpec, cfg *config.Config, events []eventSpec) ([]byte, error) {
	specs := hotStateSpecs(tables)
	handles := buildStateHandles(specs, cfg, events)

	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)
	renderStateImports(&b, handles)
	renderStateHandleTypes(&b, handles)

	b.WriteString("type State struct {\n")
	b.WriteString("\tHotState *HotState\n")
	b.WriteString("\tStore Store\n")
	for _, handle := range handles {
		b.WriteString("\t")
		b.WriteString(handle.name)
		b.WriteString(" ")
		b.WriteString(handle.stateType)
		b.WriteString("\n")
	}
	b.WriteString("\tmu sync.RWMutex\n")
	b.WriteString("\tLastSyncBlock uint64\n")
	b.WriteString("\tLastPruneBlock uint64\n")
	b.WriteString("\t// lastCommitWallNanos is the unix-nanos of the last hot-state commit, used\n")
	b.WriteString("\t// by the hybrid block/time commit cadence. 0 means \"not yet committed\".\n")
	b.WriteString("\tlastCommitWallNanos int64\n")
	b.WriteString("\t// snapshotsEnabled gates in-memory fork-recovery snapshots. They are only\n")
	b.WriteString("\t// consumed by RestoreToBlock during a reorg (cursor mode, above the finalized\n")
	b.WriteString("\t// head); during finalized backfill they are pure GC/memory churn, so the\n")
	b.WriteString("\t// ingestion layer disables them there. Default true (safe).\n")
	b.WriteString("\tsnapshotsEnabled bool\n")
	b.WriteString("\tsnapshots []memorySnapshot\n")
	b.WriteString("\tsnapshotIdx int\n")
	b.WriteString("}\n\n")

	b.WriteString("type memorySnapshot struct {\n\tblockNumber uint64\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\t")
		b.WriteString(lowerFirst(spec.baseName))
		b.WriteString(" []")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("const maxSnapshots = 128\n\n")

	b.WriteString("func NewState() *State {\n")
	b.WriteString("\ts := &State{HotState: NewHotState(DefaultClockCacheCapacity), snapshots: make([]memorySnapshot, maxSnapshots), snapshotsEnabled: true}\n")
	for _, handle := range handles {
		b.WriteString("\ts.")
		b.WriteString(handle.name)
		b.WriteString(" = ")
		b.WriteString(handle.stateType)
		b.WriteString("{state: s}\n")
	}
	b.WriteString("\treturn s\n}\n\n")

	b.WriteString(`func (s *State) Commit(ctx context.Context, store Store) error {
	if s == nil || s.HotState == nil || store == nil {
		return nil
	}
	return s.HotState.Commit(ctx, store.Conn(), store.DB())
}

func (s *State) LoadFromClickHouse(ctx context.Context, httpPort int, blockNumber uint64) error {
	if LoadStateFromClickHouseFn != nil {
		return LoadStateFromClickHouseFn(s, ctx, httpPort, blockNumber)
	}
	if s == nil {
		return nil
	}
	s.LastSyncBlock = blockNumber
	s.LastPruneBlock = blockNumber
	s.SaveSnapshot(blockNumber)
	return nil
}

var LoadStateFromClickHouseFn func(state *State, ctx context.Context, httpPort int, blockNumber uint64) error

func (s *State) SaveSnapshot(blockNumber uint64) {
	if s == nil || s.HotState == nil || len(s.snapshots) == 0 || !s.snapshotsEnabled {
		return
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	s.saveSnapshotLocked(blockNumber)
}

// SetSnapshotsEnabled toggles in-memory fork-recovery snapshots. The ingestion
// layer disables them during finalized backfill (no reorgs) to remove the
// dominant GC/memory cost; cursor mode keeps them for reorg recovery.
func (s *State) SetSnapshotsEnabled(enabled bool) {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.snapshotsEnabled = enabled
	s.mu.Unlock()
}

func (s *State) saveSnapshotLocked(blockNumber uint64) {
	idx := s.snapshotIdx % len(s.snapshots)
	snap := memorySnapshot{blockNumber: blockNumber}
`)
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		field := lowerFirst(spec.baseName)
		b.WriteString("\ts.HotState.")
		b.WriteString(spec.baseName)
		b.WriteString(".Range(func(_ ")
		b.WriteString(spec.keyType)
		b.WriteString(", v ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(") bool {\n")
		b.WriteString("\t\tsnap.")
		b.WriteString(field)
		b.WriteString(" = append(snap.")
		b.WriteString(field)
		b.WriteString(", v)\n\t\treturn true\n\t})\n")
	}
	b.WriteString(`	s.snapshots[idx] = snap
	s.snapshotIdx++
}

func (s *State) RestoreToBlock(blockNumber uint64) (uint64, error) {
	if s == nil {
		return blockNumber, nil
	}
	var best *memorySnapshot
	bestIdx := -1
	for i := range s.snapshots {
		snap := &s.snapshots[i]
		if snap.blockNumber == 0 || snap.blockNumber > blockNumber {
			continue
		}
		if best == nil || snap.blockNumber > best.blockNumber {
			best = snap
			bestIdx = i
		}
	}
	if best == nil {
		return 0, fmt.Errorf("no snapshot found at or below block %d", blockNumber)
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	s.HotState = NewHotState(DefaultClockCacheCapacity)
`)
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tfor _, val := range best.")
		b.WriteString(lowerFirst(spec.baseName))
		b.WriteString(" {\n\t\ts.HotState.")
		b.WriteString(spec.baseName)
		b.WriteString(".Set(val)\n\t}\n")
	}
	b.WriteString(`	s.LastSyncBlock = best.blockNumber
	s.LastPruneBlock = best.blockNumber
	for i := range s.snapshots {
		if s.snapshots[i].blockNumber > blockNumber {
			s.snapshots[i] = memorySnapshot{}
		}
	}
	s.snapshotIdx = bestIdx + 1
	return best.blockNumber, nil
}
`)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func buildStateHandles(specs []hotStateSpec, cfg *config.Config, events []eventSpec) []stateHandleSpec {
	used := make(map[string]struct{})
	var handles []stateHandleSpec
	add := func(name string, spec hotStateSpec) {
		name = exportIdent(name)
		if name == "" {
			return
		}
		if _, ok := used[name]; ok {
			return
		}
		used[name] = struct{}{}
		handles = append(handles, stateHandleSpec{
			name:      name,
			stateType: name + "State",
			valueName: name,
			valueType: spec.table.GoTypeName,
			spec:      spec,
		})
	}

	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		name := strings.TrimPrefix(spec.table.GoTypeName, "Memory")
		add(name, spec)
	}

	if cfg != nil {
		for _, state := range cfg.State {
			if table, ok := findStateCustomTableSpec(hotStateTables(specs), state); ok {
				if spec, ok := findHotStateSpec(specs, table); ok {
					add(state.Name, spec)
				}
				continue
			}
			target, err := findStateEventSpec(events, state)
			if err != nil {
				continue
			}
			table := stateEventToCustomTableSpec(target, state)
			if spec, ok := findHotStateSpec(specs, table); ok {
				add(state.Name, spec)
			}
		}
	}
	return handles
}

func hotStateTables(specs []hotStateSpec) []customTableSpec {
	tables := make([]customTableSpec, 0, len(specs))
	for _, spec := range specs {
		tables = append(tables, spec.table)
	}
	return tables
}

func findHotStateSpec(specs []hotStateSpec, table customTableSpec) (hotStateSpec, bool) {
	for _, spec := range specs {
		if spec.table.GoTypeName == table.GoTypeName && spec.table.Name == table.Name {
			return spec, true
		}
	}
	return hotStateSpec{}, false
}

func renderStateImports(b *bytes.Buffer, handles []stateHandleSpec) {
	imports := map[string]struct{}{
		`"context"`: {},
		`"fmt"`:     {},
		`"sync"`:    {},
	}
	for _, handle := range handles {
		for _, field := range handle.spec.table.keyFields() {
			stateAddImport(imports, field.Type)
		}
	}
	keys := make([]string, 0, len(imports))
	for imp := range imports {
		keys = append(keys, imp)
	}
	sort.Strings(keys)
	b.WriteString("import (\n")
	for _, imp := range keys {
		b.WriteString("\t")
		b.WriteString(imp)
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func stateAddImport(imports map[string]struct{}, typ string) {
	switch {
	case strings.Contains(typ, "common."):
		imports[`"github.com/ethereum/go-ethereum/common"`] = struct{}{}
	case strings.Contains(typ, "uint256."):
		imports[`"github.com/holiman/uint256"`] = struct{}{}
	case strings.Contains(typ, "decimal."):
		imports[`"github.com/shopspring/decimal"`] = struct{}{}
	case strings.Contains(typ, "time."):
		imports[`"time"`] = struct{}{}
	}
}

func renderStateHandleTypes(b *bytes.Buffer, handles []stateHandleSpec) {
	for _, handle := range handles {
		if handle.valueName != handle.valueType {
			b.WriteString("type ")
			b.WriteString(handle.valueName)
			b.WriteString(" = ")
			b.WriteString(handle.valueType)
			b.WriteString("\n\n")
		}
		b.WriteString("type ")
		b.WriteString(handle.stateType)
		b.WriteString(" struct { state *State }\n\n")
		renderStateHandleGet(b, handle)
		if !handle.spec.table.IsEvent {
			renderStateHandleSave(b, handle)
		}
	}
}

func renderStateHandleGet(b *bytes.Buffer, handle stateHandleSpec) {
	keyFields := handle.spec.table.keyFields()
	b.WriteString("func (h ")
	b.WriteString(handle.stateType)
	b.WriteString(") Get(")
	renderClockKeyParams(b, keyFields)
	b.WriteString(") (*")
	b.WriteString(handle.valueName)
	b.WriteString(", bool) {\n")
	b.WriteString("\tif h.state == nil || h.state.HotState == nil {\n\t\treturn nil, false\n\t}\n")
	b.WriteString("\tval, ok := h.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString(".GetByFields(")
	for i, field := range keyFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(lowerFirst(field.Name))
	}
	b.WriteString(")\n\tif !ok {\n")
	b.WriteString("\t\tif h.state.Store != nil && h.state.Store.Conn() != nil {\n")
	b.WriteString("\t\t\tkey := ")
	b.WriteString(handle.spec.keyType)
	b.WriteString("{")
	for i, field := range keyFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(lowerFirst(field.Name))
	}
	b.WriteString("}\n")
	b.WriteString("\t\t\th.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString("Resolver.Queue(key)\n")
	b.WriteString("\t\t\tif err := h.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString("Resolver.Resolve(context.Background(), h.state.Store.Conn(), h.state.Store.DB()); err == nil {\n")
	b.WriteString("\t\t\t\tif val, ok = h.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString(".Get(key); ok {\n")
	b.WriteString("\t\t\t\t\tif val.Tombstone {\n")
	b.WriteString("\t\t\t\t\t\treturn nil, false\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t\treturn &val, true\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn nil, false\n\t}\n")
	b.WriteString("\tif val.Tombstone {\n")
	b.WriteString("\t\treturn nil, false\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn &val, true\n}\n\n")
}

func renderStateHandleSave(b *bytes.Buffer, handle stateHandleSpec) {
	b.WriteString("func (h ")
	b.WriteString(handle.stateType)
	b.WriteString(") Save(value *")
	b.WriteString(handle.valueName)
	b.WriteString(", meta EventMeta) {\n")
	b.WriteString("\tif h.state == nil || h.state.HotState == nil || value == nil {\n\t\treturn\n\t}\n")
	for _, field := range handle.spec.table.Fields {
		switch field.Name {
		case "BlockNumber", "UpdatedAtBlock":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			b.WriteString(" = meta.BlockNumber\n")
		case "BlockTimestamp", "UpdatedAt":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			b.WriteString(" = meta.BlockTimestamp\n")
		case "TxIndex", "TransactionIndex":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			b.WriteString(" = meta.TransactionIndex\n")
		case "LogIndex":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			b.WriteString(" = meta.LogIndex\n")
		}
	}
	b.WriteString("\th.state.HotState.Update")
	b.WriteString(handle.spec.table.GoTypeName)
	b.WriteString("(*value)\n}\n\n")
}
