package codegen

import (
	"bytes"
	"go/format"
	"sort"
	"strings"

	"github.com/franz101/sqd-go/internal/config"
)

type stateHandleSpec struct {
	name      string
	stateType string
	valueName string
	valueType string
	spec      hotStateSpec
}

func generateStateGo(tables []customTableSpec, cfg *config.Config, events []eventSpec) ([]byte, error) {
	specs := hotStateSpecs(tables)
	handles := buildStateHandles(specs, cfg, events)

	var b bytes.Buffer
	b.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

`)
	renderStateImports(&b, handles)
	renderStateHandleTypes(&b, handles)

	b.WriteString("type State struct {\n")
	b.WriteString("\tHotState *HotState\n")
	b.WriteString("\tStore Store\n")
	for _, handle := range handles {
		b.WriteString("\t")
		b.WriteString(handle.name)
		b.WriteString(" ")
		b.WriteString(handle.stateType)
		b.WriteString("\n")
	}
	b.WriteString("\tmu sync.RWMutex\n")
	b.WriteString("\tLastSyncBlock uint64\n")
	b.WriteString("\tLastPruneBlock uint64\n")
	b.WriteString("\t// lastCommitWallNanos is the unix-nanos of the last hot-state commit, used\n")
	b.WriteString("\t// by the hybrid block/time commit cadence. 0 means \"not yet committed\".\n")
	b.WriteString("\tlastCommitWallNanos int64\n")
	b.WriteString("\t// commitMaxBlocks / commitMaxInterval cache the hybrid commit cadence\n")
	b.WriteString("\t// (SQD_COMMIT_INTERVAL, SQD_COMMIT_MAX_INTERVAL). Read once per State:\n")
	b.WriteString("\t// commitCustomProcessing runs on every block, and an os.Getenv + parse\n")
	b.WriteString("\t// per block is measurable overhead at backfill rates.\n")
	b.WriteString("\tcommitMaxBlocks uint64\n")
	b.WriteString("\tcommitMaxInterval time.Duration\n")
	b.WriteString("\t// snapshotsEnabled gates in-memory fork-recovery snapshots. They are only\n")
	b.WriteString("\t// consumed by RestoreToBlock during a reorg (cursor mode, above the finalized\n")
	b.WriteString("\t// head); during finalized backfill they are pure GC/memory churn, so the\n")
	b.WriteString("\t// ingestion layer disables them there. Default true (safe).\n")
	b.WriteString("\tsnapshotsEnabled bool\n")
	b.WriteString("\tsnapshots []memorySnapshot\n")
	b.WriteString("\tsnapshotIdx int\n")
	b.WriteString("}\n\n")

	b.WriteString("type memorySnapshot struct {\n\tblockNumber uint64\n")
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\t")
		b.WriteString(lowerFirst(spec.baseName))
		b.WriteString(" []")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("const maxSnapshots = 128\n\n")

	b.WriteString(`// hotCacheCapacity returns the per-entity hot clock-cache capacity.
// SQD_HOTCACHE_CAP overrides the default (entries per cache, preallocated
// flat rings — memory is capacity * entry size * number of entities, fixed at
// startup). Raise it when the live-entity working set exceeds the default and
// misses fall through to the cold tier's synchronous disk reads.
func hotCacheCapacity() uint64 {
	if envVal := os.Getenv("SQD_HOTCACHE_CAP"); envVal != "" {
		if parsed, err := strconv.ParseUint(envVal, 10, 64); err == nil && parsed > 0 {
			return parsed
		}
	}
	return DefaultClockCacheCapacity
}

`)
	b.WriteString("func NewState() *State {\n")
	b.WriteString("\ts := &State{HotState: NewHotState(hotCacheCapacity()), snapshots: make([]memorySnapshot, maxSnapshots), snapshotsEnabled: true}\n")
	for _, handle := range handles {
		b.WriteString("\ts.")
		b.WriteString(handle.name)
		b.WriteString(" = ")
		b.WriteString(handle.stateType)
		b.WriteString("{state: s}\n")
	}
	b.WriteString(`	s.commitMaxBlocks = 20000
	if envVal := os.Getenv("SQD_COMMIT_INTERVAL"); envVal != "" {
		if parsed, err := strconv.ParseUint(envVal, 10, 64); err == nil && parsed > 0 {
			s.commitMaxBlocks = parsed
		}
	}
	s.commitMaxInterval = 3 * time.Second
	if envVal := os.Getenv("SQD_COMMIT_MAX_INTERVAL"); envVal != "" {
		if parsed, err := time.ParseDuration(envVal); err == nil && parsed > 0 {
			s.commitMaxInterval = parsed
		}
	}
`)
	b.WriteString("\treturn s\n}\n\n")

	b.WriteString(`func (s *State) Commit(ctx context.Context, store Store) error {
	if s == nil || s.HotState == nil || store == nil {
		return nil
	}
	return s.HotState.Commit(ctx, store.Conn(), store.DB())
}

// LoadFromClickHouse rebuilds the in-memory hot state from the durable memory_*
// tables at startup/recovery. It dials a native ClickHouse client from the
// environment (the hot-state caches are not yet attached to a Store at this
// point) and delegates the per-entity reload to the generated HotState.Recover,
// which reads each entity's latest row back via the same columnar decoders the
// commit path writes — guaranteeing a faithful round-trip.
func (s *State) LoadFromClickHouse(ctx context.Context, blockNumber uint64) error {
	if s == nil {
		return nil
	}
	// Test mode: don't touch a live database, just advance the cursor so a fresh
	// process starts at the checkpoint.
	if os.Getenv("TEST_MODE") == "1" || os.Getenv("CI") == "1" {
		s.LastSyncBlock = blockNumber
		s.LastPruneBlock = blockNumber
		s.SaveSnapshot(blockNumber)
		return nil
	}
	if s.HotState == nil {
		s.LastSyncBlock = blockNumber
		s.LastPruneBlock = blockNumber
		s.SaveSnapshot(blockNumber)
		return nil
	}

	host := os.Getenv("CLICKHOUSE_HOST")
	if host == "" {
		host = "127.0.0.1"
	}
	port := 9000
	if v := os.Getenv("CLICKHOUSE_NATIVE_PORT"); v != "" {
		if p, err := strconv.Atoi(v); err == nil {
			port = p
		}
	}
	user := os.Getenv("CLICKHOUSE_USER")
	if user == "" {
		user = "default"
	}
	password := os.Getenv("CLICKHOUSE_PASSWORD")
	db := os.Getenv("CLICKHOUSE_DATABASE")
	if db == "" {
		db = ProjectName
	}

	conn, err := ch.Dial(ctx, ch.Options{
		Address:  fmt.Sprintf("%s:%d", host, port),
		Database: "default",
		User:     user,
		Password: password,
	})
	if err != nil {
		return fmt.Errorf("load state: dial clickhouse %s:%d: %w", host, port, err)
	}
	defer conn.Close()

	// Rebuilding from (rolled-back) ClickHouse makes the cold tier authoritative
	// again: re-open it fresh (Open wipes the dir, discarding entries past the
	// rollback point), keep it ATTACHED during Recover so rows beyond the hot
	// ring capacity spill to Pebble instead of being dropped, then mark it
	// authoritative — hot∪cold now provably covers every state row ≤ blockNumber
	// and a steady-state miss never needs a ClickHouse point-SELECT. Without a
	// configured cold tier this is the old behavior (plain hot reload, lazy
	// per-miss resolution).
	coldAttached, err := s.HotState.ReopenColdCacheFresh()
	if err != nil {
		return fmt.Errorf("load state: reopen cold tier: %w", err)
	}
	if err := s.HotState.Recover(ctx, conn, db); err != nil {
		return fmt.Errorf("load state: recover hot state at block %d: %w", blockNumber, err)
	}
	if coldAttached {
		s.HotState.coldAuthoritative = true
		log.Printf("[LOAD STATE] cold tier rebuilt and authoritative at block %d: steady-state misses skip ClickHouse", blockNumber)
	}

	s.LastSyncBlock = blockNumber
	s.LastPruneBlock = blockNumber
	s.SaveSnapshot(blockNumber)
	return nil
}

func (s *State) SaveSnapshot(blockNumber uint64) {
	if s == nil || s.HotState == nil || len(s.snapshots) == 0 || !s.snapshotsEnabled {
		return
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	s.saveSnapshotLocked(blockNumber)
}

// SetSnapshotsEnabled toggles in-memory fork-recovery snapshots. The ingestion
// layer disables them during finalized backfill (no reorgs) to remove the
// dominant GC/memory cost; cursor mode keeps them for reorg recovery.
func (s *State) SetSnapshotsEnabled(enabled bool) {
	if s == nil {
		return
	}
	s.mu.Lock()
	s.snapshotsEnabled = enabled
	s.mu.Unlock()
}

func (s *State) saveSnapshotLocked(blockNumber uint64) {
	idx := s.snapshotIdx % len(s.snapshots)
	snap := memorySnapshot{blockNumber: blockNumber}
`)
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		field := lowerFirst(spec.baseName)
		b.WriteString("\ts.HotState.")
		b.WriteString(spec.baseName)
		b.WriteString(".Range(func(_ ")
		b.WriteString(spec.keyType)
		b.WriteString(", v ")
		b.WriteString(spec.table.GoTypeName)
		b.WriteString(") bool {\n")
		b.WriteString("\t\tsnap.")
		b.WriteString(field)
		b.WriteString(" = append(snap.")
		b.WriteString(field)
		b.WriteString(", v)\n\t\treturn true\n\t})\n")
	}
	b.WriteString(`	s.snapshots[idx] = snap
	s.snapshotIdx++
}

func (s *State) RestoreToBlock(blockNumber uint64) (uint64, error) {
	if s == nil {
		return blockNumber, nil
	}
	var best *memorySnapshot
	bestIdx := -1
	for i := range s.snapshots {
		snap := &s.snapshots[i]
		if snap.blockNumber == 0 || snap.blockNumber > blockNumber {
			continue
		}
		if best == nil || snap.blockNumber > best.blockNumber {
			best = snap
			bestIdx = i
		}
	}
	if best == nil {
		return 0, fmt.Errorf("no snapshot found at or below block %d", blockNumber)
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	// Detach the cold tier before discarding the hot state: its entries reflect
	// blocks > the restore point and must not survive a reorg. Post-restore reads
	// fall back to ClickHouse (rolled back to the safe block) — correct.
	_ = s.HotState.CloseColdCache()
	s.HotState = NewHotState(hotCacheCapacity())
`)
	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		b.WriteString("\tfor _, val := range best.")
		b.WriteString(lowerFirst(spec.baseName))
		b.WriteString(" {\n\t\ts.HotState.")
		b.WriteString(spec.baseName)
		b.WriteString(".Set(val)\n\t}\n")
	}
	b.WriteString(`	s.LastSyncBlock = best.blockNumber
	s.LastPruneBlock = best.blockNumber
	for i := range s.snapshots {
		if s.snapshots[i].blockNumber > blockNumber {
			s.snapshots[i] = memorySnapshot{}
		}
	}
	s.snapshotIdx = bestIdx + 1
	return best.blockNumber, nil
}
`)

	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func buildStateHandles(specs []hotStateSpec, cfg *config.Config, events []eventSpec) []stateHandleSpec {
	used := make(map[string]struct{})
	var handles []stateHandleSpec
	add := func(name string, spec hotStateSpec) {
		name = exportIdent(name)
		if name == "" {
			return
		}
		if _, ok := used[name]; ok {
			return
		}
		used[name] = struct{}{}
		handles = append(handles, stateHandleSpec{
			name:      name,
			stateType: name + "State",
			valueName: name,
			valueType: spec.table.GoTypeName,
			spec:      spec,
		})
	}

	for _, spec := range specs {
		if spec.table.IsEvent {
			continue
		}
		name := strings.TrimPrefix(spec.table.GoTypeName, "Memory")
		add(name, spec)
	}

	if cfg != nil {
		for _, state := range cfg.State {
			if table, ok := findStateCustomTableSpec(hotStateTables(specs), state); ok {
				if spec, ok := findHotStateSpec(specs, table); ok {
					add(state.Name, spec)
				}
				continue
			}
			target, err := findStateEventSpec(events, state)
			if err != nil {
				continue
			}
			table := stateEventToCustomTableSpec(target, state)
			if spec, ok := findHotStateSpec(specs, table); ok {
				add(state.Name, spec)
			}
		}
	}
	return handles
}

func hotStateTables(specs []hotStateSpec) []customTableSpec {
	tables := make([]customTableSpec, 0, len(specs))
	for _, spec := range specs {
		tables = append(tables, spec.table)
	}
	return tables
}

func findHotStateSpec(specs []hotStateSpec, table customTableSpec) (hotStateSpec, bool) {
	for _, spec := range specs {
		if spec.table.GoTypeName == table.GoTypeName && spec.table.Name == table.Name {
			return spec, true
		}
	}
	return hotStateSpec{}, false
}

func renderStateImports(b *bytes.Buffer, handles []stateHandleSpec) {
	imports := map[string]struct{}{
		`"context"`:                     {},
		`"fmt"`:                         {},
		`"log"`:                         {},
		`"os"`:                          {},
		`"strconv"`:                     {},
		`"sync"`:                        {},
		`"time"`:                        {},
		`"github.com/ClickHouse/ch-go"`: {},
	}
	for _, handle := range handles {
		for _, field := range handle.spec.table.keyFields() {
			stateAddImport(imports, field.Type)
		}
	}
	keys := make([]string, 0, len(imports))
	for imp := range imports {
		keys = append(keys, imp)
	}
	sort.Strings(keys)
	b.WriteString("import (\n")
	for _, imp := range keys {
		b.WriteString("\t")
		b.WriteString(imp)
		b.WriteString("\n")
	}
	b.WriteString(")\n\n")
}

func stateAddImport(imports map[string]struct{}, typ string) {
	switch {
	case strings.Contains(typ, "common."):
		imports[`"github.com/ethereum/go-ethereum/common"`] = struct{}{}
	case strings.Contains(typ, "uint256."):
		imports[`"github.com/holiman/uint256"`] = struct{}{}
	case strings.Contains(typ, "decimal."):
		imports[`"github.com/shopspring/decimal"`] = struct{}{}
	case strings.Contains(typ, "time."):
		imports[`"time"`] = struct{}{}
	}
}

func renderStateHandleTypes(b *bytes.Buffer, handles []stateHandleSpec) {
	for _, handle := range handles {
		if handle.valueName != handle.valueType {
			b.WriteString("type ")
			b.WriteString(handle.valueName)
			b.WriteString(" = ")
			b.WriteString(handle.valueType)
			b.WriteString("\n\n")
		}
		b.WriteString("type ")
		b.WriteString(handle.stateType)
		b.WriteString(" struct { state *State }\n\n")
		renderStateHandleGet(b, handle)
		if !handle.spec.table.IsEvent {
			renderStateHandleSave(b, handle)
		}
	}
}

func renderStateHandleGet(b *bytes.Buffer, handle stateHandleSpec) {
	keyFields := handle.spec.table.keyFields()
	b.WriteString("func (h ")
	b.WriteString(handle.stateType)
	b.WriteString(") Get(")
	renderClockKeyParams(b, keyFields)
	b.WriteString(") (*")
	b.WriteString(handle.valueName)
	b.WriteString(", bool) {\n")
	b.WriteString("\tif h.state == nil || h.state.HotState == nil {\n\t\treturn nil, false\n\t}\n")
	b.WriteString("\tval, ok := h.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString(".GetByFields(")
	for i, field := range keyFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(lowerFirst(field.Name))
	}
	b.WriteString(")\n\tif !ok {\n")
	if entityUsesCold(handle.spec.table) {
		// Cold tier already consulted inside GetByFields. A hot+cold miss under an
		// authoritative (from-genesis) cold tier means the key provably does not
		// exist in ClickHouse, so skip the point-SELECT entirely — this is what
		// removes the per-miss SELECT storm. Non-authoritative (resume / cursor) or
		// cold-disabled keeps the ClickHouse fallback below.
		b.WriteString("\t\tif h.state.HotState != nil && h.state.HotState.coldAuthoritative {\n\t\t\treturn nil, false\n\t\t}\n")
	}
	b.WriteString("\t\tif h.state.Store != nil && h.state.Store.Conn() != nil {\n")
	b.WriteString("\t\t\tkey := ")
	b.WriteString(handle.spec.keyType)
	b.WriteString("{")
	for i, field := range keyFields {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(field.Name)
		b.WriteString(": ")
		b.WriteString(lowerFirst(field.Name))
	}
	b.WriteString("}\n")
	b.WriteString("\t\t\th.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString("Resolver.Queue(key)\n")
	b.WriteString("\t\t\tif err := h.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString("Resolver.Resolve(context.Background(), h.state.Store.Conn(), h.state.Store.DB()); err == nil {\n")
	b.WriteString("\t\t\t\tif val, ok = h.state.HotState.")
	b.WriteString(handle.spec.baseName)
	b.WriteString(".Get(key); ok {\n")
	b.WriteString("\t\t\t\t\tif val.Tombstone {\n")
	b.WriteString("\t\t\t\t\t\treturn nil, false\n")
	b.WriteString("\t\t\t\t\t}\n")
	b.WriteString("\t\t\t\t\treturn &val, true\n")
	b.WriteString("\t\t\t\t}\n")
	b.WriteString("\t\t\t}\n")
	b.WriteString("\t\t}\n")
	b.WriteString("\t\treturn nil, false\n\t}\n")
	b.WriteString("\tif val.Tombstone {\n")
	b.WriteString("\t\treturn nil, false\n")
	b.WriteString("\t}\n")
	b.WriteString("\treturn &val, true\n}\n\n")
}

func renderStateHandleSave(b *bytes.Buffer, handle stateHandleSpec) {
	b.WriteString("func (h ")
	b.WriteString(handle.stateType)
	b.WriteString(") Save(value *")
	b.WriteString(handle.valueName)
	b.WriteString(", meta EventMeta) {\n")
	b.WriteString("\tif h.state == nil || h.state.HotState == nil || value == nil {\n\t\treturn\n\t}\n")
	for _, field := range handle.spec.table.Fields {
		switch field.Name {
		case "BlockNumber", "UpdatedAtBlock":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			b.WriteString(" = meta.BlockNumber\n")
		case "BlockTimestamp", "UpdatedAt":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			if field.Type == "time.Time" {
				// A2: in-memory timestamp is int64 unix-millis to keep the ring
				// pointer-free; the DateTime64 column is restored at Append time.
				b.WriteString(" = meta.BlockTimestamp.UnixMilli()\n")
			} else {
				b.WriteString(" = meta.BlockTimestamp\n")
			}
		case "TxIndex", "TransactionIndex":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			b.WriteString(" = meta.TransactionIndex\n")
		case "LogIndex":
			b.WriteString("\tvalue.")
			b.WriteString(field.Name)
			b.WriteString(" = meta.LogIndex\n")
		}
	}
	b.WriteString("\th.state.HotState.Update")
	b.WriteString(handle.spec.table.GoTypeName)
	b.WriteString("(*value)\n}\n\n")
}
