package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
)

// generateProtoViewGo generates zero-copy view types for proto columns
// This implements the ECS-style processing without conversion overhead
func generateProtoViewGo(events []eventSpec) ([]byte, error) {
	var buf bytes.Buffer

	buf.WriteString(`// Code generated by sqd-go codegen; DO NOT EDIT.

package generated

import (
	"time"

	"github.com/ClickHouse/ch-go/proto"
	"github.com/ethereum/go-ethereum/common"
	"github.com/holiman/uint256"
	"github.com/franz101/sqd-go/abiunpack"
)

// ProtoEventBlock holds parsed events in columnar format.
// This is the ClickHouse-native storage format.
type ProtoEventBlock struct {
	HeaderBlockNumber uint64
	HeaderBlockHash   string
	Sequence          []uint8

	// Metadata columns (shared across all events)
	BlockNumber  proto.ColUInt64
	BlockHash    proto.ColFixedStr // 32 bytes
	BlockTS      proto.ColDateTime64
	ContractAddr proto.ColFixedStr // 20 bytes
	TxHash       proto.ColFixedStr // 32 bytes
	TxIndex      proto.ColUInt64
	LogIndex     proto.ColUInt64

`)

	// Generate per-event column groups
	for _, ev := range events {
		fmt.Fprintf(&buf, "\t// %s event columns\n", ev.GoTypeName)
		fmt.Fprintf(&buf, "\t%s_meta_index proto.ColUInt64\n", ev.GoTypeName)
		for _, arg := range ev.Args {
			colType := protoColType(arg.GoType)
			colName := camelToSnake(arg.GoFieldName)
			fmt.Fprintf(&buf, "\t%s_%s %s\n", ev.GoTypeName, colName, colType)
		}
		fmt.Fprint(&buf, "\n")
	}

	fmt.Fprint(&buf, "}\n\n")

	// Generate block constructor and lifecycle helpers
	fmt.Fprint(&buf, "// NewProtoEventBlock creates an initialized proto event block.\n")
	fmt.Fprint(&buf, "func NewProtoEventBlock() *ProtoEventBlock {\n")
	fmt.Fprint(&buf, "\tb := &ProtoEventBlock{Sequence: make([]uint8, 0, 128)}\n")
	fmt.Fprint(&buf, "\tb.init()\n")
	fmt.Fprint(&buf, "\treturn b\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "func (b *ProtoEventBlock) init() {\n")
	fmt.Fprint(&buf, "\tb.BlockHash.SetSize(32)\n")
	fmt.Fprint(&buf, "\tb.ContractAddr.SetSize(20)\n")
	fmt.Fprint(&buf, "\tb.TxHash.SetSize(32)\n")
	fmt.Fprint(&buf, "\tb.BlockTS.WithPrecision(proto.Precision(3))\n")
	fmt.Fprint(&buf, "\tb.BlockTS.WithLocation(time.UTC)\n")
	for _, ev := range events {
		for _, arg := range ev.Args {
			colName := ev.GoTypeName + "_" + camelToSnake(arg.GoFieldName)
			if strings.HasPrefix(arg.ClickHouseType, "FixedString(") {
				fmt.Fprintf(&buf, "\tb.%s.SetSize(%d)\n", colName, fixedStringSize(arg.ClickHouseType))
			} else if arg.GoType == "[]uint256.Int" {
				fmt.Fprintf(&buf, "\tb.%s = new(proto.ColUInt256).Array()\n", colName)
			} else if arg.GoType == "[]common.Hash" {
				fmt.Fprintf(&buf, "\tb.%s = (&proto.ColFixedStr{Size: 32}).Array()\n", colName)
			} else if arg.GoType == "[]common.Address" {
				fmt.Fprintf(&buf, "\tb.%s = (&proto.ColFixedStr{Size: 20}).Array()\n", colName)
			}
		}
	}
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "// Reset clears all column data while keeping allocated capacity.\n")
	fmt.Fprint(&buf, "func (b *ProtoEventBlock) Reset() {\n")
	fmt.Fprint(&buf, "\tb.HeaderBlockNumber = 0\n")
	fmt.Fprint(&buf, "\tb.HeaderBlockHash = \"\"\n")
	fmt.Fprint(&buf, "\tb.Sequence = b.Sequence[:0]\n")
	fmt.Fprint(&buf, "\tb.BlockNumber.Reset()\n")
	fmt.Fprint(&buf, "\tb.BlockHash.Reset()\n")
	fmt.Fprint(&buf, "\tb.BlockTS.Reset()\n")
	fmt.Fprint(&buf, "\tb.ContractAddr.Reset()\n")
	fmt.Fprint(&buf, "\tb.TxHash.Reset()\n")
	fmt.Fprint(&buf, "\tb.TxIndex.Reset()\n")
	fmt.Fprint(&buf, "\tb.LogIndex.Reset()\n")
	for _, ev := range events {
		fmt.Fprintf(&buf, "\tb.%s_meta_index.Reset()\n", ev.GoTypeName)
		for _, arg := range ev.Args {
			colName := ev.GoTypeName + "_" + camelToSnake(arg.GoFieldName)
			fmt.Fprintf(&buf, "\tb.%s.Reset()\n", colName)
		}
	}
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "func (b *ProtoEventBlock) appendMeta(meta EventMeta) uint64 {\n")
	fmt.Fprint(&buf, "\tidx := uint64(b.BlockNumber.Rows())\n")
	fmt.Fprint(&buf, "\tb.BlockNumber.Append(meta.BlockNumber)\n")
	fmt.Fprint(&buf, "\tb.BlockHash.Append(meta.BlockHash.Bytes())\n")
	fmt.Fprint(&buf, "\tb.BlockTS.Append(meta.BlockTimestamp)\n")
	fmt.Fprint(&buf, "\tb.ContractAddr.Append(meta.ContractAddress.Bytes())\n")
	fmt.Fprint(&buf, "\tb.TxHash.Append(meta.TransactionHash.Bytes())\n")
	fmt.Fprint(&buf, "\tb.TxIndex.Append(meta.TransactionIndex)\n")
	fmt.Fprint(&buf, "\tb.LogIndex.Append(meta.LogIndex)\n")
	fmt.Fprint(&buf, "\treturn idx\n")
	fmt.Fprint(&buf, "}\n\n")

	for _, ev := range events {
		fmt.Fprintf(&buf, "// Append%s appends a %s event to the proto block.\n", ev.GoTypeName, ev.GoTypeName)
		fmt.Fprintf(&buf, "func (b *ProtoEventBlock) Append%s(meta EventMeta, ev *%s) {\n", ev.GoTypeName, ev.GoTypeName)
		fmt.Fprint(&buf, "\tif b == nil || ev == nil {\n\t\treturn\n\t}\n")
		fmt.Fprint(&buf, "\tmetaIdx := b.appendMeta(meta)\n")
		fmt.Fprintf(&buf, "\tb.%s_meta_index.Append(metaIdx)\n", ev.GoTypeName)
		for _, arg := range ev.Args {
			colName := ev.GoTypeName + "_" + camelToSnake(arg.GoFieldName)
			fmt.Fprintf(&buf, "\tb.%s.Append(%s)\n", colName, protoAppendExpr(arg))
		}
		fmt.Fprintf(&buf, "\tb.Sequence = append(b.Sequence, uint8(EventType%s))\n", ev.GoTypeName)
		fmt.Fprint(&buf, "}\n\n")
	}

	fmt.Fprint(&buf, "// AppendDecodedLog appends a decoded log to the proto block.\n")
	fmt.Fprint(&buf, "func (b *ProtoEventBlock) AppendDecodedLog(log DecodedLog) bool {\n")
	fmt.Fprint(&buf, "\tswitch ev := log.Value.(type) {\n")
	for _, ev := range events {
		fmt.Fprintf(&buf, "\tcase *%s:\n", ev.GoTypeName)
		fmt.Fprintf(&buf, "\t\tb.Append%s(ev.EventMeta, ev)\n", ev.GoTypeName)
		fmt.Fprint(&buf, "\t\treturn true\n")
	}
	fmt.Fprint(&buf, "\tdefault:\n\t\treturn false\n\t}\n")
	fmt.Fprint(&buf, "}\n\n")

	// Group events by lowercased topic0 to handle shared topic0s across
	// different contracts (e.g. ExchangeOrderFilled + NegRiskExchangeOrderFilled
	// both emit OrderFilled with the same topic0 but different contract addresses).
	type topicGroup struct {
		topic0 string
		events []eventSpec
	}
	var ordered []topicGroup
	seen := make(map[string]bool)
	for _, ev := range events {
		t0Lower := strings.ToLower(ev.Topic0)
		if seen[t0Lower] {
			// Append to existing group.
			for i := range ordered {
				if ordered[i].topic0 == t0Lower {
					ordered[i].events = append(ordered[i].events, ev)
					break
				}
			}
		} else {
			seen[t0Lower] = true
			ordered = append(ordered, topicGroup{topic0: t0Lower, events: []eventSpec{ev}})
		}
	}

	// Precompute the dispatch topic0 hashes and contract addresses once at package
	// init, instead of re-hashing/-decoding the string constants (and
	// allocating address.Hex()/toLowerASCII) on every AppendFromLog call — that
	// per-call common.HexToHash + checksum-hex was a large share of processor
	// allocations on the real corpus.
	for gi, grp := range ordered {
		fmt.Fprintf(&buf, "var _aflTopic%d = common.HexToHash(%q)\n", gi, grp.events[0].Topic0)
		for ei, ev := range grp.events {
			for ai, addr := range ev.ContractAddress {
				fmt.Fprintf(&buf, "var _aflAddr%d_%d_%d = common.HexToAddress(%q)\n", gi, ei, ai, addr)
			}
		}
	}
	fmt.Fprint(&buf, "\n")

	fmt.Fprint(&buf, "// AppendFromLog decodes a raw log directly into columns without heap allocations.\n")
	fmt.Fprint(&buf, "func (b *ProtoEventBlock) AppendFromLog(address common.Address, topics []common.Hash, data []byte, meta EventMeta) bool {\n")
	fmt.Fprint(&buf, "	if len(topics) == 0 {\n		return false\n	}\n")
	fmt.Fprint(&buf, "	topic0 := topics[0]\n")

	for gi, grp := range ordered {
		evs := grp.events

		fmt.Fprintf(&buf, "	if topic0 == _aflTopic%d {\n", gi)

		for ei, ev := range evs {
			extraIndent := ""
			if len(ev.ContractAddress) > 0 {
				var addrExprs []string
				for ai := range ev.ContractAddress {
					addrExprs = append(addrExprs, fmt.Sprintf("address == _aflAddr%d_%d_%d", gi, ei, ai))
				}
				fmt.Fprintf(&buf, "		if %s {\n", strings.Join(addrExprs, " || "))
				extraIndent = "	"
			}

			indent := "		" + extraIndent
			fmt.Fprintf(&buf, "%s// %s\n", indent, ev.GoTypeName)
			fmt.Fprintf(&buf, "%svar ev %s\n", indent, ev.GoTypeName)
			fmt.Fprintf(&buf, "%sev.EventMeta = meta\n", indent)
			fmt.Fprintf(&buf, "%svar ok bool\n%svar word []byte\n%s_ = ok\n%s_ = word\n", indent, indent, indent, indent)

			topicIdx := 1
			dataWord := 0
			decodeArgs := ev.DecodeArgs
			if len(decodeArgs) == 0 {
				decodeArgs = ev.Args
			}
			for _, arg := range decodeArgs {
				if arg.Indexed {
					if !arg.Omitted {
						topicExpr := fmt.Sprintf("topics[%d]", topicIdx)
						switch {
						case arg.SolidityType == "address":
							fmt.Fprintf(&buf, "%sev.%s = common.BytesToAddress(%s[12:])\n", indent, arg.GoFieldName, topicExpr)
						case arg.SolidityType == "bool":
							fmt.Fprintf(&buf, "%sev.%s = %s[31] == 1\n", indent, arg.GoFieldName, topicExpr)
						case arg.SolidityType == "bytes32":
							fmt.Fprintf(&buf, "%sev.%s = %s\n", indent, arg.GoFieldName, topicExpr)
						case strings.HasPrefix(arg.SolidityType, "uint"), strings.HasPrefix(arg.SolidityType, "int"):
							fmt.Fprintf(&buf, "%sev.%s.SetBytes32(%s[:])\n", indent, arg.GoFieldName, topicExpr)
						default:
							fmt.Fprintf(&buf, "%s// %s has unsupported indexed ABI type %q.\n", indent, arg.GoFieldName, arg.SolidityType)
						}
					}
					topicIdx++
					continue
				}
				if !arg.Omitted {
					var tempBuf bytes.Buffer
					renderDataDecode(&tempBuf, ev.GoTypeName, arg, dataWord)
					s := strings.ReplaceAll(tempBuf.String(), "return nil, fmt.Errorf", "return false // fmt.Errorf")
					// Indent the rendered decode lines.
					for _, line := range strings.Split(s, "\n") {
						if line != "" {
							fmt.Fprintf(&buf, "%s%s\n", indent, line)
						}
					}
				}
				dataWord += abiHeadWords(arg.SolidityType)
			}
			fmt.Fprintf(&buf, "%sb.Append%s(meta, &ev)\n", indent, ev.GoTypeName)
			fmt.Fprintf(&buf, "%sreturn true\n", indent)

			if len(ev.ContractAddress) > 0 {
				fmt.Fprint(&buf, "		}\n")
			}
		}

		fmt.Fprint(&buf, "	}\n")
	}
	fmt.Fprint(&buf, "	return false\n}\n\n")
	// Generate proto view types
	for _, ev := range events {
		fmt.Fprintf(&buf, "// %sProtoView is a zero-copy view into %s proto columns.\n", ev.GoTypeName, ev.GoTypeName)
		fmt.Fprint(&buf, "// It provides ECS-style access without allocation.\n")
		fmt.Fprintf(&buf, "type %sProtoView struct {\n", ev.GoTypeName)
		fmt.Fprint(&buf, "\tblock *ProtoEventBlock\n")
		fmt.Fprint(&buf, "\trow   int\n")
		fmt.Fprint(&buf, "}\n\n")

		for _, arg := range ev.Args {
			colName := ev.GoTypeName + "_" + camelToSnake(arg.GoFieldName)
			access := viewAccessExpr(colName, arg.GoType, "v.row")
			fmt.Fprintf(&buf, "func (v %sProtoView) %s() %s {\n", ev.GoTypeName, arg.GoFieldName, arg.GoType)
			fmt.Fprintf(&buf, "\treturn %s\n", access)
			fmt.Fprintf(&buf, "}\n\n")
		}
		fmt.Fprintf(&buf, "func (v %sProtoView) Meta() EventMeta {\n", ev.GoTypeName)
		fmt.Fprintf(&buf, "\treturn eventMetaAt(v.block, int(v.block.%s_meta_index[v.row]))\n", ev.GoTypeName)
		fmt.Fprintf(&buf, "}\n\n")
	}

	// Generate view constructors
	for _, ev := range events {
		fmt.Fprintf(&buf, "// %sProtoAt creates a zero-copy view into proto columns at row i.\n", ev.GoTypeName)
		fmt.Fprintf(&buf, "func (b *ProtoEventBlock) %sProtoAt(i int) %sProtoView {\n", ev.GoTypeName, ev.GoTypeName)
		fmt.Fprintf(&buf, "\treturn %sProtoView{block: b, row: i}\n", ev.GoTypeName)
		fmt.Fprint(&buf, "}\n\n")
	}

	// Generate query interfaces
	for _, ev := range events {
		queryType := ev.GoTypeName + "Query"
		fmt.Fprintf(&buf, "// %s provides ECS-style iteration over %s events.\n", queryType, ev.GoTypeName)
		fmt.Fprintf(&buf, "type %s struct {\n", queryType)
		fmt.Fprint(&buf, "\tblock *ProtoEventBlock\n")
		fmt.Fprint(&buf, "\tcount int\n")
		fmt.Fprint(&buf, "}\n\n")

		fmt.Fprintf(&buf, "// Query%s creates an iterator over %s events.\n", ev.GoTypeName, ev.GoTypeName)
		fmt.Fprintf(&buf, "func (b *ProtoEventBlock) Query%s() %s {\n", ev.GoTypeName, queryType)
		fmt.Fprintf(&buf, "\treturn %s{block: b, count: b.%s_meta_index.Rows()}\n", queryType, ev.GoTypeName)
		fmt.Fprint(&buf, "}\n\n")

		fmt.Fprint(&buf, "// Map iterates over all events, calling fn with zero-copy view.\n")
		fmt.Fprintf(&buf, "func (q %s) Map(fn func(%sProtoView)) {\n", queryType, ev.GoTypeName)
		fmt.Fprintf(&buf, "\tfor i := 0; i < q.count; i++ {\n")
		fmt.Fprintf(&buf, "\t\tfn(q.block.%sProtoAt(i))\n", ev.GoTypeName)
		fmt.Fprint(&buf, "\t}\n}\n\n")

		fmt.Fprint(&buf, "// MapWithIndex includes row index if needed.\n")
		fmt.Fprintf(&buf, "func (q %s) MapWithIndex(fn func(i int, view %sProtoView)) {\n", queryType, ev.GoTypeName)
		fmt.Fprintf(&buf, "\tfor i := 0; i < q.count; i++ {\n")
		fmt.Fprintf(&buf, "\t\tfn(i, q.block.%sProtoAt(i))\n", ev.GoTypeName)
		fmt.Fprint(&buf, "\t}\n}\n\n")
	}

	// Generate compatibility conversion back to struct blocks. Phase 4 will migrate
	// processors to views directly.
	fmt.Fprint(&buf, "// ToParsedBlock converts this proto block into the legacy struct block shape.\n")
	fmt.Fprint(&buf, "func (b *ProtoEventBlock) ToParsedBlock() *ParsedBlock {\n")
	fmt.Fprint(&buf, "\tif b == nil {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tblockNumber := b.HeaderBlockNumber\n")
	fmt.Fprint(&buf, "\tblockHash := b.HeaderBlockHash\n")
	fmt.Fprint(&buf, "\tif blockNumber == 0 && b.BlockNumber.Rows() > 0 {\n\t\tblockNumber = b.BlockNumber[0]\n\t}\n")
	fmt.Fprint(&buf, "\tif blockHash == \"\" && b.BlockHash.Rows() > 0 {\n\t\tblockHash = common.BytesToHash(b.BlockHash.Row(0)).Hex()\n\t}\n")
	fmt.Fprint(&buf, "\tblock := &ParsedBlock{\n")
	fmt.Fprint(&buf, "\t\tBlockNumber: blockNumber,\n")
	fmt.Fprint(&buf, "\t\tBlockHash: blockHash,\n")
	fmt.Fprint(&buf, "\t\tSequence: make([]uint8, 0, len(b.Sequence)),\n")
	for _, ev := range events {
		fmt.Fprintf(&buf, "\t\t%ss: make([]%s, 0, b.%s_meta_index.Rows()),\n", ev.GoTypeName, ev.GoTypeName, ev.GoTypeName)
	}
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\tvar (\n")
	for _, ev := range events {
		fmt.Fprintf(&buf, "\t\t%sIdx int\n", ev.GoTypeName)
	}
	fmt.Fprint(&buf, "\t)\n")
	fmt.Fprint(&buf, "\tfor _, typ := range b.Sequence {\n")
	fmt.Fprint(&buf, "\t\tblock.Sequence = append(block.Sequence, typ)\n")
	fmt.Fprint(&buf, "\t\tswitch EventType(typ) {\n")
	for _, ev := range events {
		fmt.Fprintf(&buf, "\t\tcase EventType%s:\n", ev.GoTypeName)
		fmt.Fprintf(&buf, "\t\t\tview := b.%sProtoAt(%sIdx)\n", ev.GoTypeName, ev.GoTypeName)
		fmt.Fprintf(&buf, "\t\t\tblock.%ss = append(block.%ss, %s{\n", ev.GoTypeName, ev.GoTypeName, ev.GoTypeName)
		fmt.Fprint(&buf, "\t\t\t\tEventMeta: view.Meta(),\n")
		for _, arg := range ev.Args {
			fmt.Fprintf(&buf, "\t\t\t\t%s: view.%s(),\n", arg.GoFieldName, arg.GoFieldName)
		}
		fmt.Fprint(&buf, "\t\t\t})\n")
		fmt.Fprintf(&buf, "\t\t\t%sIdx++\n", ev.GoTypeName)
	}
	fmt.Fprint(&buf, "\t\t}\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn block\n")
	fmt.Fprint(&buf, "}\n\n")

	// Generate helper functions
	fmt.Fprint(&buf, "// Helper: event metadata from columns\n")
	fmt.Fprint(&buf, "func eventMetaAt(b *ProtoEventBlock, i int) EventMeta {\n")
	fmt.Fprint(&buf, "\treturn EventMeta{\n")
	fmt.Fprint(&buf, "\t\tBlockNumber:      b.BlockNumber[i],\n")
	fmt.Fprint(&buf, "\t\tBlockHash:        common.BytesToHash(b.BlockHash.Row(i)),\n")
	fmt.Fprint(&buf, "\t\tBlockTimestamp:   b.BlockTS.Row(i),\n")
	fmt.Fprint(&buf, "\t\tContractAddress:  common.BytesToAddress(b.ContractAddr.Row(i)),\n")
	fmt.Fprint(&buf, "\t\tTransactionHash:  common.BytesToHash(b.TxHash.Row(i)),\n")
	fmt.Fprint(&buf, "\t\tTransactionIndex: b.TxIndex[i],\n")
	fmt.Fprint(&buf, "\t\tLogIndex:         b.LogIndex[i],\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "}\n\n")

	// Generate proto conversion helpers
	fmt.Fprint(&buf, "// Helper: zero-copy proto.UInt256 to uint256.Int\n")
	fmt.Fprint(&buf, "func uint256FromProto(p *proto.UInt256) uint256.Int {\n")
	fmt.Fprint(&buf, "\treturn uint256.Int{p.Low.Low, p.Low.High, p.High.Low, p.High.High}\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "func protoUint256Array(v []uint256.Int) string {\n")
	fmt.Fprint(&buf, "\tdata := make([]byte, 32+len(v)*32)\n")
	fmt.Fprint(&buf, "\twriteABIArrayLen(data[:32], len(v))\n")
	fmt.Fprint(&buf, "\tfor i := range v {\n")
	fmt.Fprint(&buf, "\t\tv[i].WriteToSlice(data[32+i*32 : 32+i*32+32])\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn \"0x\" + common.Bytes2Hex(data)\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "func protoHashArray(v []common.Hash) string {\n")
	fmt.Fprint(&buf, "\tdata := make([]byte, 32+len(v)*32)\n")
	fmt.Fprint(&buf, "\twriteABIArrayLen(data[:32], len(v))\n")
	fmt.Fprint(&buf, "\tfor i := range v {\n")
	fmt.Fprint(&buf, "\t\tcopy(data[32+i*32:32+i*32+32], v[i].Bytes())\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn \"0x\" + common.Bytes2Hex(data)\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "func protoAddressArray(v []common.Address) string {\n")
	fmt.Fprint(&buf, "\tdata := make([]byte, 32+len(v)*32)\n")
	fmt.Fprint(&buf, "\twriteABIArrayLen(data[:32], len(v))\n")
	fmt.Fprint(&buf, "\tfor i := range v {\n")
	fmt.Fprint(&buf, "\t\tcopy(data[32+i*32+12:32+i*32+32], v[i].Bytes())\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn \"0x\" + common.Bytes2Hex(data)\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "func protoBoolArray(v []bool) string {\n")
	fmt.Fprint(&buf, "\tdata := make([]byte, 32+len(v)*32)\n")
	fmt.Fprint(&buf, "\twriteABIArrayLen(data[:32], len(v))\n")
	fmt.Fprint(&buf, "\tfor i := range v {\n")
	fmt.Fprint(&buf, "\t\tif v[i] {\n\t\t\tdata[32+i*32+31] = 1\n\t\t}\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn \"0x\" + common.Bytes2Hex(data)\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "func writeABIArrayLen(dst []byte, n int) {\n")
	fmt.Fprint(&buf, "\tvar count uint256.Int\n")
	fmt.Fprint(&buf, "\tcount.SetUint64(uint64(n))\n")
	fmt.Fprint(&buf, "\tcount.WriteToSlice(dst)\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "// Helper: decode []uint256.Int from hex-encoded ABI data\n")
	fmt.Fprint(&buf, "func uint256ArrayFromProto(hex string) []uint256.Int {\n")
	fmt.Fprint(&buf, "\tif hex == \"\" {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tdata := common.FromHex(hex)\n")
	fmt.Fprint(&buf, "\tif len(data) < 32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\t// ABI encoding: length (32 bytes) + elements (32 bytes each)\n")
	fmt.Fprint(&buf, "\tvar count uint256.Int\n")
	fmt.Fprint(&buf, "\tcount.SetBytes32(data[:32])\n")
	fmt.Fprint(&buf, "\tnum := int(count.Uint64())\n")
	fmt.Fprint(&buf, "\tif num <= 0 || num*32 > len(data)-32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tresult := make([]uint256.Int, num)\n")
	fmt.Fprint(&buf, "\tfor i := 0; i < num; i++ {\n")
	fmt.Fprint(&buf, "\t\tresult[i].SetBytes32(data[32+i*32 : 32+i*32+32])\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn result\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "// Helper: decode []common.Address from hex-encoded ABI data\n")
	fmt.Fprint(&buf, "func addressArrayFromProto(hex string) []common.Address {\n")
	fmt.Fprint(&buf, "\tif hex == \"\" {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tdata := common.FromHex(hex)\n")
	fmt.Fprint(&buf, "\tif len(data) < 32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tvar count uint256.Int\n")
	fmt.Fprint(&buf, "\tcount.SetBytes32(data[:32])\n")
	fmt.Fprint(&buf, "\tnum := int(count.Uint64())\n")
	fmt.Fprint(&buf, "\tif num <= 0 || num*32 > len(data)-32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tresult := make([]common.Address, num)\n")
	fmt.Fprint(&buf, "\tfor i := 0; i < num; i++ {\n")
	fmt.Fprint(&buf, "\t\tresult[i] = common.BytesToAddress(data[32+i*32+12 : 32+i*32+32])\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn result\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "// Helper: decode []bool from hex-encoded ABI data\n")
	fmt.Fprint(&buf, "func boolArrayFromProto(hex string) []bool {\n")
	fmt.Fprint(&buf, "\tif hex == \"\" {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tdata := common.FromHex(hex)\n")
	fmt.Fprint(&buf, "\tif len(data) < 32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tvar count uint256.Int\n")
	fmt.Fprint(&buf, "\tcount.SetBytes32(data[:32])\n")
	fmt.Fprint(&buf, "\tnum := int(count.Uint64())\n")
	fmt.Fprint(&buf, "\tif num <= 0 || num*32 > len(data)-32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tresult := make([]bool, num)\n")
	fmt.Fprint(&buf, "\tfor i := 0; i < num; i++ {\n")
	fmt.Fprint(&buf, "\t\tresult[i] = data[32+i*32+31] != 0\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn result\n")
	fmt.Fprint(&buf, "}\n\n")

	fmt.Fprint(&buf, "// Helper: decode []common.Hash from hex-encoded ABI data\n")
	fmt.Fprint(&buf, "func hashArrayFromProto(hex string) []common.Hash {\n")
	fmt.Fprint(&buf, "\tif hex == \"\" {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tdata := common.FromHex(hex)\n")
	fmt.Fprint(&buf, "\tif len(data) < 32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tvar count uint256.Int\n")
	fmt.Fprint(&buf, "\tcount.SetBytes32(data[:32])\n")
	fmt.Fprint(&buf, "\tnum := int(count.Uint64())\n")
	fmt.Fprint(&buf, "\tif num <= 0 || num*32 > len(data)-32 {\n\t\treturn nil\n\t}\n")
	fmt.Fprint(&buf, "\tresult := make([]common.Hash, num)\n")
	fmt.Fprint(&buf, "\tfor i := 0; i < num; i++ {\n")
	fmt.Fprint(&buf, "\t\tcopy(result[i][:], data[32+i*32:32+i*32+32])\n")
	fmt.Fprint(&buf, "\t}\n")
	fmt.Fprint(&buf, "\treturn result\n")
	fmt.Fprint(&buf, "}\n")

	// Generate zero-copy inline processing function
	generateZeroCopyProcessing(&buf, events)

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("format source: %w", err)
	}
	return formatted, nil
}

// generateZeroCopyProcessing generates zero-copy iteration helpers for ProtoEventBlock
func generateZeroCopyProcessing(buf *bytes.Buffer, events []eventSpec) {
	fmt.Fprint(buf, `
// EventsIter returns a channel that yields events from this proto block in sequence order.
// It uses zero-copy views for memory efficiency.
func (b *ProtoEventBlock) EventsIter() chan DecodedLog {
	if b == nil {
		return nil
	}
	ch := make(chan DecodedLog, len(b.Sequence))
	go func() {
		defer close(ch)

		var (
`)
	// Per-event cursors into the proto columns, generated from THIS project's
	// events (previously hardcoded to the polymarket example, which left the idx
	// vars undefined/unused for every other project and broke compilation).
	for _, ev := range events {
		fmt.Fprintf(buf, "\t\t\t%sIdx int\n", ev.GoTypeName)
	}
	fmt.Fprint(buf, `		)

		for _, typ := range b.Sequence {
			switch EventType(typ) {
`)

	// Generate case statements for each event type
	for _, ev := range events {
		fmt.Fprintf(buf, "\t\t\tcase EventType%s:\n", ev.GoTypeName)
		fmt.Fprintf(buf, "\t\t\t\tview := b.%sProtoAt(%sIdx)\n", ev.GoTypeName, ev.GoTypeName)
		fmt.Fprintf(buf, "\t\t\t\tch <- DecodedLog{Value: &%s{EventMeta: view.Meta()", ev.GoTypeName)
		for _, arg := range ev.Args {
			fmt.Fprintf(buf, ", %s: view.%s()", arg.GoFieldName, arg.GoFieldName)
		}
		fmt.Fprintf(buf, "}}\n")
		fmt.Fprintf(buf, "\t\t\t\t%sIdx++\n", ev.GoTypeName)
	}

	fmt.Fprint(buf, "\t\t\t}\n\t\t}\n\t}()\n\treturn ch\n}\n")
}



// protoColType maps Go type to proto column type
func protoColType(goType string) string {
	switch goType {
	case "common.Address":
		return "proto.ColFixedStr // 20 bytes"
	case "common.Hash":
		return "proto.ColFixedStr // 32 bytes"
	case "uint256.Int":
		return "proto.ColUInt256"
	case "uint64", "uint":
		return "proto.ColUInt64"
	case "uint32":
		return "proto.ColUInt32"
	case "uint8":
		return "proto.ColUInt8"
	case "int64", "int":
		return "proto.ColInt64"
	case "bool":
		return "proto.ColUInt8"
	case "string":
		return "proto.ColStr"
	case "[]byte":
		return "proto.ColStr"
	case "[]uint256.Int":
		return "*proto.ColArr[proto.UInt256]"
	case "[]common.Hash", "[]common.Address":
		return "*proto.ColArr[[]byte]"
	case "[]bool":
		return "proto.ColStr"
	case "time.Time":
		return "proto.ColDateTime64"
	case "protomath.Decimal256":
		return "proto.ColDecimal256"
	case "decimal.Decimal":
		return "proto.ColDecimal256"
	default:
		return "proto.ColStr"
	}
}

// viewAccessExpr generates the expression to access a proto column value
func viewAccessExpr(colName, goType, index string) string {
	switch goType {
	case "common.Address":
		return fmt.Sprintf("common.BytesToAddress(v.block.%s.Row(%s))", colName, index)
	case "common.Hash":
		return fmt.Sprintf("common.BytesToHash(v.block.%s.Row(%s))", colName, index)
	case "uint256.Int":
		return fmt.Sprintf("uint256FromProto(&v.block.%s[%s])", colName, index)
	case "uint64", "uint":
		return fmt.Sprintf("v.block.%s[%s]", colName, index)
	case "uint32":
		return fmt.Sprintf("uint32(v.block.%s[%s])", colName, index)
	case "uint8":
		return fmt.Sprintf("v.block.%s[%s]", colName, index)
	case "int64", "int":
		return fmt.Sprintf("int64(v.block.%s[%s])", colName, index)
	case "bool":
		return fmt.Sprintf("v.block.%s[%s] != 0", colName, index)
	case "string":
		return fmt.Sprintf("v.block.%s.Row(%s)", colName, index)
	case "time.Time":
		return fmt.Sprintf("v.block.%s.Row(%s)", colName, index)
	case "protomath.Decimal256":
		return fmt.Sprintf("protomath.Decimal256(v.block.%s.Row(%s))", colName, index)
	case "decimal.Decimal":
		return fmt.Sprintf("decimalFromDecimal256(protomath.Decimal256(v.block.%s.Row(%s)))", colName, index)
	case "[]byte":
		return fmt.Sprintf("common.FromHex(v.block.%s.Row(%s))", colName, index)
	case "[]uint256.Int":
		return fmt.Sprintf("hotStateUint256Slice(v.block.%s.Row(%s))", colName, index)
	case "[]common.Hash":
		return fmt.Sprintf("hotStateHashSlice(v.block.%s.Row(%s))", colName, index)
	case "[]common.Address":
		return fmt.Sprintf("addressArrayFromProto(v.block.%s.Row(%s))", colName, index)
	case "[]bool":
		return fmt.Sprintf("boolArrayFromProto(v.block.%s.Row(%s))", colName, index)
	default:
		return fmt.Sprintf("v.block.%s.Row(%s)", colName, index)
	}
}

func protoAppendExpr(arg eventArg) string {
	switch arg.GoType {
	case "decimal.Decimal":
		return "fromDecimal(ev." + arg.GoFieldName + ").Proto()"
	case "[]uint256.Int":
		return "hotStateUInt256Slice(ev." + arg.GoFieldName + ", nil)"
	case "[]common.Hash":
		return "hotStateHashSliceBytes(ev." + arg.GoFieldName + ", nil)"
	case "[]common.Address":
		return "protoAddressArray(ev." + arg.GoFieldName + ")"
	case "[]bool":
		return "protoBoolArray(ev." + arg.GoFieldName + ")"
	default:
		return appendExpr(arg)
	}
}

// camelToSnake converts CamelCase to snake_case
func camelToSnake(s string) string {
	var result []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result = append(result, '_')
		}
		result = append(result, r)
	}
	return strings.ToLower(string(result))
}
