package polymarket

import (
	"testing"

	"github.com/ethereum/go-ethereum/common"
	generated "github.com/franz101/sqd-go/examples/polymarket/generated"
	"github.com/holiman/uint256"
)

// TestConditionColdTierRoundTripUnderEviction proves the storm fix: slice-bearing
// state entities (Condition.Payouts []uint256.Int, Market.QuestionIDs
// []common.Hash) now overflow to the Pebble cold tier via the generated byte codec
// instead of being dropped on hot-ring eviction. Before the fix, an evicted
// condition produced a hot miss with no disk tier behind it, forcing a synchronous
// ClickHouse point-SELECT per reference — the resumed-run SELECT storm.
//
// With a deliberately tiny hot ring (capacity 4) and 60 distinct conditions, the
// ring overflows many times over; every condition must still be retrievable with
// every field — crucially Payouts and the Tombstone flag — intact.
func TestConditionColdTierRoundTripUnderEviction(t *testing.T) {
	const (
		capacity = 4
		n        = 60
	)
	hs := generated.NewHotState(capacity)
	if err := hs.EnableColdCache(t.TempDir(), true, 0, 0); err != nil {
		t.Fatalf("enable cold cache: %v", err)
	}
	defer func() { _ = hs.CloseColdCache() }()

	mkID := func(seed, salt byte) common.Hash {
		var h common.Hash
		h[0], h[1], h[31] = seed, salt, byte(int(seed)*7+int(salt))
		return h
	}

	want := make([]generated.MemoryCondition, n)
	for i := 0; i < n; i++ {
		c := generated.MemoryCondition{
			ID:               mkID(byte(i), 0xC0),
			Oracle:           common.Address{byte(i), 0xAA},
			QuestionID:       mkID(byte(i), 0x99),
			OutcomeSlotCount: uint8(2 + i%5),
			Resolved:         i%2 == 0,
			UpdatedAtBlock:   uint64(1_000 + i),
			UpdatedAt:        int64(1_700_000_000_000 + i),
			BlockNumber:      uint64(80_000_000 + i),
			TxIndex:          uint64(i % 17),
			LogIndex:         uint64(i % 7),
			Tombstone:        i%9 == 0, // some evicted entries are tombstones
		}
		// Mix of payout shapes: empty (unresolved), binary, and categorical.
		switch i % 3 {
		case 0:
			c.Payouts = nil
		case 1:
			c.Payouts = []uint256.Int{*uint256.NewInt(1), *uint256.NewInt(0)}
		case 2:
			c.Payouts = []uint256.Int{
				*uint256.NewInt(uint64(i)),
				*uint256.NewInt(uint64(i) * 1_000_003),
				*new(uint256.Int).Lsh(uint256.NewInt(1), 200), // a genuinely large 256-bit value
			}
		}
		want[i] = c
		hs.Conditions.Set(c)
	}

	if hs.Conditions.Evictions() == 0 {
		t.Fatalf("expected evictions with capacity %d and %d sets, got 0", capacity, n)
	}

	for i := 0; i < n; i++ {
		got, ok := hs.Conditions.GetByFields(want[i].ID)
		if !ok {
			t.Fatalf("condition %d lost: not in hot OR cold (this is the storm bug)", i)
		}
		w := want[i]
		if got.Oracle != w.Oracle || got.QuestionID != w.QuestionID ||
			got.OutcomeSlotCount != w.OutcomeSlotCount || got.Resolved != w.Resolved ||
			got.UpdatedAtBlock != w.UpdatedAtBlock || got.UpdatedAt != w.UpdatedAt ||
			got.BlockNumber != w.BlockNumber || got.TxIndex != w.TxIndex ||
			got.LogIndex != w.LogIndex || got.Tombstone != w.Tombstone {
			t.Fatalf("condition %d scalar mismatch:\n got=%+v\nwant=%+v", i, got, w)
		}
		if len(got.Payouts) != len(w.Payouts) {
			t.Fatalf("condition %d payouts len=%d want=%d", i, len(got.Payouts), len(w.Payouts))
		}
		for j := range w.Payouts {
			if !got.Payouts[j].Eq(&w.Payouts[j]) {
				t.Fatalf("condition %d payout[%d]=%s want=%s", i, j, got.Payouts[j].Dec(), w.Payouts[j].Dec())
			}
		}
	}
}

// TestMarketColdTierRoundTripUnderEviction covers the other slice shape
// (Market.QuestionIDs []common.Hash) through the same overflow path.
func TestMarketColdTierRoundTripUnderEviction(t *testing.T) {
	const (
		capacity = 3
		n        = 40
	)
	hs := generated.NewHotState(capacity)
	if err := hs.EnableColdCache(t.TempDir(), true, 0, 0); err != nil {
		t.Fatalf("enable cold cache: %v", err)
	}
	defer func() { _ = hs.CloseColdCache() }()

	want := make([]generated.MemoryMarket, n)
	for i := 0; i < n; i++ {
		var id common.Hash
		id[0], id[31] = byte(i), 0xEE
		qids := make([]common.Hash, i%4) // 0..3 question ids
		for j := range qids {
			qids[j][0], qids[j][1] = byte(i), byte(j)
		}
		m := generated.MemoryMarket{
			ID:             id,
			QuestionCount:  uint32(len(qids)),
			QuestionIDs:    qids,
			UpdatedAtBlock: uint64(2_000 + i),
			BlockNumber:    uint64(81_000_000 + i),
		}
		want[i] = m
		hs.Markets.Set(m)
	}

	if hs.Markets.Evictions() == 0 {
		t.Fatalf("expected market evictions, got 0")
	}

	for i := 0; i < n; i++ {
		got, ok := hs.Markets.GetByFields(want[i].ID)
		if !ok {
			t.Fatalf("market %d lost: not in hot OR cold", i)
		}
		if got.QuestionCount != want[i].QuestionCount || len(got.QuestionIDs) != len(want[i].QuestionIDs) {
			t.Fatalf("market %d mismatch: got=%+v want=%+v", i, got, want[i])
		}
		for j := range want[i].QuestionIDs {
			if got.QuestionIDs[j] != want[i].QuestionIDs[j] {
				t.Fatalf("market %d qid[%d] mismatch", i, j)
			}
		}
	}
}
