name: polymarket
ecosystem: evm
store_blocks: false
store_raw_logs: false
# include_metadata: # EXCLUDED BY DEFAULT KEEP DISABLED
#   - chain_id
#   - block_hash
#   - contract_address
#   - transaction_hash
exclude_metadata:
  - OrderFilled: orderhash
state:
  - name: Condition
    source_table: memory_conditions
    key:
      - ID
    mode: hotstate
  - name: Position
    source_table: memory_user_positions
    key:
      - User
      - TokenID
    mode: hotstate
  - name: NegRiskEvent
    source_table: memory_neg_risk_events
    key:
      - ID
    mode: hotstate
  - name: FixedProductMarketMaker
    source_table: memory_fixed_product_market_makers
    key:
      - ID
    mode: hotstate
  - name: ConditionPreparation
    key:
      - conditionId
chains:
  - id: 137  # Polygon mainnet
    start_block: 33605403 # PNL TRICKLES IN AT BLOCK 36500000
    # start_block: 78000000
    contracts:
      - name: ConditionalTokens
        address: "0x4D97DCd97eC945f40cF65F87097ACe5EA0476045"
        events:
          - event: ConditionPreparation(bytes32 indexed conditionId, address indexed oracle, bytes32 indexed questionId, uint256 outcomeSlotCount)
          - event: ConditionResolution(bytes32 indexed conditionId, address indexed oracle, bytes32 indexed questionId, uint256 payoutDenominator, uint256[] payoutNumerators)
          - event: PositionSplit(address indexed stakeholder, address collateralToken, bytes32 indexed parentCollectionId, bytes32 indexed conditionId, uint256[] partition, uint256 amount)
          - event: PositionsMerge(address indexed stakeholder, address collateralToken, bytes32 indexed parentCollectionId, bytes32 indexed conditionId, uint256[] partition, uint256 amount)
          - event: PayoutRedemption(address indexed redeemer, address indexed collateralToken, bytes32 indexed parentCollectionId, bytes32 conditionId, uint256[] indexSets, uint256 payout)
      - name: Exchange
        address: "0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E"
        events:
          - event: OrderFilled(bytes32 indexed orderHash, address indexed maker, address indexed taker, uint256 makerAssetId, uint256 takerAssetId, uint256 makerAmountFilled, uint256 takerAmountFilled, uint256 fee)
      - name: NegRiskExchange
        address: "0xC5d563A36AE78145C45a50134d48A1215220f80a"
        events:
          - event: OrderFilled(bytes32 indexed orderHash, address indexed maker, address indexed taker, uint256 makerAssetId, uint256 takerAssetId, uint256 makerAmountFilled, uint256 takerAmountFilled, uint256 fee)
      - name: NegRiskAdapter
        address: "0xd91E80cF2E7be2e162c6513ceD06f1dD0dA35296"
        events:
          - event: MarketPrepared(bytes32 indexed marketId, address indexed creator, uint256 feeBips, bytes data)
          - event: QuestionPrepared(bytes32 indexed marketId, bytes32 indexed questionId, uint256 index, bytes data)
          - event: PositionSplit(address indexed stakeholder, bytes32 indexed conditionId, uint256 amount)
          - event: PositionsMerge(address indexed stakeholder, bytes32 indexed conditionId, uint256 amount)
          - event: PositionsConverted(address indexed stakeholder, bytes32 indexed marketId, uint256 indexed indexSet, uint256 amount)
          - event: PayoutRedemption(address indexed redeemer, bytes32 indexed conditionId, uint256[] amounts, uint256 payout)
      - name: FixedProductMarketMakerFactory
        address: "0x8B9805A2f595B6705e74F7310829f2d299D21522"
        events:
          - event: FixedProductMarketMakerCreation(address indexed creator, address fixedProductMarketMaker, address indexed conditionalTokens, address indexed collateralToken, bytes32[] conditionIds, uint256 fee)
      - name: FixedProductMarketMaker
        events:
          - event: FPMMBuy(address indexed buyer, uint256 investmentAmount, uint256 feeAmount, uint256 indexed outcomeIndex, uint256 outcomeTokensBought)
          - event: FPMMSell(address indexed seller, uint256 returnAmount, uint256 feeAmount, uint256 indexed outcomeIndex, uint256 outcomeTokensSold)
          - event: FPMMFundingAdded(address indexed funder, uint256[] amountsAdded, uint256 sharesMinted)
          - event: FPMMFundingRemoved(address indexed funder, uint256[] amountsRemoved, uint256 collateralRemovedFromFeePool, uint256 sharesBurnt)
